//
// (C) Copyright 2020-2021 Intel Corporation.
//
// SPDX-License-Identifier: BSD-2-Clause-Patent
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.14.0
// source: ctl/firmware.proto

package ctl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FirmwareUpdateReq_DeviceType int32

const (
	FirmwareUpdateReq_SCM  FirmwareUpdateReq_DeviceType = 0
	FirmwareUpdateReq_NVMe FirmwareUpdateReq_DeviceType = 1
)

// Enum value maps for FirmwareUpdateReq_DeviceType.
var (
	FirmwareUpdateReq_DeviceType_name = map[int32]string{
		0: "SCM",
		1: "NVMe",
	}
	FirmwareUpdateReq_DeviceType_value = map[string]int32{
		"SCM":  0,
		"NVMe": 1,
	}
)

func (x FirmwareUpdateReq_DeviceType) Enum() *FirmwareUpdateReq_DeviceType {
	p := new(FirmwareUpdateReq_DeviceType)
	*p = x
	return p
}

func (x FirmwareUpdateReq_DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirmwareUpdateReq_DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_ctl_firmware_proto_enumTypes[0].Descriptor()
}

func (FirmwareUpdateReq_DeviceType) Type() protoreflect.EnumType {
	return &file_ctl_firmware_proto_enumTypes[0]
}

func (x FirmwareUpdateReq_DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirmwareUpdateReq_DeviceType.Descriptor instead.
func (FirmwareUpdateReq_DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_ctl_firmware_proto_rawDescGZIP(), []int{4, 0}
}

type FirmwareQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryScm      bool                   `protobuf:"varint,1,opt,name=queryScm,proto3" json:"queryScm,omitempty"`      // Should we query SCM devices?
	QueryNvme     bool                   `protobuf:"varint,2,opt,name=queryNvme,proto3" json:"queryNvme,omitempty"`    // Should we query NVMe devices?
	DeviceIDs     []string               `protobuf:"bytes,3,rep,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`     // Filter by specific devices
	ModelID       string                 `protobuf:"bytes,4,opt,name=modelID,proto3" json:"modelID,omitempty"`         // Filter by model ID
	FirmwareRev   string                 `protobuf:"bytes,5,opt,name=firmwareRev,proto3" json:"firmwareRev,omitempty"` // Filter by current firmware revision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareQueryReq) Reset() {
	*x = FirmwareQueryReq{}
	mi := &file_ctl_firmware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareQueryReq) ProtoMessage() {}

func (x *FirmwareQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_firmware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareQueryReq.ProtoReflect.Descriptor instead.
func (*FirmwareQueryReq) Descriptor() ([]byte, []int) {
	return file_ctl_firmware_proto_rawDescGZIP(), []int{0}
}

func (x *FirmwareQueryReq) GetQueryScm() bool {
	if x != nil {
		return x.QueryScm
	}
	return false
}

func (x *FirmwareQueryReq) GetQueryNvme() bool {
	if x != nil {
		return x.QueryNvme
	}
	return false
}

func (x *FirmwareQueryReq) GetDeviceIDs() []string {
	if x != nil {
		return x.DeviceIDs
	}
	return nil
}

func (x *FirmwareQueryReq) GetModelID() string {
	if x != nil {
		return x.ModelID
	}
	return ""
}

func (x *FirmwareQueryReq) GetFirmwareRev() string {
	if x != nil {
		return x.FirmwareRev
	}
	return ""
}

type ScmFirmwareQueryResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Module            *ScmModule             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`                        // The module of this firmware
	ActiveVersion     string                 `protobuf:"bytes,2,opt,name=activeVersion,proto3" json:"activeVersion,omitempty"`          // Active FW version
	StagedVersion     string                 `protobuf:"bytes,3,opt,name=stagedVersion,proto3" json:"stagedVersion,omitempty"`          // Staged FW version
	ImageMaxSizeBytes uint32                 `protobuf:"varint,4,opt,name=imageMaxSizeBytes,proto3" json:"imageMaxSizeBytes,omitempty"` // Maximum size of FW image accepted
	UpdateStatus      uint32                 `protobuf:"varint,5,opt,name=updateStatus,proto3" json:"updateStatus,omitempty"`           // Status of FW update
	Error             string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                          // Error string, if any
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScmFirmwareQueryResp) Reset() {
	*x = ScmFirmwareQueryResp{}
	mi := &file_ctl_firmware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScmFirmwareQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScmFirmwareQueryResp) ProtoMessage() {}

func (x *ScmFirmwareQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_firmware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScmFirmwareQueryResp.ProtoReflect.Descriptor instead.
func (*ScmFirmwareQueryResp) Descriptor() ([]byte, []int) {
	return file_ctl_firmware_proto_rawDescGZIP(), []int{1}
}

func (x *ScmFirmwareQueryResp) GetModule() *ScmModule {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *ScmFirmwareQueryResp) GetActiveVersion() string {
	if x != nil {
		return x.ActiveVersion
	}
	return ""
}

func (x *ScmFirmwareQueryResp) GetStagedVersion() string {
	if x != nil {
		return x.StagedVersion
	}
	return ""
}

func (x *ScmFirmwareQueryResp) GetImageMaxSizeBytes() uint32 {
	if x != nil {
		return x.ImageMaxSizeBytes
	}
	return 0
}

func (x *ScmFirmwareQueryResp) GetUpdateStatus() uint32 {
	if x != nil {
		return x.UpdateStatus
	}
	return 0
}

func (x *ScmFirmwareQueryResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NvmeFirmwareQueryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *NvmeController        `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"` // Controller information includes FW rev
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NvmeFirmwareQueryResp) Reset() {
	*x = NvmeFirmwareQueryResp{}
	mi := &file_ctl_firmware_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NvmeFirmwareQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NvmeFirmwareQueryResp) ProtoMessage() {}

func (x *NvmeFirmwareQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_firmware_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NvmeFirmwareQueryResp.ProtoReflect.Descriptor instead.
func (*NvmeFirmwareQueryResp) Descriptor() ([]byte, []int) {
	return file_ctl_firmware_proto_rawDescGZIP(), []int{2}
}

func (x *NvmeFirmwareQueryResp) GetDevice() *NvmeController {
	if x != nil {
		return x.Device
	}
	return nil
}

type FirmwareQueryResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ScmResults    []*ScmFirmwareQueryResp  `protobuf:"bytes,1,rep,name=scmResults,proto3" json:"scmResults,omitempty"`
	NvmeResults   []*NvmeFirmwareQueryResp `protobuf:"bytes,2,rep,name=nvmeResults,proto3" json:"nvmeResults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareQueryResp) Reset() {
	*x = FirmwareQueryResp{}
	mi := &file_ctl_firmware_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareQueryResp) ProtoMessage() {}

func (x *FirmwareQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_firmware_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareQueryResp.ProtoReflect.Descriptor instead.
func (*FirmwareQueryResp) Descriptor() ([]byte, []int) {
	return file_ctl_firmware_proto_rawDescGZIP(), []int{3}
}

func (x *FirmwareQueryResp) GetScmResults() []*ScmFirmwareQueryResp {
	if x != nil {
		return x.ScmResults
	}
	return nil
}

func (x *FirmwareQueryResp) GetNvmeResults() []*NvmeFirmwareQueryResp {
	if x != nil {
		return x.NvmeResults
	}
	return nil
}

type FirmwareUpdateReq struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	FirmwarePath  string                       `protobuf:"bytes,1,opt,name=firmwarePath,proto3" json:"firmwarePath,omitempty"`                        // Path to firmware file
	Type          FirmwareUpdateReq_DeviceType `protobuf:"varint,2,opt,name=type,proto3,enum=ctl.FirmwareUpdateReq_DeviceType" json:"type,omitempty"` // Type of device this firmware applies to
	DeviceIDs     []string                     `protobuf:"bytes,3,rep,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`                              // Devices this update applies to
	ModelID       string                       `protobuf:"bytes,4,opt,name=modelID,proto3" json:"modelID,omitempty"`                                  // Model ID this update applies to
	FirmwareRev   string                       `protobuf:"bytes,5,opt,name=firmwareRev,proto3" json:"firmwareRev,omitempty"`                          // Starting FW rev this update applies to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareUpdateReq) Reset() {
	*x = FirmwareUpdateReq{}
	mi := &file_ctl_firmware_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareUpdateReq) ProtoMessage() {}

func (x *FirmwareUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_firmware_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareUpdateReq.ProtoReflect.Descriptor instead.
func (*FirmwareUpdateReq) Descriptor() ([]byte, []int) {
	return file_ctl_firmware_proto_rawDescGZIP(), []int{4}
}

func (x *FirmwareUpdateReq) GetFirmwarePath() string {
	if x != nil {
		return x.FirmwarePath
	}
	return ""
}

func (x *FirmwareUpdateReq) GetType() FirmwareUpdateReq_DeviceType {
	if x != nil {
		return x.Type
	}
	return FirmwareUpdateReq_SCM
}

func (x *FirmwareUpdateReq) GetDeviceIDs() []string {
	if x != nil {
		return x.DeviceIDs
	}
	return nil
}

func (x *FirmwareUpdateReq) GetModelID() string {
	if x != nil {
		return x.ModelID
	}
	return ""
}

func (x *FirmwareUpdateReq) GetFirmwareRev() string {
	if x != nil {
		return x.FirmwareRev
	}
	return ""
}

type ScmFirmwareUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ScmModule             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"` // SCM device
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`   // empty if successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScmFirmwareUpdateResp) Reset() {
	*x = ScmFirmwareUpdateResp{}
	mi := &file_ctl_firmware_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScmFirmwareUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScmFirmwareUpdateResp) ProtoMessage() {}

func (x *ScmFirmwareUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_firmware_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScmFirmwareUpdateResp.ProtoReflect.Descriptor instead.
func (*ScmFirmwareUpdateResp) Descriptor() ([]byte, []int) {
	return file_ctl_firmware_proto_rawDescGZIP(), []int{5}
}

func (x *ScmFirmwareUpdateResp) GetModule() *ScmModule {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *ScmFirmwareUpdateResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NvmeFirmwareUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PciAddr       string                 `protobuf:"bytes,1,opt,name=pciAddr,proto3" json:"pciAddr,omitempty"` // PCI address of the NVMe device
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`     // empty if successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NvmeFirmwareUpdateResp) Reset() {
	*x = NvmeFirmwareUpdateResp{}
	mi := &file_ctl_firmware_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NvmeFirmwareUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NvmeFirmwareUpdateResp) ProtoMessage() {}

func (x *NvmeFirmwareUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_firmware_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NvmeFirmwareUpdateResp.ProtoReflect.Descriptor instead.
func (*NvmeFirmwareUpdateResp) Descriptor() ([]byte, []int) {
	return file_ctl_firmware_proto_rawDescGZIP(), []int{6}
}

func (x *NvmeFirmwareUpdateResp) GetPciAddr() string {
	if x != nil {
		return x.PciAddr
	}
	return ""
}

func (x *NvmeFirmwareUpdateResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FirmwareUpdateResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ScmResults    []*ScmFirmwareUpdateResp  `protobuf:"bytes,1,rep,name=scmResults,proto3" json:"scmResults,omitempty"`   // results for SCM update
	NvmeResults   []*NvmeFirmwareUpdateResp `protobuf:"bytes,2,rep,name=nvmeResults,proto3" json:"nvmeResults,omitempty"` // results for NVMe update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareUpdateResp) Reset() {
	*x = FirmwareUpdateResp{}
	mi := &file_ctl_firmware_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareUpdateResp) ProtoMessage() {}

func (x *FirmwareUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_firmware_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareUpdateResp.ProtoReflect.Descriptor instead.
func (*FirmwareUpdateResp) Descriptor() ([]byte, []int) {
	return file_ctl_firmware_proto_rawDescGZIP(), []int{7}
}

func (x *FirmwareUpdateResp) GetScmResults() []*ScmFirmwareUpdateResp {
	if x != nil {
		return x.ScmResults
	}
	return nil
}

func (x *FirmwareUpdateResp) GetNvmeResults() []*NvmeFirmwareUpdateResp {
	if x != nil {
		return x.NvmeResults
	}
	return nil
}

var File_ctl_firmware_proto protoreflect.FileDescriptor

const file_ctl_firmware_proto_rawDesc = "" +
	"\n" +
	"\x12ctl/firmware.proto\x12\x03ctl\x1a\x15ctl/storage_scm.proto\x1a\rctl/smd.proto\"\xa6\x01\n" +
	"\x10FirmwareQueryReq\x12\x1a\n" +
	"\bqueryScm\x18\x01 \x01(\bR\bqueryScm\x12\x1c\n" +
	"\tqueryNvme\x18\x02 \x01(\bR\tqueryNvme\x12\x1c\n" +
	"\tdeviceIDs\x18\x03 \x03(\tR\tdeviceIDs\x12\x18\n" +
	"\amodelID\x18\x04 \x01(\tR\amodelID\x12 \n" +
	"\vfirmwareRev\x18\x05 \x01(\tR\vfirmwareRev\"\xf2\x01\n" +
	"\x14ScmFirmwareQueryResp\x12&\n" +
	"\x06module\x18\x01 \x01(\v2\x0e.ctl.ScmModuleR\x06module\x12$\n" +
	"\ractiveVersion\x18\x02 \x01(\tR\ractiveVersion\x12$\n" +
	"\rstagedVersion\x18\x03 \x01(\tR\rstagedVersion\x12,\n" +
	"\x11imageMaxSizeBytes\x18\x04 \x01(\rR\x11imageMaxSizeBytes\x12\"\n" +
	"\fupdateStatus\x18\x05 \x01(\rR\fupdateStatus\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"D\n" +
	"\x15NvmeFirmwareQueryResp\x12+\n" +
	"\x06device\x18\x01 \x01(\v2\x13.ctl.NvmeControllerR\x06device\"\x8c\x01\n" +
	"\x11FirmwareQueryResp\x129\n" +
	"\n" +
	"scmResults\x18\x01 \x03(\v2\x19.ctl.ScmFirmwareQueryRespR\n" +
	"scmResults\x12<\n" +
	"\vnvmeResults\x18\x02 \x03(\v2\x1a.ctl.NvmeFirmwareQueryRespR\vnvmeResults\"\xe9\x01\n" +
	"\x11FirmwareUpdateReq\x12\"\n" +
	"\ffirmwarePath\x18\x01 \x01(\tR\ffirmwarePath\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.ctl.FirmwareUpdateReq.DeviceTypeR\x04type\x12\x1c\n" +
	"\tdeviceIDs\x18\x03 \x03(\tR\tdeviceIDs\x12\x18\n" +
	"\amodelID\x18\x04 \x01(\tR\amodelID\x12 \n" +
	"\vfirmwareRev\x18\x05 \x01(\tR\vfirmwareRev\"\x1f\n" +
	"\n" +
	"DeviceType\x12\a\n" +
	"\x03SCM\x10\x00\x12\b\n" +
	"\x04NVMe\x10\x01\"U\n" +
	"\x15ScmFirmwareUpdateResp\x12&\n" +
	"\x06module\x18\x01 \x01(\v2\x0e.ctl.ScmModuleR\x06module\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"H\n" +
	"\x16NvmeFirmwareUpdateResp\x12\x18\n" +
	"\apciAddr\x18\x01 \x01(\tR\apciAddr\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8f\x01\n" +
	"\x12FirmwareUpdateResp\x12:\n" +
	"\n" +
	"scmResults\x18\x01 \x03(\v2\x1a.ctl.ScmFirmwareUpdateRespR\n" +
	"scmResults\x12=\n" +
	"\vnvmeResults\x18\x02 \x03(\v2\x1b.ctl.NvmeFirmwareUpdateRespR\vnvmeResultsB9Z7github.com/daos-stack/daos/src/control/common/proto/ctlb\x06proto3"

var (
	file_ctl_firmware_proto_rawDescOnce sync.Once
	file_ctl_firmware_proto_rawDescData []byte
)

func file_ctl_firmware_proto_rawDescGZIP() []byte {
	file_ctl_firmware_proto_rawDescOnce.Do(func() {
		file_ctl_firmware_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ctl_firmware_proto_rawDesc), len(file_ctl_firmware_proto_rawDesc)))
	})
	return file_ctl_firmware_proto_rawDescData
}

var file_ctl_firmware_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ctl_firmware_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ctl_firmware_proto_goTypes = []any{
	(FirmwareUpdateReq_DeviceType)(0), // 0: ctl.FirmwareUpdateReq.DeviceType
	(*FirmwareQueryReq)(nil),          // 1: ctl.FirmwareQueryReq
	(*ScmFirmwareQueryResp)(nil),      // 2: ctl.ScmFirmwareQueryResp
	(*NvmeFirmwareQueryResp)(nil),     // 3: ctl.NvmeFirmwareQueryResp
	(*FirmwareQueryResp)(nil),         // 4: ctl.FirmwareQueryResp
	(*FirmwareUpdateReq)(nil),         // 5: ctl.FirmwareUpdateReq
	(*ScmFirmwareUpdateResp)(nil),     // 6: ctl.ScmFirmwareUpdateResp
	(*NvmeFirmwareUpdateResp)(nil),    // 7: ctl.NvmeFirmwareUpdateResp
	(*FirmwareUpdateResp)(nil),        // 8: ctl.FirmwareUpdateResp
	(*ScmModule)(nil),                 // 9: ctl.ScmModule
	(*NvmeController)(nil),            // 10: ctl.NvmeController
}
var file_ctl_firmware_proto_depIdxs = []int32{
	9,  // 0: ctl.ScmFirmwareQueryResp.module:type_name -> ctl.ScmModule
	10, // 1: ctl.NvmeFirmwareQueryResp.device:type_name -> ctl.NvmeController
	2,  // 2: ctl.FirmwareQueryResp.scmResults:type_name -> ctl.ScmFirmwareQueryResp
	3,  // 3: ctl.FirmwareQueryResp.nvmeResults:type_name -> ctl.NvmeFirmwareQueryResp
	0,  // 4: ctl.FirmwareUpdateReq.type:type_name -> ctl.FirmwareUpdateReq.DeviceType
	9,  // 5: ctl.ScmFirmwareUpdateResp.module:type_name -> ctl.ScmModule
	6,  // 6: ctl.FirmwareUpdateResp.scmResults:type_name -> ctl.ScmFirmwareUpdateResp
	7,  // 7: ctl.FirmwareUpdateResp.nvmeResults:type_name -> ctl.NvmeFirmwareUpdateResp
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ctl_firmware_proto_init() }
func file_ctl_firmware_proto_init() {
	if File_ctl_firmware_proto != nil {
		return
	}
	file_ctl_storage_scm_proto_init()
	file_ctl_smd_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ctl_firmware_proto_rawDesc), len(file_ctl_firmware_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ctl_firmware_proto_goTypes,
		DependencyIndexes: file_ctl_firmware_proto_depIdxs,
		EnumInfos:         file_ctl_firmware_proto_enumTypes,
		MessageInfos:      file_ctl_firmware_proto_msgTypes,
	}.Build()
	File_ctl_firmware_proto = out.File
	file_ctl_firmware_proto_goTypes = nil
	file_ctl_firmware_proto_depIdxs = nil
}
