//
// (C) Copyright 2019-2024 Intel Corporation.
//
// SPDX-License-Identifier: BSD-2-Clause-Patent
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.14.0
// source: ctl/storage_nvme.proto

package ctl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NvmeControllerResult represents state of operation performed on controller.
type NvmeControllerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PciAddr       string                 `protobuf:"bytes,1,opt,name=pci_addr,json=pciAddr,proto3" json:"pci_addr,omitempty"`     // PCI address of NVMe controller
	State         *ResponseState         `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                        // state of current operation
	RoleBits      uint32                 `protobuf:"varint,3,opt,name=role_bits,json=roleBits,proto3" json:"role_bits,omitempty"` // Device active roles (bitmask)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NvmeControllerResult) Reset() {
	*x = NvmeControllerResult{}
	mi := &file_ctl_storage_nvme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NvmeControllerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NvmeControllerResult) ProtoMessage() {}

func (x *NvmeControllerResult) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_storage_nvme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NvmeControllerResult.ProtoReflect.Descriptor instead.
func (*NvmeControllerResult) Descriptor() ([]byte, []int) {
	return file_ctl_storage_nvme_proto_rawDescGZIP(), []int{0}
}

func (x *NvmeControllerResult) GetPciAddr() string {
	if x != nil {
		return x.PciAddr
	}
	return ""
}

func (x *NvmeControllerResult) GetState() *ResponseState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *NvmeControllerResult) GetRoleBits() uint32 {
	if x != nil {
		return x.RoleBits
	}
	return 0
}

type ScanNvmeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        bool                   `protobuf:"varint,1,opt,name=Health,proto3" json:"Health,omitempty"`       // Retrieve NVMe device health statistics
	Meta          bool                   `protobuf:"varint,2,opt,name=Meta,proto3" json:"Meta,omitempty"`           // Retrieve metadata relating to NVMe device
	Basic         bool                   `protobuf:"varint,3,opt,name=Basic,proto3" json:"Basic,omitempty"`         // Strip NVMe device details to only basic
	MetaSize      uint64                 `protobuf:"varint,4,opt,name=MetaSize,proto3" json:"MetaSize,omitempty"`   // Size of the metadata blob
	RdbSize       uint64                 `protobuf:"varint,5,opt,name=RdbSize,proto3" json:"RdbSize,omitempty"`     // Size of the RDB blob
	MemRatio      float32                `protobuf:"fixed32,6,opt,name=MemRatio,proto3" json:"MemRatio,omitempty"`  // Ratio of VOS-file:meta-blob sizes
	LinkStats     bool                   `protobuf:"varint,7,opt,name=LinkStats,proto3" json:"LinkStats,omitempty"` // Populate PCIe link info in health statistics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanNvmeReq) Reset() {
	*x = ScanNvmeReq{}
	mi := &file_ctl_storage_nvme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanNvmeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanNvmeReq) ProtoMessage() {}

func (x *ScanNvmeReq) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_storage_nvme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanNvmeReq.ProtoReflect.Descriptor instead.
func (*ScanNvmeReq) Descriptor() ([]byte, []int) {
	return file_ctl_storage_nvme_proto_rawDescGZIP(), []int{1}
}

func (x *ScanNvmeReq) GetHealth() bool {
	if x != nil {
		return x.Health
	}
	return false
}

func (x *ScanNvmeReq) GetMeta() bool {
	if x != nil {
		return x.Meta
	}
	return false
}

func (x *ScanNvmeReq) GetBasic() bool {
	if x != nil {
		return x.Basic
	}
	return false
}

func (x *ScanNvmeReq) GetMetaSize() uint64 {
	if x != nil {
		return x.MetaSize
	}
	return 0
}

func (x *ScanNvmeReq) GetRdbSize() uint64 {
	if x != nil {
		return x.RdbSize
	}
	return 0
}

func (x *ScanNvmeReq) GetMemRatio() float32 {
	if x != nil {
		return x.MemRatio
	}
	return 0
}

func (x *ScanNvmeReq) GetLinkStats() bool {
	if x != nil {
		return x.LinkStats
	}
	return false
}

type ScanNvmeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctrlrs        []*NvmeController      `protobuf:"bytes,1,rep,name=ctrlrs,proto3" json:"ctrlrs,omitempty"`
	State         *ResponseState         `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanNvmeResp) Reset() {
	*x = ScanNvmeResp{}
	mi := &file_ctl_storage_nvme_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanNvmeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanNvmeResp) ProtoMessage() {}

func (x *ScanNvmeResp) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_storage_nvme_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanNvmeResp.ProtoReflect.Descriptor instead.
func (*ScanNvmeResp) Descriptor() ([]byte, []int) {
	return file_ctl_storage_nvme_proto_rawDescGZIP(), []int{2}
}

func (x *ScanNvmeResp) GetCtrlrs() []*NvmeController {
	if x != nil {
		return x.Ctrlrs
	}
	return nil
}

func (x *ScanNvmeResp) GetState() *ResponseState {
	if x != nil {
		return x.State
	}
	return nil
}

type FormatNvmeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatNvmeReq) Reset() {
	*x = FormatNvmeReq{}
	mi := &file_ctl_storage_nvme_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatNvmeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatNvmeReq) ProtoMessage() {}

func (x *FormatNvmeReq) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_storage_nvme_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatNvmeReq.ProtoReflect.Descriptor instead.
func (*FormatNvmeReq) Descriptor() ([]byte, []int) {
	return file_ctl_storage_nvme_proto_rawDescGZIP(), []int{3}
}

var File_ctl_storage_nvme_proto protoreflect.FileDescriptor

const file_ctl_storage_nvme_proto_rawDesc = "" +
	"\n" +
	"\x16ctl/storage_nvme.proto\x12\x03ctl\x1a\x10ctl/common.proto\x1a\rctl/smd.proto\"x\n" +
	"\x14NvmeControllerResult\x12\x19\n" +
	"\bpci_addr\x18\x01 \x01(\tR\apciAddr\x12(\n" +
	"\x05state\x18\x02 \x01(\v2\x12.ctl.ResponseStateR\x05state\x12\x1b\n" +
	"\trole_bits\x18\x03 \x01(\rR\broleBits\"\xbf\x01\n" +
	"\vScanNvmeReq\x12\x16\n" +
	"\x06Health\x18\x01 \x01(\bR\x06Health\x12\x12\n" +
	"\x04Meta\x18\x02 \x01(\bR\x04Meta\x12\x14\n" +
	"\x05Basic\x18\x03 \x01(\bR\x05Basic\x12\x1a\n" +
	"\bMetaSize\x18\x04 \x01(\x04R\bMetaSize\x12\x18\n" +
	"\aRdbSize\x18\x05 \x01(\x04R\aRdbSize\x12\x1a\n" +
	"\bMemRatio\x18\x06 \x01(\x02R\bMemRatio\x12\x1c\n" +
	"\tLinkStats\x18\a \x01(\bR\tLinkStats\"e\n" +
	"\fScanNvmeResp\x12+\n" +
	"\x06ctrlrs\x18\x01 \x03(\v2\x13.ctl.NvmeControllerR\x06ctrlrs\x12(\n" +
	"\x05state\x18\x02 \x01(\v2\x12.ctl.ResponseStateR\x05state\"\x0f\n" +
	"\rFormatNvmeReqB9Z7github.com/daos-stack/daos/src/control/common/proto/ctlb\x06proto3"

var (
	file_ctl_storage_nvme_proto_rawDescOnce sync.Once
	file_ctl_storage_nvme_proto_rawDescData []byte
)

func file_ctl_storage_nvme_proto_rawDescGZIP() []byte {
	file_ctl_storage_nvme_proto_rawDescOnce.Do(func() {
		file_ctl_storage_nvme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ctl_storage_nvme_proto_rawDesc), len(file_ctl_storage_nvme_proto_rawDesc)))
	})
	return file_ctl_storage_nvme_proto_rawDescData
}

var file_ctl_storage_nvme_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ctl_storage_nvme_proto_goTypes = []any{
	(*NvmeControllerResult)(nil), // 0: ctl.NvmeControllerResult
	(*ScanNvmeReq)(nil),          // 1: ctl.ScanNvmeReq
	(*ScanNvmeResp)(nil),         // 2: ctl.ScanNvmeResp
	(*FormatNvmeReq)(nil),        // 3: ctl.FormatNvmeReq
	(*ResponseState)(nil),        // 4: ctl.ResponseState
	(*NvmeController)(nil),       // 5: ctl.NvmeController
}
var file_ctl_storage_nvme_proto_depIdxs = []int32{
	4, // 0: ctl.NvmeControllerResult.state:type_name -> ctl.ResponseState
	5, // 1: ctl.ScanNvmeResp.ctrlrs:type_name -> ctl.NvmeController
	4, // 2: ctl.ScanNvmeResp.state:type_name -> ctl.ResponseState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ctl_storage_nvme_proto_init() }
func file_ctl_storage_nvme_proto_init() {
	if File_ctl_storage_nvme_proto != nil {
		return
	}
	file_ctl_common_proto_init()
	file_ctl_smd_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ctl_storage_nvme_proto_rawDesc), len(file_ctl_storage_nvme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ctl_storage_nvme_proto_goTypes,
		DependencyIndexes: file_ctl_storage_nvme_proto_depIdxs,
		MessageInfos:      file_ctl_storage_nvme_proto_msgTypes,
	}.Build()
	File_ctl_storage_nvme_proto = out.File
	file_ctl_storage_nvme_proto_goTypes = nil
	file_ctl_storage_nvme_proto_depIdxs = nil
}
