// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ctl/system.proto

package ctl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SystemMember refers to a data-plane instance that is a member of DAOS
// system running on host with the control-plane listening at "Addr".
type SystemMember struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Rank                 uint32   `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	State                uint32   `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemMember) Reset()         { *m = SystemMember{} }
func (m *SystemMember) String() string { return proto.CompactTextString(m) }
func (*SystemMember) ProtoMessage()    {}
func (*SystemMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef8179e5b0aee00, []int{0}
}

func (m *SystemMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemMember.Unmarshal(m, b)
}
func (m *SystemMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemMember.Marshal(b, m, deterministic)
}
func (m *SystemMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemMember.Merge(m, src)
}
func (m *SystemMember) XXX_Size() int {
	return xxx_messageInfo_SystemMember.Size(m)
}
func (m *SystemMember) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemMember.DiscardUnknown(m)
}

var xxx_messageInfo_SystemMember proto.InternalMessageInfo

func (m *SystemMember) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *SystemMember) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SystemMember) GetRank() uint32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *SystemMember) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

// SystemQueryResp returns active system members.
type SystemQueryResp struct {
	Members              []*SystemMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SystemQueryResp) Reset()         { *m = SystemQueryResp{} }
func (m *SystemQueryResp) String() string { return proto.CompactTextString(m) }
func (*SystemQueryResp) ProtoMessage()    {}
func (*SystemQueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef8179e5b0aee00, []int{1}
}

func (m *SystemQueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemQueryResp.Unmarshal(m, b)
}
func (m *SystemQueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemQueryResp.Marshal(b, m, deterministic)
}
func (m *SystemQueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemQueryResp.Merge(m, src)
}
func (m *SystemQueryResp) XXX_Size() int {
	return xxx_messageInfo_SystemQueryResp.Size(m)
}
func (m *SystemQueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemQueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_SystemQueryResp proto.InternalMessageInfo

func (m *SystemQueryResp) GetMembers() []*SystemMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*SystemMember)(nil), "ctl.SystemMember")
	proto.RegisterType((*SystemQueryResp)(nil), "ctl.SystemQueryResp")
}

func init() { proto.RegisterFile("ctl/system.proto", fileDescriptor_aef8179e5b0aee00) }

var fileDescriptor_aef8179e5b0aee00 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x2e, 0xc9, 0xd1,
	0x2f, 0xae, 0x2c, 0x2e, 0x49, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2e,
	0xc9, 0x51, 0x4a, 0xe0, 0xe2, 0x09, 0x06, 0x0b, 0xfa, 0xa6, 0xe6, 0x26, 0xa5, 0x16, 0x09, 0x09,
	0x71, 0xb1, 0x24, 0xa6, 0xa4, 0x14, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x20,
	0xb1, 0xd2, 0xd2, 0xcc, 0x14, 0x09, 0x26, 0x88, 0x18, 0x88, 0x0d, 0x12, 0x2b, 0x4a, 0xcc, 0xcb,
	0x96, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x0d, 0x02, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0x8b, 0x4b, 0x12,
	0x4b, 0x52, 0x25, 0x58, 0xc0, 0x82, 0x10, 0x8e, 0x92, 0x1d, 0x17, 0x3f, 0xc4, 0x86, 0xc0, 0xd2,
	0xd4, 0xa2, 0xca, 0xa0, 0xd4, 0xe2, 0x02, 0x21, 0x6d, 0x2e, 0xf6, 0x5c, 0xb0, 0x75, 0xc5, 0x12,
	0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x82, 0x7a, 0xc9, 0x25, 0x39, 0x7a, 0xc8, 0x0e, 0x09, 0x82,
	0xa9, 0x48, 0x62, 0x03, 0xbb, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xdc, 0x97, 0xf7,
	0xc1, 0x00, 0x00, 0x00,
}
