#!python

Import('env')

env.AppendUnique(LIBPATH=[Dir('.')])
denv = env.Clone()

# generate server module
srv = denv.SharedLibrary('daos_ct_srv', Glob('*.c'))
denv.Install('$PREFIX/lib/daos_srv', srv)

# generate client library
client = denv.SharedLibrary('daos_ct', Glob('*.c'))
denv.Install('$PREFIX/lib/', client)
