"""Install DAOS Storage Estimador"""

def install_storage_estimator_module(env, lib_prefix, version):
    """Install Storage Estimador module for the specified python version"""

    if GetOption("help"):
        return

    denv = env.Clone()

    install_path = lib_prefix + "/python"
    install_path += version + "/site-packages/storage_estimator"

    denv.Install(install_path, "common/vos_structures.py")
    denv.Install(install_path, "common/__init__.py")
    denv.Install(install_path, "common/dfs_sb.py")
    denv.Install(install_path, "common/vos_size.py")
    denv.Install(install_path, "common/explorer.py")
    denv.Install(install_path, "common/parse_csv.py")
    denv.Install(install_path, "common/util.py")

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    denv = env.Clone()
    denv.Install("$PREFIX/bin/", "daos_storage_estimator.py")

    install_storage_estimator_module(env, '$PREFIX/lib64/', "3")

if __name__ == "SCons.Script":
    scons()
