#!python
# (C) Copyright 2016-2020 Intel Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# GOVERNMENT LICENSE RIGHTS-OPEN SOURCE SOFTWARE
# The Government's rights to use, modify, reproduce, release, perform, display,
# or disclose this software are subject to the terms of the Apache License as
# provided in Contract No. 8F-30005.
# Any reproduction of computer software, computer software documentation, or
# portions thereof marked with this legend must also reproduce the markings.
#
"""Build crt_launch"""
import os
import sys
import daos_build

CRT_LAUNCH = 'crt_launch.c'

def scons():
    """scons function"""
    Import('env', 'prereqs', 'cart_lib', 'gurt_lib')

    tenv = env.Clone()

    libs = ['cart', 'gurt', 'pthread', 'm']
    if not GetOption('help') and not GetOption('clean'):
        mpi = daos_build.configure_mpi(tenv, libs)
        if mpi is None:
            print("\nSkipping compilation for tests that need MPI")
            print("Install and load mpich or openmpi\n")
            return

    tenv.AppendUnique(CPPPATH=['#/src/cart'])
    tenv.AppendUnique(LIBS=libs)
    prereqs.require(tenv, 'mercury')
    tenv.AppendUnique(LIBPATH=['#/src/cart'])
    tenv.AppendUnique(FLAGS='-pthread')

    crt_launch = daos_build.program(tenv, CRT_LAUNCH)

    tenv.Requires(crt_launch, [cart_lib, gurt_lib])
    tenv.Install(os.path.join("$PREFIX", 'bin'), crt_launch)

if __name__ == "SCons.Script":
    scons()
