#!python

Import('env', 'PREREQS')

libs = ['daos', 'daos_common', 'daos_tier', 'crt', 'crt_util',
	'mpi', 'uuid', 'cmocka']

denv = env.Clone()

if PREREQS is not None:
    PREREQS.require(denv, 'ompi', 'cart')

denv.Program('simple_array', 'simple_array.c', LIBS=libs)
denv.Program('daosbench', 'daosbench.c', LIBS=libs)

# tests
SConscript('suite/SConscript', exports = ['denv'])
