"""Build cart_ctl test"""


SRC = ['cart_ctl.c']


def scons():
    """scons function"""
    Import('env', 'cart_utils_objs')

    tenv = env.Clone(LIBS=[])
    tenv.d_internal_headers()
    tenv.d_internal_headers(src_dir="cart")
    tenv.d_internal_headers(src_dir="cart/utils")
    tenv.AppendUnique(LIBS=['cart', 'gurt', 'pthread', 'daos', 'daos_common'])

    tenv.require('mercury', 'protobufc')

    ctl = tenv.d_program([SRC, cart_utils_objs])
    tenv.Install('$PREFIX/bin', ctl)


if __name__ == "SCons.Script":
    scons()
