"""Build cart_ctl test"""


SRC = ['cart_ctl.c']


def scons():
    """scons function"""
    Import('env', 'cart_utils_objs')

    tenv = env.Clone(LIBS=[])
    tenv.AppendUnique(LIBS=['cart', 'gurt', 'pthread', 'daos', 'daos_common'])
    tenv.AppendUnique(CPPPATH=[Dir('../../../src/mgmt').srcnode()])
    tenv.AppendUnique(CPPPATH=[Dir('../../cart').srcnode()])
    tenv.AppendUnique(CPPPATH=[Dir('../../cart/utils').srcnode()])

    tenv.require('mercury', 'protobufc')

    ctl = tenv.d_program([SRC, cart_utils_objs])
    tenv.Install('$PREFIX/bin', ctl)


if __name__ == "SCons.Script":
    scons()
