#!python
"""Build cart src"""


def scons():
    """Scons function"""
    Import('env', 'prereqs')

    env.AppendUnique(LIBPATH=[Dir('.')])

    libraries = ['crt_util', 'mercury', 'abt']

    if prereqs:
        prereqs.require(env, 'mercury', 'pmix', 'argobots')
    else:
        libraries += ['na', 'pmix']

    denv = env.Clone()
    denv.Append(CPPPATH=['#/src/crt'])

    crt = denv.SharedLibrary('libcrt', Glob('*.c'), LIBS=libraries)
    denv.Install('$PREFIX/lib/', crt)

    # Builders
    SConscript('tests/SConscript', exports='denv')

if __name__ == "SCons.Script":
    scons()
