#!python

Import('env', 'PREREQS')

env.AppendUnique(LIBPATH=[Dir('.')])

libraries = ['crt_util', 'mercury', 'abt']

if PREREQS is None:
    libraries += ['na', 'pmix']
else:
    PREREQS.require(env, 'mercury', 'pmix', 'argobots')

denv = env.Clone()
denv.Append(CPPPATH = ['#/src/crt'])

crt = denv.SharedLibrary('libcrt', Glob('*.c'), LIBS=libraries)
denv.Install('$PREFIX/lib/', crt)

# Builders
SConscript('tests/SConscript', exports='denv')
