"""Build Blob I/O tests"""


def scons():
    """Execute build"""
    Import('denv')

    libraries = ['uuid', 'abt', 'bio', 'gurt', 'cmocka', 'daos_common_pmem', 'daos_tests']

    env = denv.Clone()

    env.AppendUnique(LIBPATH=[Dir('..')])
    env.AppendUnique(RPATH_FULL=['$PREFIX/lib64/daos_srv'])
    bio_ut_src = ['bio_ut.c', 'wal_ut.c']
    bio_ut = env.d_test_program('bio_ut', bio_ut_src, LIBS=libraries)
    env.Install('$PREFIX/bin/', bio_ut)


if __name__ == "SCons.Script":
    scons()
