"""Build DAOS server"""
import daos_build

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    denv = env.Clone()

    libraries = ['daos_common', 'gurt', 'cart', 'vos_srv', 'daos', 'daos_tier']
    libraries += ['dl', 'uuid', 'pthread', 'abt']
    libraries += ['hwloc']

    prereqs.require(denv, 'hwloc', 'cart', 'argobots')

    # the "-rdynamic" is to allow other dll to refer symbol defined in
    # daos_server such as dss_tls_key etc.
    denv.AppendUnique(LINKFLAGS=['-rdynamic'])

    # Add runtime paths for daos libraries
    denv.AppendUnique(RPATH=[Literal(r'\$$ORIGIN/../lib/daos_srv')])

    # Generate server program
    server = daos_build.program(denv, 'daos_server', Glob('*.c'),
                                LIBS=libraries)
    denv.Install('$PREFIX/bin', server)

if __name__ == "SCons.Script":
    scons()
