#!python

Import('env', 'PREREQS')

denv = env.Clone()

libraries = ['daos_common', 'crt', 'vos_srv']
libraries += ['dl', 'uuid', 'pthread', 'abt']
libraries += ['hwloc', 'crt']

if PREREQS is not None:
	PREREQS.require(denv, 'hwloc', 'cart', 'argobots')

# the "-rdynamic" is to allow other dll to refer symbol defined in daos_server
# such as dss_tls_key etc.
denv.Append(LINKFLAGS = ['-rdynamic'])

# Generate server program
server = denv.Program('daos_server', Glob('*.c'), LIBS=libraries)
denv.Install('$PREFIX/bin', server)
