# it's a real shame that this step is even needed.  push events have the commit message # in
# ${{ github.event.head_commit.message }} but pull_requests don't.  :-(
name: 'Import Commit Message'
description: 'Import Commit Message'
runs:
  using: "composite"
  steps:
    - name: Import Commit Message
      id: commit_message
      run: echo "text<<EOF" >> $GITHUB_OUTPUT;
            git show -s --format=%B >> $GITHUB_OUTPUT;
            echo "EOF" >> $GITHUB_OUTPUT;
    - name: Import and Dequote Commit Message
      id: dequoted_commit_message
      run: . ci/gha_functions.sh;
            echo "text<<EOF" >> $GITHUB_OUTPUT;
            git show -s --format=%B | escape_single_quotes >> $GITHUB_OUTPUT;
            echo "EOF" >> $GITHUB_OUTPUT;
    - name: Identify Commit Pragmas
      run: . ci/gha_functions.sh;
            echo '${{ steps.dequoted_commit_message.outputs.text }}' | get_commit_pragmas
