"""Build DAOS config"""
import os

def scons():
    """Execute build"""
    Import('env', 'CONF_DIR')

    env.Install(CONF_DIR, ['daos_server.yml', 'daos.yml',
                           'daos_agent.yml'])

if __name__ == "SCons.Script":
    scons()
