"""Build DAOS config"""


def scons():
    """Execute build"""
    Import('env', 'conf_dir', 'prereqs')

    if prereqs.server_requested():
        env.Install(conf_dir, ['daos_server.yml'])
    if prereqs.client_requested():
        env.Install(conf_dir, ['daos_control.yml', 'daos_agent.yml'])


if __name__ == "SCons.Script":
    scons()
