#!python

Import('denv')

libraries = ['daos_common', 'daos', 'daos_tests', 'pouch', 'cart']
libraries += ['daos_tier', 'uuid', 'mpi']
libraries += ['cmocka']

test1 = denv.Program('cross_conn_test', 'cross_conn_test.c', LIBS = libraries)
test2 = denv.Program('tier_populate', 'tier_populate.c', LIBS = libraries)
test3 = denv.Program('fetch_test', ['fetch_test.c', 'parse_info.c'], LIBS = libraries)
denv.Install('$PREFIX/bin/', test1)
denv.Install('$PREFIX/bin/', test2)
denv.Install('$PREFIX/bin/', test3)
