"""Build tier tests"""
import daos_build

def scons():
    """Execute build"""
    Import('denv')

    libraries = ['daos_common', 'daos', 'daos_tests', 'gurt', 'cart']
    libraries += ['daos_tier', 'uuid', 'mpi']
    libraries += ['cmocka']

    test1 = daos_build.program(denv, 'cross_conn_test', 'cross_conn_test.c',
                               LIBS=libraries)
    test2 = daos_build.program(denv, 'tier_populate', 'tier_populate.c',
                               LIBS=libraries)
    test3 = daos_build.program(denv, 'fetch_test',
                               ['fetch_test.c', 'parse_info.c'], LIBS=libraries)
    denv.Install('$PREFIX/bin/', test1)
    denv.Install('$PREFIX/bin/', test2)
    denv.Install('$PREFIX/bin/', test3)

if __name__ == "SCons.Script":
    scons()
