"""Tests that we can build from prebuilt components"""
import sys, os
sys.path.insert(0, "..")
from prereq_tools import PreReqComponent

ENV = DefaultEnvironment()

OPTS = Variables()
PREREQS = PreReqComponent(ENV, OPTS)
PATH = os.path.realpath(os.path.join(Dir('#').abspath, "..",
                                     "components.py"))
PREREQS.preload(PATH)

PREREQS.require(ENV, "pmix", "pthread")
ENV.Program("foo", Glob("*.c"))
Help(OPTS.GenerateHelpText(ENV))
