"""Build rdb tests"""
import daos_build

def scons():
    """Execute build"""
    Import('denv', 'prereqs', 'libdaos_tgts', 'daos_common_pmem_lib')

    tenv = denv.Clone()
    prereqs.require(tenv, 'isal')

    # rdbt server
    librdbt = daos_build.library(tenv, 'rdbt', ['rdb_test.c', 'rpc.c'],
                                 install_off='../..')
    tenv.Install('$PREFIX/lib64/daos_srv', librdbt)

    # rdbt client
    rdbt = daos_build.program(tenv, 'rdbt', ['rdbt.c', 'rpc.c'] + libdaos_tgts,
                              LIBS=['daos_common_pmem', 'cart', 'gurt', 'uuid', 'isal', 'protobuf-c'])
    tenv.Requires(rdbt, [daos_common_pmem_lib])
    tenv.Install('$PREFIX/bin', rdbt)

if __name__ == "SCons.Script":
    scons()
