Import('env')

# rdbt server
librdbt = env.SharedLibrary('rdbt', ['rdb_test.c', 'rpc.c'])
env.Install('$PREFIX/lib/daos_srv', librdbt)

# rdbt client
rdbt = env.Program('rdbt', ['rdbt.c', 'rpc.c'],
		   LIBS=['cart', 'gurt', 'daos_common', 'uuid'])
env.Install('$PREFIX/bin', rdbt)
