"""Build rdb tests"""
def scons():
    """Execute build"""
    Import('denv')

    # rdbt server
    librdbt = denv.SharedLibrary('rdbt', ['rdb_test.c', 'rpc.c'])
    denv.Install('$PREFIX/lib/daos_srv', librdbt)

    # rdbt client
    rdbt = denv.Program('rdbt', ['rdbt.c', 'rpc.c'],
                        LIBS=['cart', 'gurt', 'daos_common', 'uuid'])
    denv.Install('$PREFIX/bin', rdbt)

if __name__ == "SCons.Script":
    scons()
