Import('env')

# raft
SConscript('raft/SConscript', exports = 'env')

# rdb-specific env
env = env.Clone()
env.AppendUnique(CPPPATH = ['#/src/rdb/raft/include'])
env.AppendUnique(LIBPATH = ['raft/src'])

# rdb
rdb = env.SharedLibrary('rdb',
			['rdb_util.c', 'rdb_path.c', 'rdb_layout.c',
			 'rdb_tree.c', 'rdb_rpc.c', 'rdb_raft.c', 'rdb_tx.c',
			 'rdb_module.c'],
			LIBS=['raft'])
env.Install('$PREFIX/lib/daos_srv', rdb)
