# (C) Copyright 2021 Intel Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
"""DAOS metrics utility"""


def scons():
    """Execute build"""
    Import('env')

    denv = env.Clone()

    daos_metrics = denv.d_program('daos_metrics', ['daos_metrics.c'], LIBS=['gurt'])

    denv.Install('$PREFIX/bin', daos_metrics)


if __name__ == "SCons.Script":
    scons()
