# Install dependencies of a development node
# yamllint disable rule:line-length

- name: Install rpms missing development dependencies
  remote_user: root
  dnf:
    state: latest
    update_cache: true
    name:
      - meson
      - rpm-build
      - rpmdevtools
      - createrepo
      - python3-clustershell

- name: Install python development dependencies
  remote_user: root
  pip:
    state: present
    name:
      - "avocado=={{ daos_avocado_version | default(daos_avocado_version_default) }}"
      - "avocado-framework=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
      - "avocado-framework-plugin-glib=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
      - "avocado-framework-plugin-golang=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
      - "avocado-framework-plugin-loader-yaml=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
      - "avocado-framework-plugin-result-html=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
      - "avocado-framework-plugin-result-upload=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
      - "avocado-framework-plugin-varianter-yaml-to-mux=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
