"""Build DAOS I/O server"""
import daos_build

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    denv = env.Clone()

    libraries = ['daos_common', 'gurt', 'cart', 'vos_srv', 'daos']
    libraries += ['bio', 'dl', 'uuid', 'pthread', 'abt']
    libraries += ['hwloc', 'pmemobj', 'yaml', 'protobuf-c']

    prereqs.require(denv, 'hwloc', 'cart', 'argobots')

    # the "-rdynamic" is to allow other dll to refer symbol defined in
    # daos_io_server such as dss_tls_key etc.
    denv.AppendUnique(LINKFLAGS=['-rdynamic'])

    # Add runtime paths for daos libraries
    denv.AppendUnique(RPATH=[Literal(r'\$$ORIGIN/../lib/daos_srv')])

    # Generate I/O server program
    iosrv = daos_build.program(denv, 'daos_io_server', Glob('*.c'),
                               LIBS=libraries)
    denv.Install('$PREFIX/bin', iosrv)

    SConscript('tests/SConscript', exports='denv')

if __name__ == "SCons.Script":
    scons()
