version: 2
updates:
  - package-ecosystem: pip
    directories:
      - /utils/ansible/ftest/
      - /utils/cq/
      - /
    ignore:
      - dependency-name: "avocado-framework*"
    schedule:
      interval: weekly
    groups:
      python-packages:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    target-branch: master
    directory: /
    schedule:
      interval: weekly
    groups:
      gha-versions:
        patterns:
          - "*"
    reviewers:
      - daos-stack/actions-watchers
    commit-message:
      prefix: "Doc-only: true \n"

  - package-ecosystem: github-actions
    target-branch: release/2.6
    directory: /
    schedule:
      interval: weekly
    groups:
      gha-versions:
        patterns:
          - "*"
    reviewers:
      - daos-stack/actions-watchers
    commit-message:
      prefix: "Doc-only: true \n"

  - package-ecosystem: github-actions
    target-branch: release/2.6.4-aurora
    directory: /
    schedule:
      interval: weekly
    groups:
      gha-versions:
        patterns:
          - "*"
    reviewers:
      - daos-stack/actions-watchers
    commit-message:
      prefix: "Doc-only: true \n"

  - package-ecosystem: github-actions
    target-branch: release/2.6.4-mfg
    directory: /
    schedule:
      interval: weekly
    groups:
      gha-versions:
        patterns:
          - "*"
    reviewers:
      - daos-stack/actions-watchers
    commit-message:
      prefix: "Doc-only: true \n"

  - package-ecosystem: gomod
    target-branch: master
    directory: /src/control
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    reviewers:
      - daos-stack/actions-watchers
    commit-message:
      prefix: "Doc-only: true \n"

  - package-ecosystem: gomod
    target-branch: release/2.6
    directory: /src/control
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    reviewers:
      - daos-stack/actions-watchers
    commit-message:
      prefix: "Doc-only: true \n"

  - package-ecosystem: gomod
    target-branch: release/2.6.4-aurora
    directory: /src/control
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    reviewers:
      - daos-stack/actions-watchers
    commit-message:
      prefix: "Doc-only: true \n"

  - package-ecosystem: gomod
    target-branch: release/2.6.4-mfg
    directory: /src/control
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    reviewers:
      - daos-stack/actions-watchers
    commit-message:
      prefix: "Doc-only: true \n"
