"""Build ftest"""
import os

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    ftest_install_dir = '$PREFIX/lib/daos/TESTING/ftest'

    env.Install(ftest_install_dir, Glob('*.*')) 

    dirs = ['container', 'control', 'daos_test', 'data', 'io', \
            'network', 'object', 'pool', 'rebuild', 'security', \
            'server', 'soak', 'unittest']

    for dir in dirs:
        env.Install(os.path.join(ftest_install_dir, dir),
        Glob("%s/*.*" % dir))

    # util
    SConscript('util/SConscript')

if __name__ == "SCons.Script":
    scons()
