"""Build ftest"""
import os

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    ftest_install_dir = '$PREFIX/lib/daos/TESTING/ftest'

    env.Install(ftest_install_dir, Glob('*.*'))

    dirs = ['aggregation', 'checksum', 'container', 'control',
            'daos_test', 'data', 'io', 'network', 'nvme',
            'object', 'osa', 'pool', 'rebuild', 'security',
            'server', 'soak', 'unittest', 'cart/corpc  ',
            'cart/ctl', 'cart/ghost_rank_rpc',
            'cart/group_test', 'cart/iv', 'cart/no_pmix',
            'cart/nopmix_launcher', 'cart/rpc',
            'cart/selftest', 'cart/util']

    for sub_dir in dirs:
        env.Install(os.path.join(ftest_install_dir, sub_dir),
                    Glob("%s/*.*" % sub_dir))

    # util
    SConscript('util/SConscript')

if __name__ == "SCons.Script":
    scons()
