"""Build client tests"""
import daos_build

def scons():
    """Execute build"""
    Import('denv')

    daos_build.program(denv, 'eq_test', Glob('eq_tests.c'),
                       LIBS=['daos', 'daos_common', 'gurt', 'cart',
                             'pthread'])

if __name__ == "SCons.Script":
    scons()
