- name: systemd daemon-reexec
  become: true
  command: systemctl daemon-reexec
  when: ansible_service_mgr == 'systemd'

- name: systemd daemon-reload
  become: true
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'

- name: Update Debian GRUB config
  become: true
  command: update-grub
  listen: Update Debian GRUB config
  when: ansible_os_family == 'Debian'
