#!python

Import('env', 'PREREQS')

env.AppendUnique(LIBPATH=[Dir('.')])
denv = env.Clone()

# dsms: DSM Server Module
dsms = denv.SharedLibrary('cont',
			  ['rpc.c', 'dsms_module.c',
			   'dsms_container.c', 'dsms_target.c'])
denv.Install('$PREFIX/lib/daos_srv', dsms)

# Container client library
dc_co_tgts = denv.SharedObject(['client.c', 'rpc.c'])
Export('dc_co_tgts')

# tests
SConscript('tests/SConscript', exports = ['denv', 'PREREQS'])
