#!python

Import('env', 'PREREQS')

env.AppendUnique(LIBPATH=[Dir('.')])
denv = env.Clone()

# ds_cont: Container Server
ds_cont = denv.SharedLibrary('cont',
			     ['srv.c', 'srv_container.c', 'srv_target.c',
			      'rpc.c'])
denv.Install('$PREFIX/lib/daos_srv', ds_cont)

# dc_cont: Container Client
dc_co_tgts = denv.SharedObject(['cli.c', 'rpc.c'])
Export('dc_co_tgts')

# tests
SConscript('tests/SConscript', exports = ['denv', 'PREREQS'])
