#!python

Import('denv')

libraries = ['libdaos_sr', 'libdaos_common', 'daos_transport']

denv.Program('pseudo_cluster', 'pseudo_cluster.c', LIBS = libraries)
denv.Program('other', 'other.c',  LIBS = libraries)
