"""Build daosctl"""
import daos_build

def scons():
    """Execute build"""

    Import('env', 'prereqs')

    libs = ['daos', 'gurt', 'daos_common', 'uuid',
            'cart', 'pmem', 'pmemobj', 'daos_tests']
    sources = ['daosctl.c', 'help.c', 'common_utils.c', 'test-pool.c',
               'pool-cmds.c', 'cont-cmds.c', 'io-cmds.c']

    denv = env.Clone()

    if not GetOption('help') and not GetOption('clean'):
        mpi = daos_build.configure_mpi(prereqs, denv, libs)
        if mpi is None:
            return

    denv.AppendUnique(CFLAGS=['-std=gnu99'])
    denv.AppendUnique(CPPDEFINES=['TEST'])

    daosctl = denv.Program('daosctl', sources, LIBS=libs)
    env.Install('$PREFIX/bin/', daosctl)

if __name__ == "SCons.Script":
    scons()
