"""Build Per-server Metadata"""

FILES = ['smd_device.c', 'smd_pool.c', 'smd_store.c']

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    denv = env.Clone()
    denv.Append(CPPDEFINES=['-DDAOS_PMEM_BUILD'])
    prereqs.require(denv, 'pmdk', 'argobots', 'protobufc')

    smd_lib = denv.Library('smd', FILES, LIBS=[])
    Export('smd_lib')

    if prereqs.test_requested():
        SConscript('tests/SConscript', exports='denv')

if __name__ == "SCons.Script":
    scons()
