"""Build Per-server Metadata"""
def scons():
    """Execute build"""
    Import('env', 'prereqs')

    env.AppendUnique(LIBPATH=[Dir('.')])

    denv = env.Clone()
    denv.Append(CPPDEFINES=['-DDAOS_PMEM_BUILD'])
    prereqs.require(denv, 'argobots', 'protobufc')

    denv.Library('smd', Glob('*.c'),
                 LIBS=[])

    SConscript('tests/SConscript', exports='denv')

if __name__ == "SCons.Script":
    scons()
