#!python

Import('env', 'PREREQS')

env.AppendUnique(LIBPATH=[Dir('.')])

if PREREQS is not None:
        PREREQS.require(env, 'argobots')

denv = env.Clone()

src = ['debug.c', 'hash.c', 'misc.c']
common = denv.SharedLibrary('libcrt_util', src)
denv.Install('$PREFIX/lib/', common)

denv.Append(CPPPATH = ['#/src/util'])
