#!python

def scons():
    """Scons function"""

    Import('env', 'prereqs')

    env.AppendUnique(LIBPATH=[Dir('.')])

    if prereqs is not None:
            prereqs.require(env, 'argobots')

    denv = env.Clone()

    src = ['debug.c', 'hash.c', 'misc.c']
    common = denv.SharedLibrary('libcrt_util', src)
    denv.Install('$PREFIX/lib/', common)

    denv.Append(CPPPATH = ['#/src/util'])

if __name__ == "SCons.Script":
    scons()
