"""Build chk library"""
import daos_build

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    env.AppendUnique(LIBPATH=[Dir('.')])

    denv = env.Clone()

    # common
    prereqs.require(denv, 'argobots', 'protobufc')
    chk_pb = denv.SharedObject(['chk.pb-c.c'])
    Export('chk_pb')

    if not prereqs.server_requested():
        return

    # chk
    chk = daos_build.library(denv, 'chk',
                             [chk_pb, 'chk_srv.c', 'chk_common.c'],
                             install_off="../..")
    denv.Install('$PREFIX/lib64/daos_srv', chk)

if __name__ == "SCons.Script":
    scons()
