name: 'Provision Cluster'
description: 'Provision Cluster'
inputs:
  condition:
    description: Condition this should run on
    required: true
  ref:
    description: Ref for code checkout
    default: "${{ github.event.pull_request.head.sha }}"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Request and Provision a Cluster
      if: ${{ inputs.condition }}
      shell: bash
      run: |
          . ci/gha_functions.sh
          STAGE_NAME='${{ env.STAGE_NAME }}'
          if "${{ github.event.schedule }}"; then
            REQID='${{ github.run_id }}-${{ github.run_number }}'
          else
            REQID='${{ github.event.pull_request.number }}-${{ github.run_number }}'
          fi
          CP_PRIORITY=${{ env.CP_PRIORITY }}
          echo "::group::Provisioning"
          if ! JENKINS_URL='${{ env.JENKINS_URL }}'                   \
               LABEL='${{ env.LABEL }}'                               \
               PRIORITY=${CP_PRIORITY:-3}                             \
               COVFN_DISABLED=${COVFN_DISABLED}                       \
               provision_cluster "$STAGE_NAME" "${{ github.run_id }}" \
                                 "${{ runner.name }}"                 \
                                 "$REQID-${STAGE_NAME// /_}"; then
               echo "::endgroup::"
               echo "Failed to provision cluster"
               exit 1
          fi
          echo "::endgroup::"
    - name: Wait for nodes to be ready
      if: ${{ inputs.condition }}
      shell: bash
      run: . ci/gha_functions.sh;
           set -eux;
           echo "::group::Waiting for nodes to be ready";
           wait_nodes_ready;
           echo "::endgroup::"
    - name: Post-provision cluster
      if: ${{ inputs.condition }}
      shell: bash
      run: |
        . ci/gha_functions.sh
        set -x
        inst_repos="${{ env.CP_PR_REPOS }} ${{ github.event.inputs.pr-repos }}"
        if [ -n "${{ github.event.inputs.rpm-test-version }}" ]; then
            rpm_test_version="${{ github.event.inputs.rpm-test-version }}"
        elif [ -n "${{ env.CP_RPM_TEST_VERSION }}" ]; then
            rpm_test_version="${{ env.CP_RPM_TEST_VERSION }}"
        fi
        if [ -z "$rpm_test_version" ] &&
           [[ $inst_repos != *daos@* ]]; then
            inst_repos+=" daos@PR-${{ github.event.pull_request.number }}"
            inst_repos+=":${{ github.run_number }}"
        fi
        echo "::group::Post-provision configuration";
        REPO_PATH="$REPO_PATH$GITHUB_RUN_NUMBER/artifact/artifacts/$TARGET"
        ARTIFACTS_URL=$ARTIFACTS_URL                                      \
        INST_REPOS="$(eval echo "$inst_repos")"                           \
        REPO_PATH=$REPO_PATH                                              \
        CI_RPM_TEST_VERSION="$rpm_test_version"                           \
        DAOS_VERSION="$DAOS_VERSION"                                      \
        DISTRO=$PROVISION_DISTRO ci/provisioning/post_provision_config.sh
        echo "::endgroup::"
