#!/usr/bin/python
'''
  (C) Copyright 2019 Intel Corporation.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  GOVERNMENT LICENSE RIGHTS-OPEN SOURCE SOFTWARE
  The Government's rights to use, modify, reproduce, release, perform, display,
  or disclose this software are subject to the terms of the Apache License as
  provided in Contract No. B609815.
  Any reproduction of computer software, computer software documentation, or
  portions thereof marked with this legend must also reproduce the markings.
'''
from __future__ import print_function

import os
import sys
import json
from avocado import Test

sys.path.append('./util')
sys.path.append('../util')
sys.path.append('../../../utils/py')
sys.path.append('./../../utils/py')

import AgentUtils
import server_utils
import write_host_file
from daos_api import DaosContext, DaosPool, DaosContainer

class Dfuse(Test):
    """
    Runs Dfuse test.
    """

    def __init__(self, *args, **kwargs):

        super(Dfuse, self).__init__(*args, **kwargs)

        self.hostlist_servers = None
        self.hostlist_clients = None
        self.agent_sessions = None

    def setUp(self):

        # get paths from the build_vars generated by build
        with open('../../../.build_vars.json') as build_file:
            build_paths = json.load(build_file)
        basepath = os.path.normpath(os.path.join(build_paths['PREFIX'], '..'))

        server_group = self.params.get("server_group", '/server/',
                                       'daos_server')

        self.hostlist_servers = self.params.get("test_servers", '/run/hosts/')
        hostfile_servers = (
            write_host_file.write_host_file(self.hostlist_servers,
                                            self.workdir))
        print("Host file servers is: {}".format(hostfile_servers))

        self.hostlist_clients = self.params.get("test_clients", '/run/hosts/')

        # start server
        self.agent_sessions = AgentUtils.run_agent(basepath,
                                                   self.hostlist_servers,
                                                   self.hostlist_clients)
        server_utils.run_server(hostfile_servers, server_group, basepath)

    def tearDown(self):
        if self.agent_sessions:
            AgentUtils.stop_agent(self.hostlist_clients, self.agent_sessions)
        server_utils.stop_server(hosts=self.hostlist_servers)

    def test_dfuse(self):
        """Try and run something over fuse

        :avocado: tags=vm,regression
        """

        # setup the DAOS python API
        context = DaosContext(build_paths['PREFIX'] + '/lib/')

        createmode = self.params.get("mode", '/run/poolparams/')
        createuid = os.geteuid()
        creategid = os.getegid()
        createsetid = self.params.get("setname", '/run/poolparams/')
        createsize = self.params.get("size", '/run/poolparams/')

        # setup the pool
        pool = DaosPool(context)
        pool.create(createmode, createuid, creategid,
                    createsize, createsetid)
        pool.connect(1 << 1)

        container = DaosContainer(context)
        container.create(pool.handle)

        self.fail("Well, here we are")

    def test_dfuse_optimist(self):
        """Try and run something over fuse"""
        pass
