#!python

Import('env', 'PREREQS')

env.AppendUnique(LIBPATH=[Dir('.')])
denv = env.Clone()

# dsms: DSM Server Module
dsms = denv.SharedLibrary('pool',
			  ['rpc.c', 'dsms_module.c', 'dsms_storage.c',
			   'dsms_pool.c', 'dsms_target.c'])
denv.Install('$PREFIX/lib/daos_srv', dsms)

# dc_pool: Pool Client
dc_pool_tgts = denv.SharedObject(['client.c', 'rpc.c'])
Export('dc_pool_tgts')

# tests
SConscript('tests/SConscript', exports = ['denv', 'PREREQS'])
