"""Build DAOS Addons"""

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    denv = env.Clone()

    denv.AppendUnique(LIBPATH=[Dir('.')])
    prereqs.require(denv, 'ompi')

    addons_tgts = denv.SharedObject(['dac_array.c', 'dac_hl.c'])
    addons_tgts += denv.SharedObject(['daos_array.c', 'daos_hl.c'])
    Export('addons_tgts')

if __name__ == "SCons.Script":
    scons()
