#!python

Import('env')

env.AppendUnique(LIBPATH=[Dir('.')])
denv = env.Clone()

# generate server module
ct_srv = denv.SharedLibrary('tier',
			    ['rpc.c', 'srv.c','srv_ping.c',
			     'srv_enum.c', 'srv_fetch.c'])

denv.Install('$PREFIX/lib/daos_srv', ct_srv)

# generate client library
ct_client = denv.SharedLibrary('daos_tier',
			       ['rpc.c', 'cli.c', 'cli_ping.c',
			        'cli_container.c', 'cli_object.c',
				'cli_stager.c'])
denv.Install('$PREFIX/lib/', ct_client)

# tests
SConscript('tests/SConscript', exports = 'denv')
