"""Build tier modules"""
import daos_build

def scons():
    """Execute build"""
    Import('env')

    env.AppendUnique(LIBPATH=[Dir('.')])
    denv = env.Clone()

    common = denv.SharedObject(['rpc.c'])
    # generate server module
    ct_srv = daos_build.library(denv, 'tier',
                                [common, 'srv.c', 'srv_ping.c', 'srv_util.c',
                                 'srv_enum.c', 'srv_fetch.c', 'srv_tmgmt.c'])

    denv.Install('$PREFIX/lib/daos_srv', ct_srv)

    # generate client library
    dc_tier_tgts = denv.SharedObject(['cli.c', 'cli_ping.c',
                                      'cli_util.c', 'cli_container.c',
                                      'cli_object.c', 'cli_stager.c',
                                      'cli_tmgmt.c']) + common
    Export('dc_tier_tgts')

if __name__ == "SCons.Script":
    scons()
