"""Build daos mgmt tests"""


def scons():
    """Execute build"""
    Import('denv', 'pb_objs')

    tenv = denv.Clone()

    mocks = tenv.Object("mocks.c")

    tenv.Append(CPPDEFINES={'DRPC_TEST': '1'})
    # Isolated unit tests
    tenv.d_test_program('srv_drpc_tests',
                        source=[pb_objs, mocks, 'srv_drpc_tests.c', '../srv_drpc.c'],
                        LIBS=['cmocka', 'protobuf-c', 'daos_common_pmem', 'gurt', 'uuid'])


if __name__ == "SCons.Script":
    scons()
