"""Build daos mgmt tests"""
import daos_build

def scons():
    """Execute build"""
    Import('denv', 'prereqs', 'pb', 'daos_common_pmem_lib')

    prereqs.require(denv, 'protobufc')

    mocks = denv.Object("mocks.c")

    denv.Append(CPPDEFINES={'DRPC_TEST' : '1'})
    # Isolated unit tests
    test = daos_build.test(denv, 'srv_drpc_tests',
                           source=[pb, mocks, 'srv_drpc_tests.c', '../srv_drpc.c'],
                           LIBS=['cmocka', 'protobuf-c', 'daos_common_pmem', 'gurt', 'uuid'])
    denv.Requires(test, [daos_common_pmem_lib])

if __name__ == "SCons.Script":
    scons()
