"""Build versioned extent allocator tests"""


def scons():
    """Execute build"""
    Import('denv', 'gurt_lib')

    libs = gurt_lib + ['smd', 'pmemobj', 'cmocka', 'daos_common_pmem', 'uuid', 'abt']
    denv.Install('$PREFIX/bin/', denv.d_test_program('smd_ut.c', LIBS=libs))


if __name__ == "SCons.Script":
    scons()
