// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drpc_test.proto

package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Module int32

const (
	Module_HELLO Module = 0
)

var Module_name = map[int32]string{
	0: "HELLO",
}
var Module_value = map[string]int32{
	"HELLO": 0,
}

func (x Module) String() string {
	return proto.EnumName(Module_name, int32(x))
}
func (Module) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_drpc_test_525278b76c188682, []int{0}
}

type Function int32

const (
	Function_GREETING Function = 0
)

var Function_name = map[int32]string{
	0: "GREETING",
}
var Function_value = map[string]int32{
	"GREETING": 0,
}

func (x Function) String() string {
	return proto.EnumName(Function_name, int32(x))
}
func (Function) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_drpc_test_525278b76c188682, []int{1}
}

// *
// Hello is the message to request a greeting from the server
//
// name is the name of the user being greeted
type Hello struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_drpc_test_525278b76c188682, []int{0}
}
func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (dst *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(dst, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// *
// HeloResponse is the greeting returned from the server.
//
// greeting is greeting message for the user.
type HelloResponse struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_drpc_test_525278b76c188682, []int{1}
}
func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (dst *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(dst, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*Hello)(nil), "hello.Hello")
	proto.RegisterType((*HelloResponse)(nil), "hello.HelloResponse")
	proto.RegisterEnum("hello.Module", Module_name, Module_value)
	proto.RegisterEnum("hello.Function", Function_name, Function_value)
}

func init() { proto.RegisterFile("drpc_test.proto", fileDescriptor_drpc_test_525278b76c188682) }

var fileDescriptor_drpc_test_525278b76c188682 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x29, 0x2a, 0x48,
	0x8e, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0x48, 0xcd,
	0xc9, 0xc9, 0x57, 0x92, 0xe6, 0x62, 0xf5, 0x00, 0x31, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73,
	0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x6d, 0x2e, 0x5e, 0xb0, 0x64,
	0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x14, 0x17, 0x47, 0x7a, 0x51, 0x6a, 0x6a,
	0x49, 0x66, 0x5e, 0x3a, 0x54, 0x21, 0x9c, 0xaf, 0x25, 0xcc, 0xc5, 0xe6, 0x9b, 0x9f, 0x52, 0x9a,
	0x93, 0x2a, 0xc4, 0xc9, 0xc5, 0xea, 0xe1, 0xea, 0xe3, 0xe3, 0x2f, 0xc0, 0xa0, 0x25, 0xc1, 0xc5,
	0xe1, 0x56, 0x9a, 0x97, 0x5c, 0x92, 0x99, 0x9f, 0x27, 0xc4, 0xc3, 0xc5, 0xe1, 0x1e, 0xe4, 0xea,
	0x1a, 0xe2, 0xe9, 0xe7, 0x2e, 0xc0, 0x90, 0xc4, 0x06, 0x76, 0x86, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x0b, 0x9e, 0xb7, 0x3d, 0x99, 0x00, 0x00, 0x00,
}
