"""Build daos security tests"""
import daos_build

def scons():
    """Execute build"""
    Import('denv', 'dc_security_tgts')

    # Isolated unit tests
    daos_build.test(denv, 'cli_security_tests',
                    source=['cli_security_tests.c', dc_security_tgts],
                    LIBS=['cmocka', 'protobuf-c', 'daos_common', 'gurt'])
    daos_build.test(denv, 'acl_api_tests',
                    source=['acl_api_tests.c', '../acl_api.c'],
                    LIBS=['cmocka', 'protobuf-c', 'daos_common', 'gurt'])

if __name__ == "SCons.Script":
    scons()
