"""Build daos security tests"""
#
# (C) Copyright 2026 Hewlett Packard Enterprise Development LP
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#


def scons():
    """Execute build"""
    Import('denv', 'dc_security_tgts', 'acl_tgts')

    mocks = denv.Object('drpc_mocks.c')
    util = denv.Object('sec_test_util.c')
    # Isolated unit tests
    denv.d_test_program('cli_security_tests',
                        source=['cli_security_tests.c', util, dc_security_tgts, mocks],
                        LIBS=['cmocka', 'protobuf-c', 'daos_common', 'gurt', 'uuid'])

    denv.d_test_program('srv_acl_tests',
                        source=['srv_acl_tests.c', util, acl_tgts, mocks],
                        LIBS=['cmocka', 'protobuf-c', 'daos_common', 'gurt', 'uuid'])


if __name__ == "SCons.Script":
    scons()
