# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy a containerized DAOS system

version: "3.8"

services:

  daos_admin:
    image: "daos-admin:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-admin/el8"
      args:
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "DAOS_VERSION=${DAOS_VERSION}"
    tty: true
    secrets:
      - source: daos_admin-certs
        target: daos_admin-certs.txz

secrets:
  daos_admin-certs:
    file: "${DAOS_ADMIN_CERTS_TXZ}"
