# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy a containerized DAOS system

version: "3.8"

services:

  daos_server:
    image: "${DAOS_DOCKER_IMAGE_NSP}/daos-server-${LINUX_DISTRO}:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-server/${LINUX_DISTRO}"
      args:
        - "LINUX_DISTRO=${LINUX_DISTRO}"
        - "DAOS_DOCKER_IMAGE_NSP=${DAOS_DOCKER_IMAGE_NSP}"
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "DAOS_VERSION=${DAOS_VERSION}"
    # XXX Seems to not be possible to use uio without privileged mode
    # https://github.com/moby/moby/issues/22825
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 1048576
    network_mode: host
    volumes:
      - type: bind
        read_only: false
        source: /sys/devices/system/node
        target: /sys/devices/system/node
      - type: bind
        read_only: false
        source: /lib/modules
        target: /lib/modules
      - type: bind
        read_only: false
        source: /dev/hugepages
        target: /dev/hugepages
    secrets:
      - source: daos_server-certs
        target: daos_server-certs.txz

secrets:
  daos_server-certs:
    file: "${DAOS_SERVER_CERTS_TXZ}"
