# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to deploy a DAOS client service with Docker stack

version: "3.8"

services:
  daos_client_gt:
    image: "${DAOS_DOCKER_IMAGE_NSP}/daos-client_gt-${LINUX_DISTRO}:${DAOS_DOCKER_IMAGE_TAG}"
    tty: true
    networks:
      - docker_host
    secrets:
      - source: daos_agent-certs
        target: daos_agent-certs.txz
        uid: '0'
        gid: '0'
        mode: 0600

secrets:
  daos_agent-certs:
    external: true

networks:
  docker_host:
    name: "host"
    external: true
