# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy a containerized DAOS system

version: "3.8"

services:

  daos_client_gt:
    image: "${DAOS_DOCKER_IMAGE_NSP}/daos-client_gt-${LINUX_DISTRO}:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-client_agent/${LINUX_DISTRO}"
      args:
        - "LINUX_DISTRO=${LINUX_DISTRO}"
        - "DAOS_DOCKER_IMAGE_NSP=${DAOS_DOCKER_IMAGE_NSP}"
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "DAOS_VERSION=${DAOS_VERSION}"
        - "DAOS_CLIENT_UNAME=${DAOS_CLIENT_UNAME}"
        - "DAOS_CLIENT_GNAME=${DAOS_CLIENT_GNAME}"
    tty: true
    network_mode: host
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    secrets:
      - source: daos_agent-certs
        target: daos_agent-certs.txz

secrets:
  daos_agent-certs:
    file: "${DAOS_AGENT_CERTS_TXZ}"
