# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy a containerized DAOS system

version: "3.8"

services:

  daos_server:
    image: "daos-server:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-server/el8"
      args:
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "DAOS_VERSION=${DAOS_VERSION}"
        - "DAOS_CLIENT_UNAME=${DAOS_CLIENT_UNAME}"
        - "DAOS_CLIENT_UID=${DAOS_CLIENT_UID}"
        - "DAOS_CLIENT_GNAME=${DAOS_CLIENT_GNAME}"
        - "DAOS_CLIENT_GID=${DAOS_CLIENT_GID}"
    # XXX Seems to not be possible to use uio without privileged mode
    # https://github.com/moby/moby/issues/22825
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 1048576
    network_mode: host
    volumes:
      - type: bind
        read_only: false
        source: /sys/devices/system/node
        target: /sys/devices/system/node
      - type: bind
        read_only: false
        source: /lib/modules
        target: /lib/modules
      - type: bind
        read_only: false
        source: /dev/hugepages
        target: /dev/hugepages
    secrets:
      - source: daos_server-certs
        target: daos_server-certs.txz

secrets:
  daos_server-certs:
    file: "${DAOS_SERVER_CERTS_TXZ}"
