# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy a containerized DAOS system

version: "3.8"

services:

  daos_agent:
    image: "${DAOS_DOCKER_IMAGE_NSP}/daos-agent-${LINUX_DISTRO}:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-agent/${LINUX_DISTRO}"
      args:
        - "LINUX_DISTRO=${LINUX_DISTRO}"
        - "DAOS_DOCKER_IMAGE_NSP=${DAOS_DOCKER_IMAGE_NSP}"
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "DAOS_VERSION=${DAOS_VERSION}"
    network_mode: host
    pid: host
    volumes:
      - type: volume
        source: daos_agent-socket
        target: /var/run/daos_agent
        volume:
          nocopy: true
    secrets:
      - source: daos_agent-certs
        target: daos_agent-certs.txz

  daos_client_sa:
    image: "${DAOS_DOCKER_IMAGE_NSP}/daos-client_sa-${LINUX_DISTRO}:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-client/${LINUX_DISTRO}"
      args:
        - "LINUX_DISTRO=${LINUX_DISTRO}"
        - "DAOS_DOCKER_IMAGE_NSP=${DAOS_DOCKER_IMAGE_NSP}"
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "DAOS_VERSION=${DAOS_VERSION}"
    tty: true
    network_mode: host
    pid: host
    cap_add:
      - SYS_ADMIN
    user: "${DAOS_CLIENT_UID}:${DAOS_CLIENT_GID}"
    volumes:
      - type: volume
        source: daos_agent-socket
        target: /var/run/daos_agent
        volume:
          nocopy: true
    devices:
      - "/dev/fuse:/dev/fuse"
    depends_on:
      - daos_agent

volumes:
  daos_agent-socket:

secrets:
  daos_agent-certs:
    file: "${DAOS_AGENT_CERTS_TXZ}"
