# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy a containerized DAOS system

version: "3.8"

services:

  daos_admin:
    image: "${DAOS_DOCKER_IMAGE_NSP}/daos-admin-${LINUX_DISTRO}:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-admin/${LINUX_DISTRO}"
      args:
        - "LINUX_DISTRO=${LINUX_DISTRO}"
        - "DAOS_DOCKER_IMAGE_NSP=${DAOS_DOCKER_IMAGE_NSP}"
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "DAOS_VERSION=${DAOS_VERSION}"
    tty: true
    secrets:
      - source: daos_admin-certs
        target: daos_admin-certs.txz

secrets:
  daos_admin-certs:
    file: "${DAOS_ADMIN_CERTS_TXZ}"
