# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy a containerized DAOS system

version: "3.8"

services:

  daos_base:
    image: "${DAOS_DOCKER_IMAGE_NSP}/daos-base-${LINUX_DISTRO}:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-base/${LINUX_DISTRO}"
      args:
        - "DAOS_CLIENT_UNAME=${DAOS_CLIENT_UNAME}"
        - "DAOS_CLIENT_UID=${DAOS_CLIENT_UID}"
        - "DAOS_CLIENT_GNAME=${DAOS_CLIENT_GNAME}"
        - "DAOS_CLIENT_GID=${DAOS_CLIENT_GID}"
        - "BUST_CACHE=${BUST_CACHE}"
        - "LINUX_IMAGE_NAME=${LINUX_IMAGE_NAME}"
        - "LINUX_IMAGE_TAG=${LINUX_IMAGE_TAG}"
        - "DAOS_REPOS=${DAOS_REPOS}"
        - "DAOS_GPG_KEYS=${DAOS_GPG_KEYS}"
        - "DAOS_REPOS_NOAUTH=${DAOS_REPOS_NOAUTH}"
        - "DAOS_VERSION=${DAOS_VERSION}"
    tty: true
