# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy a containerized DAOS system

version: "3.8"

services:

  daos_spdk_setup:
    image: "${DAOS_DOCKER_IMAGE_NSP}/daos-spdk_setup-${LINUX_DISTRO}:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-spdk_setup/${LINUX_DISTRO}"
      args:
        - "LINUX_DISTRO=${LINUX_DISTRO}"
        - "DAOS_DOCKER_IMAGE_NSP=${DAOS_DOCKER_IMAGE_NSP}"
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "DAOS_VERSION=${DAOS_VERSION}"
    # XXX Seems to not be possible to use uio without privileged mode
    # https://github.com/moby/moby/issues/22825
    privileged: true
    network_mode: none
    volumes:
      - type: bind
        read_only: false
        source: /lib/modules
        target: /lib/modules
      - type: bind
        read_only: false
        source: /dev/hugepages
        target: /dev/hugepages
