"""Build blob I/O"""
import os
import daos_build

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    env.AppendUnique(LIBPATH=[Dir('.')])

    denv = env.Clone()
    prereqs.require(denv, 'pmdk', 'spdk', 'argobots', 'protobufc', 'hwloc')

    SConscript('smd/SConscript')
    denv.AppendUnique(LIBPATH=['smd'])

    bio = daos_build.library(denv, "bio", Glob('*.c'),
                             LIBS=['numa', 'spdk', 'smd'])
    denv.Install('$PREFIX/lib64/daos_srv', bio)

if __name__ == "SCons.Script":
    scons()
