"""Build dav_v2 libraries"""


SRC = ['alloc_class.c', 'bucket.c', 'container_ravl.c', 'container_seglists.c', 'critnib.c',
       'dav_clogs.c', 'dav_iface.c', 'heap.c', 'memblock.c', 'memops.c', 'meta_io.c',
       'palloc.c', 'ravl.c', 'ravl_interval.c', 'recycler.c', 'stats.c', 'tx.c', 'ulog.c',
       'util.c', 'wal_tx.c']


def scons():
    """Scons function"""

    Import('env', 'base_env')

    env.AppendUnique(LIBPATH=[Dir('.')])
    base_env.AppendUnique(LIBPATH=[Dir('.')])
    base_env.d_add_build_rpath()
    env.d_add_build_rpath()

    denv = env.Clone()

    denv.AppendUnique(LIBS=['pthread', 'gurt'])
    denv.Append(CPPDEFINES=['-DDAOS_PMEM_BUILD', '-DDAV_V2_BUILD'])
    denv.AppendUnique(CFLAGS=['-fvisibility=hidden'])

    dav_v2 = denv.d_library('dav_v2', SRC)
    denv.Install('$PREFIX/lib64/', dav_v2)


if __name__ == "SCons.Script":
    scons()
