# Install dependencies of an admin/client node

- name: Install rpms DAOS client dependencies
  remote_user: root
  dnf:
    state: latest
    update_cache: true
    name: "{{ daos_base_deps.rpms + daos_client_deps.rpms }}"
