# Install dependencies of a server node

- name: Install rpms DAOS server dependencies
  remote_user: root
  dnf:
    state: latest
    update_cache: true
    name: "{{ daos_base_deps.rpms + daos_server_deps.rpms }}"
