#!python
# (C) Copyright 2021 Intel Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
"""Build crt_utils component"""

import daos_build

LIB_SRC = ['crt_utils.c']


####################################
# Create cart utility share objects
####################################
def build_utility_shared_obj(env):
    """Build cart utility library"""
    cart_utils_objs = env.SharedObject(LIB_SRC, SHOBJPREFIX='s_')
    Export('cart_utils_objs')


def scons():
    """Scons function"""

    Import('env', 'prereqs')

    prereqs.require(env, 'protobufc')

    daos_build.add_build_rpath(env)

    # Generate cart utility shared objects
    build_utility_shared_obj(env)


if __name__ == "SCons.Script":
    scons()
