"""Build client tests"""


def scons():
    """Execute build"""
    Import('denv')
    denv.require('isal_crypto')

    eq_tests = denv.d_test_program('eq_tests', 'eq_tests.c',
                                   LIBS=['daos', 'daos_common', 'gurt', 'cart',
                                         'pthread', 'cmocka'])
    agent_tests = denv.d_test_program('agent_tests', 'agent_tests.c',
                                      LIBS=['daos', 'daos_common', 'gurt', 'cart',
                                            'pthread', 'cmocka'])
    job_tests = denv.d_test_program('job_tests', 'job_tests.c',
                                    LIBS=['daos', 'daos_common', 'gurt', 'cart',
                                          'pthread', 'cmocka'])

    denv.Install('$PREFIX/bin/', [eq_tests, agent_tests, job_tests])


if __name__ == "SCons.Script":
    scons()
