"""Build test suite"""
import daos_build

def scons():
    """Execute build"""
    Import('denv')

    libraries = ['daos_common', 'daos', 'daos_tests', 'gurt', 'cart']
    libraries += ['uuid', 'mpi']
    libraries += ['cmocka']

    test = daos_build.program(denv, 'daos_test', Glob('*.c'), LIBS=libraries)
    denv.Install('$PREFIX/bin/', test)

if __name__ == "SCons.Script":
    scons()
