"""Build versioned extent allocator"""


FILES = ['vea_alloc.c', 'vea_api.c', 'vea_free.c', 'vea_hint.c', 'vea_init.c', 'vea_util.c']

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    env.AppendUnique(LIBPATH=[Dir('.')])

    if not prereqs.server_requested():
        return

    denv = env.Clone()
    prereqs.require(denv, 'pmdk')

    denv.Append(CPPDEFINES=['-DDAOS_PMEM_BUILD'])
    denv.Library('vea', FILES, LIBS=['daos_common_pmem', 'gurt'])

    if prereqs.test_requested():
        SConscript('tests/SConscript', exports='denv')


if __name__ == "SCons.Script":
    scons()
