"""Build versioned extent allocator"""

FILES = ['vea_alloc.c', 'vea_api.c', 'vea_free.c', 'vea_hint.c', 'vea_init.c', 'vea_util.c']


def scons():
    """Execute build"""
    Import('env')

    env.AppendUnique(LIBPATH=[Dir('.')])

    if not env.d_server_requested():
        return

    denv = env.Clone()
    denv.d_add_requires('pmdk')

    denv.Append(CPPDEFINES=['-DDAOS_PMEM_BUILD'])
    denv.d_static_library('vea', FILES, LIBS=['daos_common_pmem'])

    if env.d_tests_requested():
        SConscript('tests/SConscript', exports='denv')


if __name__ == "SCons.Script":
    scons()
