# Ansible scripts for configuring a DAOS node with ftest
# yamllint disable rule:line-length

- name: Checking required variables
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  loop:
    - daos_launch_username

- name: Gather distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ playbook_dir }}/vars/{{ ansible_distribution | replace(' ', '_') }}{{ ansible_distribution_major_version }}.yml"

- name: Set includedir in sudoers
  become: true
  lineinfile:
    state: present
    create: false
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    validate: /usr/sbin/visudo -cf %s

- name: "Add user {{ ansible_user_id }} to sudo"
  become: true
  lineinfile:
    state: present
    create: true
    owner: root
    group: root
    path: "/etc/sudoers.d/{{ ansible_user_id }}"
    line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL"
    mode: 0440
    validate: /usr/sbin/visudo -cf %s

- name: Create MPI module directory
  become: true
  file:
    path: /etc/modulefiles/mpi
    state: directory
    owner: root
    group: root
    mode: '0755'
    recurse: true

- name: Copy bash script enable-coredumps.sh
  become: true
  copy:
    src: file/enable-coredumps.sh
    dest: /root/enable-coredumps.sh
    owner: root
    group: root
    mode: '0600'

- name: Enable CORE dump
  become: true
  command: /bin/bash /root/enable-coredumps.sh

- name: Copy bash script configure-nofile.sh
  become: true
  copy:
    src: file/configure-nofile.sh
    dest: /root/configure-nofile.sh
    owner: root
    group: root
    mode: '0600'

- name: Configure Number of Open Files
  become: true
  command: /bin/bash /root/configure-nofile.sh

- name: Copy bash script configure-passwd.sh
  become: true
  copy:
    src: file/configure-passwd.sh
    dest: /root/configure-passwd.sh
    owner: root
    group: root
    mode: '0600'

- name: Configure /etc/passwd
  become: true
  command: "/bin/bash /root/configure-passwd.sh {{ daos_launch_username }}"

- name: Add EPEL release
  become: true
  dnf:
    name: epel-release
    state: present

- name: Add DAOS repository
  become: true
  yum_repository:
    name: daos-packages
    description: DAOS v2.6.1 Packages Packages
    baseurl: https://packages.daos.io/v2.6.1/EL8/packages/x86_64
    enabled: true
    gpgcheck: true
    protect: true
    gpgkey: https://packages.daos.io/RPM-GPG-KEY-2023
    state: present
