{
 "title": "DAOS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Ranks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(engine_rank)" }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (rank) (ceil(rate(engine_events_dead_ranks[15s])))",
     "legendFormat": "Rank died"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (instance, rank, pool, target) (rate(engine_pool_xferred_fetch[15s]))",
     "legendFormat": "Fetch"
    },
    {
     "expr": "sum without (instance, rank, pool, target) (rate(engine_pool_xferred_update[15s]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum without (instance, rank, pool, target) (rate(engine_pool_xferred_fetch[15s]) + rate(engine_pool_xferred_update[15s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "I/O Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum without (instance, rank, pool, target) (rate(engine_pool_ops_fetch[1m]))",
     "legendFormat": "Fetch"
    },
    {
     "expr": "sum without (instance, rank, pool, target) (rate(engine_pool_ops_update[1m]))",
     "legendFormat": "Update"
    }
   ]
  },
  {
   "title": "Average Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg without (instance, rank, target) (engine_io_latency_fetch_mean)",
     "legendFormat": "{{size}}"
    }
   ]
  },
  {
   "title": "Average Update Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg without (instance, rank, target) (engine_io_latency_update_mean)",
     "legendFormat": "{{size}}"
    }
   ]
  },
  { "title": "Pools and Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Open Pool Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum without (instance, rank, pool) (engine_pool_ops_pool_connect) - sum without (instance, rank, pool) (engine_pool_ops_pool_disconnect)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Open Container Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum without (instance, rank, job, pool) (engine_pool_ops_cont_open) - sum without (instance, rank, job, pool) (engine_pool_ops_cont_close)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Container Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum without (instance, rank, pool) (rate(engine_pool_ops_cont_open[15s]))",
     "legendFormat": "Open"
    },
    {
     "expr": "sum without (instance, rank, pool) (rate(engine_pool_ops_cont_close[15s]))",
     "legendFormat": "Close"
    },
    {
     "expr": "sum without (instance, rank, pool) (rate(engine_pool_ops_cont_destroy[15s]))",
     "legendFormat": "Destroy"
    }
   ]
  }
 ]
}