#!python

Import('env')

env.AppendUnique(LIBPATH=[Dir('.')])

denv = env.Clone()

# Compiler options
# denv.Append(CPPPATH = ['#/src/dsr/include'])

src = ['obj_class.c', 'pl_map.c', 'ring_map.c']

# generate server module
srv = denv.SharedLibrary('daos_sr_srv', ['dsrs_module.c', src])
denv.Install('$PREFIX/lib/daos_srv', srv)

# generate client library
client = denv.SharedLibrary('daos_sr',
			    ['dsrc_api.c', 'dsrc_module.c', src])
denv.Install('$PREFIX/lib', client)

# Build tests
SConscript('tests/SConscript', exports='denv')
