"""Build object tests"""
import daos_build

def scons():
    """Execute build"""
    Import('denv', 'common_tgts', 'prereqs')

    denv.AppendUnique(LIBPATH=['../../client/api'])

    denv.AppendUnique(RPATH=[Literal(r'\$$ORIGIN/../lib/daos_srv')])

    test_tgt = denv.SharedObject('place_obj.c')
    pl_test = daos_build.program(denv, 'pl_map', test_tgt + common_tgts,
                                 LIBS=['daos', 'daos_common', 'gurt', 'cart',
                                       'placement', 'uuid', 'pthread', 'isal'])
    denv.Install('$PREFIX/bin/', pl_test)

if __name__ == "SCons.Script":
    scons()
