"""Build tier tests"""

def scons():
    """Execute build"""
    Import('denv')

    #Import('build_program')
    #libraries = ['pthread', 'uuid', 'daos_common', 'daos', 'crt',
    #             'cmocka']
    #build_program(denv, 'dct_test', ['dct_ping_test.c', 'dct_test.c'],
    #              LIBS=[libraries, 'daos_tier'])

if __name__ == "SCons.Script":
    scons()
