#!python

Import('denv')

denv.Append(CPPPATH = ['#/src/tier', '#/src/server'])

libraries = ['pthread', 'uuid']
libraries += ['daos_common', 'daos', 'cart', 'daos_tier']
libraries += ['cmocka']


#denv.Program('dct_test', ['dct_ping_test.c', 'dct_test.c'],
#            LIBS=[libraries, 'daos_tier'])
