# Copyright 2018-2022 Intel Corporation
# All rights reserved.
#
# 'recipe' for Docker to build an environment scan DAOS for malware.
#

# Pull base image
ARG BASE_DISTRO=opensuse/leap:15.3
FROM $BASE_DISTRO
LABEL maintainer="daos@daos.groups.io"

# Intermittent cache-bust.  Used to reduce load on the actual CACHEBUST later.
ARG CB0

# Use local repo server if present
# if a local repo server is present and the distro repo server can not
# be reached, have to bootstrap in an environment to get curl installed
# to then install the pre-built repo file.
ARG REPO_FILE_URL
RUN set -e;                                                      \
    if [ -n "$REPO_FILE_URL" ]; then                             \
        zypper mr --all --disable;                               \
        zypper addrepo                                           \
          "${REPO_FILE_URL%/*/}"/opensuse-proxy/distribution/leap/15.3/repo/oss \
          opensuse_oss_proxy;                                    \
        zypper --non-interactive install curl;                   \
        mkdir -p /etc/zypp/repos.d &&                            \
        cd /etc/zypp/repos.d/ &&                                 \
        curl -k -f -o daos_ci-leap15-artifactory.repo.tmp        \
             "$REPO_FILE_URL"daos_ci-leap15-artifactory.repo &&  \
        for file in *.repo; do                                   \
            true > $file;                                        \
        done;                                                    \
        mv daos_ci-leap15-artifactory.repo{.tmp,};               \
    fi;                                                          \
    zypper --non-interactive --gpg-auto-import-keys install      \
        dnf dnf-plugins-core &&                                  \
    mkdir -p /etc/dnf/repos.d &&                                 \
    cd /etc/zypp/repos.d/ &&                                     \
    for file in *.repo; do                                       \
        sed -e '/type=NONE/d' < $file > /etc/dnf/repos.d/$file;  \
    done;                                                        \
    zypper --non-interactive clean --all;                        \
    dnf config-manager --save --setopt=assumeyes=True;           \
    dnf config-manager --save --setopt=install_weak_deps=False;  \
    if [ -n "$REPO_FILE_URL" ]; then                             \
        cd /etc/dnf/repos.d/ &&                                  \
        mv daos_ci-leap15-artifactory.repo{,.tmp};               \
        for file in *.repo; do                                   \
            true > $file;                                        \
        done;                                                    \
        mv daos_ci-leap15-artifactory.repo{.tmp,};               \
    fi

ARG JENKINS_URL
ARG REPOS
RUN for repo in $REPOS; do                                                                                 \
        branch="master";                                                                                   \
        build_number="lastSuccessfulBuild";                                                                \
        if [[ $repo = *@* ]]; then                                                                         \
            branch="${repo#*@}";                                                                           \
            repo="${repo%@*}";                                                                             \
            if [[ $branch = *:* ]]; then                                                                   \
                build_number="${branch#*:}";                                                               \
                branch="${branch%:*}";                                                                     \
            fi;                                                                                            \
        fi;                                                                                                \
        echo -e "[$repo:$branch:$build_number]\n\
name=$repo:$branch:$build_number\n\
baseurl=${JENKINS_URL}job/daos-stack/job/$repo/job/$branch/$build_number/artifact/artifacts/leap15/\n\
enabled=1\n\
gpgcheck=False\n" >> /etc/dnf/repos.d/$repo:$branch:$build_number.repo;   \
        cat /etc/dnf/repos.d/$repo:$branch:$build_number.repo; \
    done

# Install OS updates and package.  Include basic tools and daos dependencies
COPY ./ci/rpm/install-leap15.sh /tmp/install.sh
RUN chmod +x /tmp/install.sh && dnf upgrade &&          \
    if [ -n "$REPO_FILE_URL" ]; then                    \
        cd /etc/dnf/repos.d/ &&                         \
        mv daos_ci-leap15-artifactory.repo{,.tmp};      \
        for file in *.repo; do                          \
            true > $file;                               \
            done;                                       \
            mv daos_ci-leap15-artifactory.repo{.tmp,};  \
        fi &&                                           \
    /tmp/install.sh && dnf clean all &&                 \
    rm -f /tmp/install.sh
RUN if ! grep MODULEPATH=.*/usr/share/modules /etc/profile.d/lmod.sh; then \
        sed -e '/MODULEPATH=/s/$/:\/usr\/share\/modules/'                  \
               /etc/profile.d/lmod.sh;                                     \
    fi

RUN update-ca-certificates

ARG UID=1000

# Add DAOS users
RUN useradd --no-log-init --uid $UID --user-group --create-home --shell /bin/bash \
            --home /home/daos daos_server
RUN echo "daos_server ALL=(root) NOPASSWD: ALL" >> /etc/sudoers.d/daos_sudo_setup; \
    chmod 0440 /etc/sudoers.d/daos_sudo_setup;                                     \
    visudo -c;                                                                     \
    sudo -l -U daos_server

# force an upgrade to get any newly built RPMs, but only if CACHEBUST is set.
ARG CACHEBUST
RUN [ -z "$CACHEBUST" ] || {                                                                 \
        dnf upgrade                                                                          \
            --exclude=fuse,fuse-libs,fuse-devel,libraft0,raft-devel,mercury,mercury-devel && \
        if [ -n "$REPO_FILE_URL" ]; then                                                     \
            cd /etc/dnf/repos.d/ &&                                                          \
            mv daos_ci-leap15-artifactory.repo{,.tmp};                                       \
            for file in *.repo; do                                                           \
                true > $file;                                                                \
            done;                                                                            \
            mv daos_ci-leap15-artifactory.repo{.tmp,};                                       \
        fi &&                                                                                \
        dnf clean all;                                                                       \
    }

ARG BUILD_URL
COPY ci/rpm/install_maldet.sh /tmp/install_maldet.sh
COPY ci/rpm/distro_info.sh /tmp/distro_info.sh
RUN /tmp/install_maldet.sh
