# Copyright 2018-2022 Intel Corporation
# All rights reserved.
#
# 'recipe' for Docker to build an environment scan DAOS for malware.
#

# Pull base image
FROM centos:centos7
LABEL maintainer="daos@daos.groups.io"

# Intermittent cache-bust.  Used to reduce load on the actual CACHEBUST later.
ARG CB0

# Use local repo server if present
ARG REPO_FILE_URL
RUN set -e;                                                      \
    if [ -n "$REPO_FILE_URL" ]; then                             \
        cd /etc/yum.repos.d/ &&                                  \
        curl -k -f -o daos_ci-centos7-artifactory.repo.tmp       \
             "$REPO_FILE_URL"daos_ci-centos7-artifactory.repo && \
        for file in *.repo; do                                   \
            true > $file;                                        \
        done;                                                    \
        mv daos_ci-centos7-artifactory.repo{.tmp,};              \
    fi;                                                          \
    yum --assumeyes install dnf;                                 \
    yum clean all;                                               \
    dnf --assumeyes --disablerepo \*epel\* install               \
                        epel-release dnf-plugins-core;           \
    dnf config-manager --save --setopt=assumeyes=True;           \
    dnf config-manager --save --setopt=install_weak_deps=False;  \
    if [ -n "$REPO_FILE_URL" ]; then                             \
        dnf --quiet config-manager --disable epel;               \
    fi;                                                          \
    dnf update epel-release;                                     \
    dnf clean all

ARG JENKINS_URL
ARG REPOS
RUN for repo in $REPOS; do                                                \
        branch="master";                                                  \
        build_number="lastSuccessfulBuild";                               \
        if [[ $repo = *@* ]]; then                                        \
            branch="${repo#*@}";                                          \
            repo="${repo%@*}";                                            \
            if [[ $branch = *:* ]]; then                                  \
                build_number="${branch#*:}";                              \
                branch="${branch%:*}";                                    \
            fi;                                                           \
        fi;                                                               \
        echo -e "[$repo:$branch:$build_number]\n\
name=$repo:$branch:$build_number\n\
baseurl=${JENKINS_URL}job/daos-stack/job/$repo/job/$branch/$build_number/artifact/artifacts/centos7/\n\
enabled=1\n\
gpgcheck=False\n" >> /etc/yum.repos.d/$repo:$branch:$build_number.repo;   \
        cat /etc/yum.repos.d/$repo:$branch:$build_number.repo; \
        dnf repolist; \
        dnf --disablerepo=\* --enablerepo=$repo:$branch:$build_number makecache; \
    done

# Install OS updates and package.  Include basic tools and daos dependencies

COPY ./ci/rpm/install-base-centos7.sh /tmp/install.sh
RUN chmod +x /tmp/install.sh && dnf upgrade && /tmp/install.sh && dnf clean all && \
    rm -f /tmp/install.sh

ARG UID=1000

# Add DAOS users
RUN useradd --no-log-init --uid $UID --user-group --create-home --shell /bin/bash \
            --home /home/daos daos_server
RUN echo "daos_server ALL=(root) NOPASSWD: ALL" >> /etc/sudoers.d/daos_sudo_setup; \
    chmod 0440 /etc/sudoers.d/daos_sudo_setup;                                     \
    visudo -c;                                                                     \
    sudo -l -U daos_server

# force an upgrade to get any newly built RPMs, but only if CACHEBUST is set.
ARG CACHEBUST
RUN [ -z "$CACHEBUST" ] || {                                                           \
        dnf upgrade --exclude=spdk,spdk-devel,dpdk-devel,dpdk,mercury-devel,mercury && \
        dnf clean all;                                                                 \
    }

ARG BUILD_URL
COPY ci/rpm/distro_info.sh /tmp/distro_info.sh
COPY ci/rpm/install_maldet.sh /tmp/install_maldet.sh
COPY ci/provisioning/post_provision_config_common_functions.sh \
     /tmp/post_provision_config_common_functions.sh
RUN /tmp/install_maldet.sh
