# Copyright 2018-2022 Intel Corporation
# All rights reserved.
#
# 'recipe' for Docker to build an environment scan DAOS for malware.
#

# Pull base image
ARG BASE_DISTRO=opensuse/leap:15.3
FROM $BASE_DISTRO
# Needed for later use of BASE_DISTRO
ARG BASE_DISTRO
LABEL maintainer="daos@daos.groups.io"

# Intermittent cache-bust.  Used to reduce load on the actual CB1 later.
ARG CB0

ARG REPO_FILE_URL
ARG JENKINS_URL
ARG REPOS
# script to translate lookup distro names to commonly used names
COPY ci/rpm/distro_info.sh /tmp/distro_info.sh
# script to install OS updates basic tools and maldet
COPY ci/rpm/install_maldet.sh /tmp/install.sh
# script to setup local repo if available
COPY ./utils/scripts/repo-helper-leap15.sh /tmp/repo-helper.sh
RUN set -e;                                         \
    chmod +x /tmp/repo-helper.sh /tmp/install.sh && \
    /tmp/repo-helper.sh

# Add DAOS users
ARG UID=1000
COPY ./utils/scripts/daos-server-user-setup.sh /tmp/daos-server-user-setup.sh
RUN set -e;                                    \
    chmod +x /tmp/daos-server-user-setup.sh && \
    /tmp/daos-server-user-setup.sh

# force an upgrade to get any newly built RPMs, but only if CB1 is set.
ARG CB1
RUN [ -z "$CB1" ] || {                                  \
        dnf upgrade &&                                  \
        dnf clean all;                                  \
    }

ARG BUILD_URL
COPY ci/rpm/build_url_repo.sh /tmp/build_url_repo.sh
RUN /tmp/build_url_repo.sh
