"""Build DAOS Certificate Generation"""
import os

def scons():
    """Execute build"""
    Import('env')

    env.Install("$PREFIX/lib64/daos/certgen", ['admin.cnf',
                                               'agent.cnf',
                                               'ca.cnf',
                                               'server.cnf',
                                               'gen_certificates.sh'])

if __name__ == "SCons.Script":
    scons()
