"""Build DAOS Certificate Generation"""


def scons():
    """Execute build"""
    Import('env')

    env.Install("$PREFIX/lib64/daos/certgen", ['admin.cnf',
                                               'agent.cnf',
                                               'server.cnf',
                                               'gen_certificates.sh'])


if __name__ == "SCons.Script":
    scons()
