"""Build crt_launch"""

SRC_FILE = 'daos_dump_errnos.c'


def scons():
    """scons function"""
    Import('env')

    tenv = env.Clone()

    libs = ['gurt', 'pthread', 'm']

    tenv.AppendUnique(LIBS=libs)
    tenv.require('mercury')
    tenv.AppendUnique(FLAGS='-pthread')

    bin_util = tenv.d_program(SRC_FILE, LIBS=libs)

    tenv.Install('$PREFIX/bin', bin_util)


if __name__ == "SCons.Script":
    scons()
