# Ansible scripts for deploying the DAOS functional test platform

- hosts: daos_dev
  vars_files:
    - vars/defaults.yml
  tasks:
    - import_tasks: tasks/daos_dev.yml

- hosts: daos_servers
  vars_files:
    - vars/defaults.yml
  tasks:
    - import_tasks: tasks/daos_servers.yml

- hosts: daos_clients
  vars_files:
    - vars/defaults.yml
  tasks:
    - import_tasks: tasks/daos_clients.yml
