# Copyright (C) 2016-2019 Intel Corporation
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted for any purpose (including commercial purposes)
# provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions, and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions, and the following disclaimer in the
#    documentation and/or materials provided with the distribution.
#
# 3. In addition, redistributions of modified forms of the source or binary
#    code must carry prominent notices stating that the original code was
#    changed and the date of the change.
#
#  4. All publications or advertising materials mentioning features or use of
#     this software are asked, but not required, to acknowledge that it was
#     developed by Intel Corporation and credit the contributors.
#
# 5. Neither the name of Intel Corporation, nor the name of any Contributor
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""Build crt_launch"""
import os
import sys

CRT_LAUNCH = 'crt_launch.c'

def scons():
    """scons function"""

    Import('env', 'prereqs', 'cart_lib', 'gurt_lib')

    tenv = env.Clone()

    if tenv.subst("$MPI_PKG") != "":
        tenv.ParseConfig("pkg-config --cflags --libs $MPI_PKG")
    elif not prereqs.check_component('ompi'):
        sys.stdout.write("No MPI installed...skipping crt_launch build\n")
        return

    tenv.AppendUnique(CPPPATH=['#/src/cart'])
    tenv.AppendUnique(LIBS=['cart', 'gurt', 'pthread', 'm', 'mpi'])
    prereqs.require(tenv, 'mercury', 'ompi')
    tenv.AppendUnique(LIBPATH=['#/src/cart'])
    tenv.AppendUnique(RPATH="$PREFIX/lib")
    tenv.AppendUnique(FLAGS='-pthread')

    crt_launch = tenv.Program(CRT_LAUNCH)

    tenv.Requires(crt_launch, [cart_lib, gurt_lib])
    tenv.Install(os.path.join("$PREFIX", 'bin'), crt_launch)

if __name__ == "SCons.Script":
    scons()
