"""Build DAOS Add owns"""


def scons():
    """Execute build"""
    Import('env', 'libdaos_tgts')

    denv = env.Clone()

    denv.AppendUnique(LIBPATH=[Dir('.')])

    libdaos_tgts.extend(denv.SharedObject(['dc_kv.c']))


if __name__ == "SCons.Script":
    scons()
