"""Build dtx library"""
import daos_build

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    env.AppendUnique(LIBPATH=[Dir('.')])
    denv = env.Clone()

    prereqs.require(denv, 'argobots', 'protobufc', 'hwloc')

    # dtx
    dtx = daos_build.library(denv, 'dtx',
                             ['dtx_srv.c', 'dtx_rpc.c', 'dtx_resync.c',
                              'dtx_common.c', 'dtx_cos.c'])
    denv.Install('$PREFIX/lib64/daos_srv', dtx)

if __name__ == "SCons.Script":
    scons()
