"""Build DAOS Addons"""

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    denv = env.Clone()

    denv.AppendUnique(LIBPATH=[Dir('.')])
    prereqs.require(denv, 'ompi')

    dc_array_tgts = denv.SharedObject(['dc_array.c'])

    Export('dc_array_tgts')

if __name__ == "SCons.Script":
    scons()
