#!python

Import('env', 'PREREQS')

env.Append(CPPPATH = ['#/src/dtp'])
env.AppendUnique(LIBPATH=[Dir('.')])

libraries = ['daos_common', 'mercury']

if PREREQS is None:
    libraries.append(['mercury','na','mcl'])
else:
    PREREQS.require(env, 'mercury', 'mcl')

dtp = env.SharedLibrary('libdaos_transport', Glob('*.c'), LIBS=libraries)
env.Install('$PREFIX/lib/', dtp)

# Builders
SConscript('tests/SConscript', exports='env')
