#!python

Import('env')

env.Append(CPPPATH = ['#/src/dtp'])

env.Library('libdaos_transport', Glob('*.c'))
env.Append(LIBPATH = ['#/build/dtp'])

# Builders
SConscript('tests/SConscript', exports='env')
