#!python

Import('env', 'PREREQS')

env.Append(CPPPATH = ['#/src/dtp'])

libraries = ['daos_common', 'mercury']
libraries += ['pset']

if PREREQS is None:
    libraries.append(['mercury','na'])
else:
    PREREQS.require(env, 'mercury', 'iof')

dtp = env.SharedLibrary('libdaos_transport', Glob('*.c'), LIBS=libraries)
env.Install('#/build/lib/', dtp)

# Builders
SConscript('tests/SConscript', exports='env')
