"""Build util"""
import os

def scons():
    """Execute build"""
    Import('env')

    util_install_dir = '$PREFIX/lib/daos/TESTING/ftest/util'

    env.Install(util_install_dir, Glob('*.*'))
    env.Install(os.path.join(util_install_dir, 'apricot'),
                ['apricot/setup.py', 'apricot/VERSION'])
    env.Install(os.path.join(util_install_dir, 'apricot/apricot'),
                Glob('apricot/apricot/*.py'))

if __name__ == "SCons.Script":
    scons()
