.TH daos 1 "11 June 2021"
.SH NAME
daos \- Command to manage DAOS pool/container/object
.SH SYNOPSIS
\fBdaos\fP RESOURCE COMMAND [OPTIONS]
.SH DESCRIPTION
daos is a tool that can be used to manage/query pool content,
create/query/manage/destroy a container inside a pool, copy data
between a POSIX container and a POSIX filesystem, clone a DAOS container,
or query/manage an object inside a container.
.SH OPTIONS
.SS Application Options
.TP
\fB\fB\-\-debug\fR\fP
enable debug output
.TP
\fB\fB\-\-verbose\fR\fP
enable verbose output (when applicable)
.TP
\fB\fB\-\-json\fR\fP
enable JSON output
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SH COMMANDS
.SS container
perform tasks related to DAOS containers

\fBAliases\fP: cont

.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container check
check objects' consistency in a container

\fBUsage\fP: container check [check-OPTIONS]
.TP
.SS check objects' consistency in a container
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-e\fR, \fB\-\-epc\fR\fP
container epoch
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container clone
clone a container

\fBUsage\fP: container clone [clone-OPTIONS]
.TP
.SS clone a container
.TP
\fB\fB\-S\fR, \fB\-\-src\fR (\fIrequired\fR)\fP
source container
.TP
\fB\fB\-D\fR, \fB\-\-dst\fR (\fIrequired\fR)\fP
destination container
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container create
create a container

\fBUsage\fP: container create [create-OPTIONS]
.TP
.SS create a container
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (optional)
.TP
\fB\fB\-t\fR, \fB\-\-type\fR <default: \fI"POSIX"\fR>\fP
container type
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
container namespace path
.TP
\fB\fB\-z\fR, \fB\-\-chunk-size\fR\fP
container chunk size
.TP
\fB\fB\-o\fR, \fB\-\-oclass\fR\fP
default object class
.TP
\fB\fB\-\-properties\fR\fP
container properties
.TP
\fB\fB\-A\fR, \fB\-\-acl-file\fR\fP
input file containing ACL
.TP
\fB\fB\-u\fR, \fB\-\-user\fR\fP
user who will own the container (username@[domain])
.TP
\fB\fB\-g\fR, \fB\-\-group\fR\fP
group who will own the container (group@[domain])
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container create-snapshot
create container snapshot

\fBUsage\fP: container create-snapshot [create-snapshot-OPTIONS]
.TP

\fBAliases\fP: create-snap

.SS create container snapshot
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-e\fR, \fB\-\-epc\fR\fP
epoch to use for snapshot
.TP
\fB\fB\-s\fR, \fB\-\-snap\fR\fP
snapshot name
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container delete-acl
delete a container's ACL

\fBUsage\fP: container delete-acl [delete-acl-OPTIONS]
.TP
.SS delete a container's ACL
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-P\fR, \fB\-\-principal\fR (\fIrequired\fR)\fP
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container delete-attribute
delete container user-defined attribute

\fBUsage\fP: container delete-attribute [delete-attribute-OPTIONS]
.TP

\fBAliases\fP: del-attr

.SS delete container user-defined attribute
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container destroy
destroy a container

\fBUsage\fP: container destroy [destroy-OPTIONS]
.TP
.SS destroy a container
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-f\fR, \fB\-\-force\fR\fP
force the container destroy
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container destroy-snapshot
destroy container snapshot

\fBUsage\fP: container destroy-snapshot [destroy-snapshot-OPTIONS]
.TP

\fBAliases\fP: destroy-snap

.SS destroy container snapshot
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-e\fR, \fB\-\-epc\fR\fP
snapshot epoch to delete
.TP
\fB\fB\-r\fR, \fB\-\-epcrange\fR\fP
range of snapshot epochs to delete
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container get-acl
get a container's ACL

\fBUsage\fP: container get-acl [get-acl-OPTIONS]
.TP
.SS get a container's ACL
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-O\fR, \fB\-\-outfile\fR\fP
write ACL to file
.TP
\fB\fB\-f\fR, \fB\-\-force\fR\fP
overwrite existing outfile
.TP
\fB\fB\-V\fR, \fB\-\-verbose\fR\fP
show verbose output
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container get-attribute
get container user-defined attribute

\fBUsage\fP: container get-attribute [get-attribute-OPTIONS]
.TP

\fBAliases\fP: get-attr

.SS get container user-defined attribute
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container get-property
get container user-defined attribute

\fBUsage\fP: container get-property [get-property-OPTIONS]
.TP

\fBAliases\fP: get-prop

.SS get container user-defined attribute
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-\-properties\fR <default: \fI"all"\fR>\fP
container properties to get
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container list-attributes
list container user-defined attributes

\fBUsage\fP: container list-attributes [list-attributes-OPTIONS]
.TP

\fBAliases\fP: list-attrs

.SS list container user-defined attributes
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-V\fR, \fB\-\-verbose\fR\fP
Include values
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container list-objects
list all objects in container

\fBUsage\fP: container list-objects [list-objects-OPTIONS]
.TP

\fBAliases\fP: list-obj

.SS list all objects in container
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-e\fR, \fB\-\-epc\fR\fP
container epoch
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container list-snapshots
list container snapshots

\fBUsage\fP: container list-snapshots [list-snapshots-OPTIONS]
.TP

\fBAliases\fP: list-snaps

.SS list container snapshots
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container overwrite-acl
replace a container's ACL

\fBUsage\fP: container overwrite-acl [overwrite-acl-OPTIONS]
.TP

\fBAliases\fP: replace

.SS replace a container's ACL
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-f\fR, \fB\-\-acl-file\fR (\fIrequired\fR)\fP
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container query
query a container

\fBUsage\fP: container query [query-OPTIONS]
.TP
.SS query a container
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container rollback
roll back container to specified snapshot

\fBUsage\fP: container rollback [rollback-OPTIONS]
.TP

\fBAliases\fP: rb

.SS roll back container to specified snapshot
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-e\fR, \fB\-\-epc\fR\fP
epoch to use for snapshot
.TP
\fB\fB\-s\fR, \fB\-\-snap\fR\fP
snapshot name
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container set-attribute
set container user-defined attribute

\fBUsage\fP: container set-attribute [set-attribute-OPTIONS]
.TP

\fBAliases\fP: set-attr

.SS set container user-defined attribute
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-a\fR, \fB\-\-attr\fR\fP
attribute name
.TP
\fB\fB\-v\fR, \fB\-\-value\fR\fP
attribute value
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container set-owner
change ownership for a container

\fBUsage\fP: container set-owner [set-owner-OPTIONS]
.TP
.SS change ownership for a container
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-u\fR, \fB\-\-user\fR\fP
user who will own the container
.TP
\fB\fB\-g\fR, \fB\-\-group\fR\fP
group who will own the container
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container set-property
set container user-defined attribute

\fBUsage\fP: container set-property [set-property-OPTIONS]
.TP

\fBAliases\fP: set-prop

.SS set container user-defined attribute
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-\-properties\fR (\fIrequired\fR)\fP
container properties to set
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container stat
get container statistics

\fBUsage\fP: container stat [stat-OPTIONS]
.TP
.SS get container statistics
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS container update-acl
update a container's ACL

\fBUsage\fP: container update-acl [update-acl-OPTIONS]
.TP
.SS update a container's ACL
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-e\fR, \fB\-\-entry\fR\fP
.TP
\fB\fB\-f\fR, \fB\-\-acl-file\fR\fP
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS filesystem
POSIX filesystem operations

\fBAliases\fP: fs

.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS filesystem copy
copy to and from a POSIX filesystem

\fBUsage\fP: filesystem copy [copy-OPTIONS]
.TP
.SS copy to and from a POSIX filesystem
.TP
\fB\fB\-s\fR, \fB\-\-src\fR (\fIrequired\fR)\fP
copy source
.TP
\fB\fB\-d\fR, \fB\-\-dst\fR (\fIrequired\fR)\fP
copy destination
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS filesystem get-attr
get fs attributes

\fBUsage\fP: filesystem get-attr [get-attr-OPTIONS]
.TP
.SS get fs attributes
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-z\fR, \fB\-\-chunk-size\fR\fP
container chunk size
.TP
\fB\fB\-o\fR, \fB\-\-oclass\fR\fP
default object class
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS filesystem reset-attr
reset fs attributes

\fBUsage\fP: filesystem reset-attr [reset-attr-OPTIONS]
.TP
.SS reset fs attributes
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-z\fR, \fB\-\-chunk-size\fR\fP
container chunk size
.TP
\fB\fB\-o\fR, \fB\-\-oclass\fR\fP
default object class
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS filesystem reset-chunk-size
reset fs chunk size

\fBUsage\fP: filesystem reset-chunk-size [reset-chunk-size-OPTIONS]
.TP
.SS reset fs chunk size
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-z\fR, \fB\-\-chunk-size\fR\fP
container chunk size
.TP
\fB\fB\-o\fR, \fB\-\-oclass\fR\fP
default object class
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS filesystem reset-oclass
reset fs obj class

\fBUsage\fP: filesystem reset-oclass [reset-oclass-OPTIONS]
.TP
.SS reset fs obj class
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-z\fR, \fB\-\-chunk-size\fR\fP
container chunk size
.TP
\fB\fB\-o\fR, \fB\-\-oclass\fR\fP
default object class
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS filesystem set-attr
set fs attributes

\fBUsage\fP: filesystem set-attr [set-attr-OPTIONS]
.TP
.SS set fs attributes
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-z\fR, \fB\-\-chunk-size\fR\fP
container chunk size
.TP
\fB\fB\-o\fR, \fB\-\-oclass\fR\fP
default object class
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS object
DAOS object operations

\fBAliases\fP: obj

.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS object query
query an object's layout

\fBUsage\fP: object query [query-OPTIONS]
.TP
.SS query an object's layout
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-d\fR, \fB\-\-path\fR\fP
unified namespace path
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR\fP
container UUID (deprecated; use positional arg)
.TP
\fB\fB\-i\fR, \fB\-\-oid\fR\fP
DAOS object id (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS pool
perform tasks related to DAOS pools
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS pool autotest
verify setup with smoke tests

\fBUsage\fP: pool autotest [autotest-OPTIONS]
.TP
.SS verify setup with smoke tests
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS pool delete-attribute
delete pool user-defined attribute

\fBUsage\fP: pool delete-attribute [delete-attribute-OPTIONS]
.TP

\fBAliases\fP: del-attr

.SS delete pool user-defined attribute
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS pool get-attribute
get pool user-defined attribute

\fBUsage\fP: pool get-attribute [get-attribute-OPTIONS]
.TP

\fBAliases\fP: get-attr

.SS get pool user-defined attribute
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS pool list-attributes
list pool user-defined attributes

\fBUsage\fP: pool list-attributes [list-attributes-OPTIONS]
.TP

\fBAliases\fP: list-attrs

.SS list pool user-defined attributes
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.TP
\fB\fB\-V\fR, \fB\-\-verbose\fR\fP
Include values
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS pool list-containers
list all containers in pool

\fBUsage\fP: pool list-containers [list-containers-OPTIONS]
.TP

\fBAliases\fP: list-cont, ls

.SS list all containers in pool
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS pool query
query pool info

\fBUsage\fP: pool query [query-OPTIONS]
.TP
.SS query pool info
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS pool set-attribute
set pool user-defined attribute

\fBUsage\fP: pool set-attribute [set-attribute-OPTIONS]
.TP

\fBAliases\fP: set-attr

.SS set pool user-defined attribute
.TP
\fB\fB\-G\fR, \fB\-\-sys-name\fR\fP
DAOS system name
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR\fP
pool UUID (deprecated; use positional arg)
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SS version
print daos version
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
