.TH dmg 1 "8 October 2020"
.SH NAME
dmg \- Administrative tool for managing DAOS clusters
.SH SYNOPSIS
\fBdmg\fP [OPTIONS] [COMMAND] [SUBCOMMAND]
.SH DESCRIPTION
dmg (DAOS Management) is a tool for connecting to DAOS servers
for the purpose of issuing administrative commands to the cluster. dmg is
provided as a means for allowing administrators to securely discover and
administer DAOS components such as storage allocations, network configuration,
and access control settings, along with system wide operations.
.SH OPTIONS
.SS Application Options
.TP
\fB\fB\-\-allow-proxy\fR\fP
Allow proxy configuration via environment
.TP
\fB\fB\-l\fR, \fB\-\-host-list\fR\fP
comma separated list of addresses <ipv4addr/hostname:port>
.TP
\fB\fB\-i\fR, \fB\-\-insecure\fR\fP
have dmg attempt to connect without certificates
.TP
\fB\fB\-d\fR, \fB\-\-debug\fR\fP
enable debug output
.TP
\fB\fB\-j\fR, \fB\-\-json\fR\fP
Enable JSON output
.TP
\fB\fB\-J\fR, \fB\-\-json-logging\fR\fP
Enable JSON-formatted log output
.TP
\fB\fB\-o\fR, \fB\-\-config-path\fR\fP
Client config file path
.SH COMMANDS
.SS cont
Perform tasks related to DAOS containers

\fBAliases\fP: c

.SS cont set-owner
Change the owner for a DAOS container

\fBUsage\fP: cont set-owner [set-owner-OPTIONS]
.TP
.TP
\fB\fB\-g\fR, \fB\-\-group\fR\fP
New owner-group for the container, format name@domain
.TP
\fB\fB\-u\fR, \fB\-\-user\fR\fP
New owner-user for the container, format name@domain
.TP
\fB\fB\-c\fR, \fB\-\-cont\fR (\fIrequired\fR)\fP
UUID of the DAOS container
.TP
\fB\fB\-p\fR, \fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of the DAOS pool for the container
.SS network
Perform tasks related to network devices attached to remote servers

\fBAliases\fP: n

.SS network scan
Scan for network interface devices on remote servers

\fBUsage\fP: network scan [scan-OPTIONS]
.TP
.TP
\fB\fB\-p\fR, \fB\-\-provider\fR\fP
Filter device list to those that support the given OFI provider or 'all' for all available (default is the provider specified in daos_server.yml)
.SS pool
Perform tasks related to DAOS pools

\fBAliases\fP: p

.SS pool create
Create a DAOS pool

\fBUsage\fP: pool create [create-OPTIONS]
.TP

\fBAliases\fP: c

.TP
\fB\fB\-g\fR, \fB\-\-group\fR\fP
DAOS pool to be owned by given group, format name@domain
.TP
\fB\fB\-u\fR, \fB\-\-user\fR\fP
DAOS pool to be owned by given user, format name@domain
.TP
\fB\fB\-a\fR, \fB\-\-acl-file\fR\fP
Access Control List file path for DAOS pool
.TP
\fB\fB\-s\fR, \fB\-\-scm-size\fR (\fIrequired\fR)\fP
Size of SCM component of DAOS pool
.TP
\fB\fB\-n\fR, \fB\-\-nvme-size\fR\fP
Size of NVMe component of DAOS pool
.TP
\fB\fB\-r\fR, \fB\-\-ranks\fR\fP
Storage server unique identifiers (ranks) for DAOS pool
.TP
\fB\fB\-v\fR, \fB\-\-nsvc\fR <default: \fI"1"\fR>\fP
Number of pool service replicas
.TP
\fB\fB\-S\fR, \fB\-\-sys\fR <default: \fI"daos_server"\fR>\fP
DAOS system that pool is to be a part of
.SS pool delete-acl
Delete an entry from a DAOS pool's Access Control List

\fBUsage\fP: pool delete-acl [delete-acl-OPTIONS]
.TP

\fBAliases\fP: da

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of DAOS pool
.TP
\fB\fB\-p\fR, \fB\-\-principal\fR (\fIrequired\fR)\fP
Principal whose entry should be removed
.SS pool destroy
Destroy a DAOS pool

\fBUsage\fP: pool destroy [destroy-OPTIONS]
.TP

\fBAliases\fP: d

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of DAOS pool to destroy
.TP
\fB\fB\-f\fR, \fB\-\-force\fR\fP
Force removal of DAOS pool
.SS pool drain
Drain targets from a rank

\fBUsage\fP: pool drain [drain-OPTIONS]
.TP

\fBAliases\fP: d

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of the DAOS pool to drain a target in
.TP
\fB\fB\-\-rank\fR (\fIrequired\fR)\fP
Rank of the targets to be drained
.TP
\fB\fB\-\-target-idx\fR\fP
Comma-separated list of target idx(s) to be drained on the rank
.SS pool evict
Evict all pool connections to a DAOS pool

\fBUsage\fP: pool evict [evict-OPTIONS]
.TP

\fBAliases\fP: ev

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of DAOS pool to evict connection to
.TP
\fB\fB\-S\fR, \fB\-\-sys\fR <default: \fI"daos_server"\fR>\fP
DAOS system that the pools connections be evicted from.
.SS pool exclude
Exclude targets from a rank

\fBUsage\fP: pool exclude [exclude-OPTIONS]
.TP

\fBAliases\fP: e

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of the DAOS pool to exclude a target from
.TP
\fB\fB\-\-rank\fR (\fIrequired\fR)\fP
Rank of the targets to be excluded
.TP
\fB\fB\-\-target-idx\fR\fP
Comma-separated list of target idx(s) to be excluded from the rank
.SS pool extend
Extend a DAOS pool to include new ranks.

\fBUsage\fP: pool extend [extend-OPTIONS]
.TP

\fBAliases\fP: ext

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of the DAOS pool to extend
.TP
\fB\fB\-\-ranks\fR (\fIrequired\fR)\fP
Comma-separated list of ranks to add to the pool
.TP
\fB\fB\-s\fR, \fB\-\-scm-size\fR (\fIrequired\fR)\fP
Size of SCM component of the original DAOS pool being extended
.TP
\fB\fB\-n\fR, \fB\-\-nvme-size\fR\fP
Size of NVMe component of the original DAOS pool being extended, or none if not originally supplied to pool create.
.SS pool get-acl
Get a DAOS pool's Access Control List

\fBUsage\fP: pool get-acl [get-acl-OPTIONS]
.TP

\fBAliases\fP: ga

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of DAOS pool
.TP
\fB\fB\-o\fR, \fB\-\-outfile\fR\fP
Output ACL to file
.TP
\fB\fB\-f\fR, \fB\-\-force\fR\fP
Allow to clobber output file
.TP
\fB\fB\-v\fR, \fB\-\-verbose\fR\fP
Add descriptive comments to ACL entries
.SS pool list
List DAOS pools

\fBAliases\fP: l

.SS pool overwrite-acl
Overwrite a DAOS pool's Access Control List

\fBUsage\fP: pool overwrite-acl [overwrite-acl-OPTIONS]
.TP

\fBAliases\fP: oa

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of DAOS pool
.TP
\fB\fB\-a\fR, \fB\-\-acl-file\fR (\fIrequired\fR)\fP
Path for new Access Control List file
.SS pool query
Query a DAOS pool

\fBUsage\fP: pool query [query-OPTIONS]
.TP

\fBAliases\fP: q

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of DAOS pool to query
.SS pool reintegrate
Reintegrate targets for a rank

\fBUsage\fP: pool reintegrate [reintegrate-OPTIONS]
.TP

\fBAliases\fP: r

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of the DAOS pool to start reintegration in
.TP
\fB\fB\-\-rank\fR (\fIrequired\fR)\fP
Rank of the targets to be reintegrated
.TP
\fB\fB\-\-target-idx\fR\fP
Comma-separated list of target idx(s) to be reintegrated into the rank
.SS pool set-prop
Set pool property

\fBUsage\fP: pool set-prop [set-prop-OPTIONS]
.TP

\fBAliases\fP: sp

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of DAOS pool
.TP
\fB\fB\-n\fR, \fB\-\-name\fR (\fIrequired\fR)\fP
Name of property to be set
.TP
\fB\fB\-v\fR, \fB\-\-value\fR (\fIrequired\fR)\fP
Value of property to be set
.SS pool update-acl
Update entries in a DAOS pool's Access Control List

\fBUsage\fP: pool update-acl [update-acl-OPTIONS]
.TP

\fBAliases\fP: ua

.TP
\fB\fB\-\-pool\fR (\fIrequired\fR)\fP
UUID of DAOS pool
.TP
\fB\fB\-a\fR, \fB\-\-acl-file\fR\fP
Path for new Access Control List file
.TP
\fB\fB\-e\fR, \fB\-\-entry\fR\fP
Single Access Control Entry to add or update
.SS storage
Perform tasks related to storage attached to remote servers

\fBAliases\fP: st

.SS storage format
Format SCM and NVMe storage attached to remote servers.

\fBUsage\fP: storage format [format-OPTIONS]
.TP

\fBAliases\fP: f

.TP
\fB\fB\-v\fR, \fB\-\-verbose\fR\fP
Show results of each SCM & NVMe device format operation
.TP
\fB\fB\-\-reformat\fR\fP
Reformat storage overwriting any existing filesystem (CAUTION: destructive operation)
.SS storage prepare
Prepare SCM and NVMe storage attached to remote servers.

\fBUsage\fP: storage prepare [prepare-OPTIONS]
.TP

\fBAliases\fP: p

.TP
\fB\fB\-w\fR, \fB\-\-pci-whitelist\fR\fP
Whitespace separated list of PCI devices (by address) to be unbound from Kernel driver and used with SPDK (default is all PCI devices).
.TP
\fB\fB\-p\fR, \fB\-\-hugepages\fR\fP
Number of hugepages to allocate (in MB) for use by SPDK (default 1024)
.TP
\fB\fB\-u\fR, \fB\-\-target-user\fR\fP
User that will own hugepage mountpoint directory and vfio groups.
.TP
\fB\fB\-n\fR, \fB\-\-nvme-only\fR\fP
Only prepare NVMe storage.
.TP
\fB\fB\-s\fR, \fB\-\-scm-only\fR\fP
Only prepare SCM.
.TP
\fB\fB\-\-reset\fR\fP
Reset SCM modules to memory mode after removing namespaces. Reset SPDK returning NVMe device bindings back to kernel modules.
.TP
\fB\fB\-f\fR, \fB\-\-force\fR\fP
Perform format without prompting for confirmation
.SS storage query
Query storage commands, including raw NVMe SSD device health stats and internal blobstore health info.

\fBAliases\fP: q

.SS storage query device-health
Query the device health

\fBUsage\fP: query device-health [device-health-OPTIONS]
.TP

\fBAliases\fP: d

.TP
\fB\fB\-u\fR, \fB\-\-uuid\fR (\fIrequired\fR)\fP
Device UUID
.SS storage query list-devices
List storage devices on the server

\fBUsage\fP: query list-devices [list-devices-OPTIONS]
.TP

\fBAliases\fP: d

.TP
\fB\fB\-r\fR, \fB\-\-rank\fR\fP
Constrain operation to the specified server rank
.TP
\fB\fB\-b\fR, \fB\-\-health\fR\fP
Include device health in results
.TP
\fB\fB\-u\fR, \fB\-\-uuid\fR\fP
Device UUID (all devices if blank)
.SS storage query list-pools
List pools on the server

\fBUsage\fP: query list-pools [list-pools-OPTIONS]
.TP

\fBAliases\fP: p

.TP
\fB\fB\-r\fR, \fB\-\-rank\fR\fP
Constrain operation to the specified server rank
.TP
\fB\fB\-u\fR, \fB\-\-uuid\fR\fP
Pool UUID (all pools if blank)
.TP
\fB\fB\-v\fR, \fB\-\-verbose\fR\fP
Show more detail about pools
.SS storage query target-health
Query the target health

\fBUsage\fP: query target-health [target-health-OPTIONS]
.TP

\fBAliases\fP: t

.TP
\fB\fB\-r\fR, \fB\-\-rank\fR (\fIrequired\fR)\fP
Server rank hosting target
.TP
\fB\fB\-t\fR, \fB\-\-tgtid\fR (\fIrequired\fR)\fP
VOS target ID to query
.SS storage query usage
Show SCM & NVMe storage space utilization per storage server

\fBAliases\fP: u

.SS storage scan
Scan SCM and NVMe storage attached to remote servers.

\fBUsage\fP: storage scan [scan-OPTIONS]
.TP

\fBAliases\fP: s

.TP
\fB\fB\-v\fR, \fB\-\-verbose\fR\fP
List SCM & NVMe device details
.TP
\fB\fB\-n\fR, \fB\-\-nvme-health\fR\fP
Display NVMe device health statistics
.TP
\fB\fB\-m\fR, \fB\-\-nvme-meta\fR\fP
Display server meta data held on NVMe storage
.SS storage set
Manually set the device state.

\fBAliases\fP: s

.SS storage set nvme-faulty
Manually set the device state of an NVMe SSD to FAULTY.

\fBUsage\fP: set nvme-faulty [nvme-faulty-OPTIONS]
.TP

\fBAliases\fP: n

.TP
\fB\fB\-u\fR, \fB\-\-uuid\fR (\fIrequired\fR)\fP
Device UUID to set
.TP
\fB\fB\-f\fR, \fB\-\-force\fR\fP
Do not require confirmation
.SS system
Perform distributed tasks related to DAOS system

\fBAliases\fP: sy

.SS system leader-query
Query for current Management Service leader

\fBAliases\fP: l

.SS system list-pools
List all pools in the DAOS system

\fBAliases\fP: p

.SS system query
Query DAOS system status

\fBUsage\fP: system query [query-OPTIONS]
.TP

\fBAliases\fP: q

.TP
\fB\fB\-r\fR, \fB\-\-ranks\fR\fP
Comma separated ranges or individual system ranks to operate on
.TP
\fB\fB\-\-rank-hosts\fR\fP
Hostlist representing hosts whose managed ranks are to be operated on
.TP
\fB\fB\-v\fR, \fB\-\-verbose\fR\fP
Display more member details
.SS system start
Perform start of stopped DAOS system

\fBUsage\fP: system start [start-OPTIONS]
.TP

\fBAliases\fP: r

.TP
\fB\fB\-r\fR, \fB\-\-ranks\fR\fP
Comma separated ranges or individual system ranks to operate on
.TP
\fB\fB\-\-rank-hosts\fR\fP
Hostlist representing hosts whose managed ranks are to be operated on
.SS system stop
Perform controlled shutdown of DAOS system

\fBUsage\fP: system stop [stop-OPTIONS]
.TP

\fBAliases\fP: s

.TP
\fB\fB\-r\fR, \fB\-\-ranks\fR\fP
Comma separated ranges or individual system ranks to operate on
.TP
\fB\fB\-\-rank-hosts\fR\fP
Hostlist representing hosts whose managed ranks are to be operated on
.TP
\fB\fB\-\-force\fR\fP
Force stop DAOS system members
.SS version
Print dmg version
