# (C) Copyright 2020-2021 Intel Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
"""Example code"""


def scons():
    """Execute build"""
    Import('env')

    env.d_test_program(File('telemetry_producer_example.c'), LIBS=['gurt'])

    env.d_test_program(File('telemetry_consumer_example.c'), LIBS=['gurt'])


if __name__ == "SCons.Script":
    scons()
