"""Build versioned extent allocator lib"""
def scons():
    """Execute build"""
    Import('env')

    denv = env.Clone()
    denv.Library('vea', Glob('*.c'), LIBS=['daos_common', 'gurt'])

    SConscript('tests/SConscript', exports='denv')

if __name__ == "SCons.Script":
    scons()
