#!/bin/bash

# set -x
set -e -o pipefail

if [[ "$(id -u)" != "0" ]] ; then
	echo "[ERROR] run-daos_agent can only be run as root"
	exit -1
fi

CWD="$(realpath "$(dirname $0)")"

mkdir -p /var/run/daos_agent/
chmod 755 /var/run/daos_agent/
chown daos_agent:daos_agent /var/run/daos_agent/

cd /var/run/daos_agent/
exec sudo --user=daos_agent --group=daos_agent /usr/bin/daos_agent "$@"
