"""Build addons test"""
import daos_build

def scons():
    """Execute build"""
    Import('denv')

    libraries = ['daos_common', 'daos', 'daos_tests', 'gurt', 'cart']
    libraries += ['uuid', 'mpi']
    libraries += ['cmocka']

    Import('daos_test_tgt')

    addons = denv.SharedObject(Glob('*.c'))
    daos_addons_test = daos_build.program(denv, 'daos_addons_test',
                                          daos_test_tgt + addons,
                                          LIBS=libraries)
    denv.Install('$PREFIX/bin/', daos_addons_test)

if __name__ == "SCons.Script":
    scons()
