//
// (C) Copyright 2019-2024 Intel Corporation.
// (C) Copyright 2026 Hewlett Packard Enterprise Development LP
//
// SPDX-License-Identifier: BSD-2-Clause-Patent
//

// This file defines the messages used by DRPC_MODULE_SRV.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.14.0
// source: srv/srv.proto

package srv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyReadyReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uri              string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`                               // Primary CaRT URI
	Nctxs            uint32                 `protobuf:"varint,2,opt,name=nctxs,proto3" json:"nctxs,omitempty"`                          // Number of primary CaRT contexts
	DrpcListenerSock string                 `protobuf:"bytes,3,opt,name=drpcListenerSock,proto3" json:"drpcListenerSock,omitempty"`     // Path to I/O Engine's dRPC listener socket
	InstanceIdx      uint32                 `protobuf:"varint,4,opt,name=instanceIdx,proto3" json:"instanceIdx,omitempty"`              // I/O Engine instance index
	Ntgts            uint32                 `protobuf:"varint,5,opt,name=ntgts,proto3" json:"ntgts,omitempty"`                          // number of VOS targets allocated in I/O Engine
	Incarnation      uint64                 `protobuf:"varint,6,opt,name=incarnation,proto3" json:"incarnation,omitempty"`              // HLC incarnation number
	SecondaryUris    []string               `protobuf:"bytes,7,rep,name=secondaryUris,proto3" json:"secondaryUris,omitempty"`           // secondary CaRT URIs
	SecondaryNctxs   []uint32               `protobuf:"varint,8,rep,packed,name=secondaryNctxs,proto3" json:"secondaryNctxs,omitempty"` // number of CaRT contexts for each secondary provider
	CheckMode        bool                   `protobuf:"varint,9,opt,name=check_mode,json=checkMode,proto3" json:"check_mode,omitempty"` // True if engine started in checker mode
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotifyReadyReq) Reset() {
	*x = NotifyReadyReq{}
	mi := &file_srv_srv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyReadyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReadyReq) ProtoMessage() {}

func (x *NotifyReadyReq) ProtoReflect() protoreflect.Message {
	mi := &file_srv_srv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReadyReq.ProtoReflect.Descriptor instead.
func (*NotifyReadyReq) Descriptor() ([]byte, []int) {
	return file_srv_srv_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyReadyReq) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *NotifyReadyReq) GetNctxs() uint32 {
	if x != nil {
		return x.Nctxs
	}
	return 0
}

func (x *NotifyReadyReq) GetDrpcListenerSock() string {
	if x != nil {
		return x.DrpcListenerSock
	}
	return ""
}

func (x *NotifyReadyReq) GetInstanceIdx() uint32 {
	if x != nil {
		return x.InstanceIdx
	}
	return 0
}

func (x *NotifyReadyReq) GetNtgts() uint32 {
	if x != nil {
		return x.Ntgts
	}
	return 0
}

func (x *NotifyReadyReq) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *NotifyReadyReq) GetSecondaryUris() []string {
	if x != nil {
		return x.SecondaryUris
	}
	return nil
}

func (x *NotifyReadyReq) GetSecondaryNctxs() []uint32 {
	if x != nil {
		return x.SecondaryNctxs
	}
	return nil
}

func (x *NotifyReadyReq) GetCheckMode() bool {
	if x != nil {
		return x.CheckMode
	}
	return false
}

type GetPoolSvcReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // Pool UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolSvcReq) Reset() {
	*x = GetPoolSvcReq{}
	mi := &file_srv_srv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolSvcReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolSvcReq) ProtoMessage() {}

func (x *GetPoolSvcReq) ProtoReflect() protoreflect.Message {
	mi := &file_srv_srv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolSvcReq.ProtoReflect.Descriptor instead.
func (*GetPoolSvcReq) Descriptor() ([]byte, []int) {
	return file_srv_srv_proto_rawDescGZIP(), []int{1}
}

func (x *GetPoolSvcReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetPoolSvcResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`          // DAOS error code
	Svcreps       []uint32               `protobuf:"varint,2,rep,packed,name=svcreps,proto3" json:"svcreps,omitempty"` // Pool service replica ranks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolSvcResp) Reset() {
	*x = GetPoolSvcResp{}
	mi := &file_srv_srv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolSvcResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolSvcResp) ProtoMessage() {}

func (x *GetPoolSvcResp) ProtoReflect() protoreflect.Message {
	mi := &file_srv_srv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolSvcResp.ProtoReflect.Descriptor instead.
func (*GetPoolSvcResp) Descriptor() ([]byte, []int) {
	return file_srv_srv_proto_rawDescGZIP(), []int{2}
}

func (x *GetPoolSvcResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetPoolSvcResp) GetSvcreps() []uint32 {
	if x != nil {
		return x.Svcreps
	}
	return nil
}

type PoolFindByLabelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"` // Pool label
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolFindByLabelReq) Reset() {
	*x = PoolFindByLabelReq{}
	mi := &file_srv_srv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolFindByLabelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolFindByLabelReq) ProtoMessage() {}

func (x *PoolFindByLabelReq) ProtoReflect() protoreflect.Message {
	mi := &file_srv_srv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolFindByLabelReq.ProtoReflect.Descriptor instead.
func (*PoolFindByLabelReq) Descriptor() ([]byte, []int) {
	return file_srv_srv_proto_rawDescGZIP(), []int{3}
}

func (x *PoolFindByLabelReq) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type PoolFindByLabelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`          // DAOS error code
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`               // Pool UUID
	Svcreps       []uint32               `protobuf:"varint,3,rep,packed,name=svcreps,proto3" json:"svcreps,omitempty"` // Pool service replica ranks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolFindByLabelResp) Reset() {
	*x = PoolFindByLabelResp{}
	mi := &file_srv_srv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolFindByLabelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolFindByLabelResp) ProtoMessage() {}

func (x *PoolFindByLabelResp) ProtoReflect() protoreflect.Message {
	mi := &file_srv_srv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolFindByLabelResp.ProtoReflect.Descriptor instead.
func (*PoolFindByLabelResp) Descriptor() ([]byte, []int) {
	return file_srv_srv_proto_rawDescGZIP(), []int{4}
}

func (x *PoolFindByLabelResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PoolFindByLabelResp) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PoolFindByLabelResp) GetSvcreps() []uint32 {
	if x != nil {
		return x.Svcreps
	}
	return nil
}

type ListPoolsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeAll    bool                   `protobuf:"varint,1,opt,name=include_all,json=includeAll,proto3" json:"include_all,omitempty"` // Include all pools in response, regardless of state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsReq) Reset() {
	*x = ListPoolsReq{}
	mi := &file_srv_srv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsReq) ProtoMessage() {}

func (x *ListPoolsReq) ProtoReflect() protoreflect.Message {
	mi := &file_srv_srv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsReq.ProtoReflect.Descriptor instead.
func (*ListPoolsReq) Descriptor() ([]byte, []int) {
	return file_srv_srv_proto_rawDescGZIP(), []int{5}
}

func (x *ListPoolsReq) GetIncludeAll() bool {
	if x != nil {
		return x.IncludeAll
	}
	return false
}

type ListPoolsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pools         []*ListPoolsResp_Pool  `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"` // List of pools
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsResp) Reset() {
	*x = ListPoolsResp{}
	mi := &file_srv_srv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsResp) ProtoMessage() {}

func (x *ListPoolsResp) ProtoReflect() protoreflect.Message {
	mi := &file_srv_srv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsResp.ProtoReflect.Descriptor instead.
func (*ListPoolsResp) Descriptor() ([]byte, []int) {
	return file_srv_srv_proto_rawDescGZIP(), []int{6}
}

func (x *ListPoolsResp) GetPools() []*ListPoolsResp_Pool {
	if x != nil {
		return x.Pools
	}
	return nil
}

type ListPoolsResp_Pool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`               // Pool UUID
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`             // Pool label
	Svcreps       []uint32               `protobuf:"varint,3,rep,packed,name=svcreps,proto3" json:"svcreps,omitempty"` // Pool service ranks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsResp_Pool) Reset() {
	*x = ListPoolsResp_Pool{}
	mi := &file_srv_srv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsResp_Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsResp_Pool) ProtoMessage() {}

func (x *ListPoolsResp_Pool) ProtoReflect() protoreflect.Message {
	mi := &file_srv_srv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsResp_Pool.ProtoReflect.Descriptor instead.
func (*ListPoolsResp_Pool) Descriptor() ([]byte, []int) {
	return file_srv_srv_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ListPoolsResp_Pool) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ListPoolsResp_Pool) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ListPoolsResp_Pool) GetSvcreps() []uint32 {
	if x != nil {
		return x.Svcreps
	}
	return nil
}

var File_srv_srv_proto protoreflect.FileDescriptor

const file_srv_srv_proto_rawDesc = "" +
	"\n" +
	"\rsrv/srv.proto\x12\x03srv\"\xab\x02\n" +
	"\x0eNotifyReadyReq\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x14\n" +
	"\x05nctxs\x18\x02 \x01(\rR\x05nctxs\x12*\n" +
	"\x10drpcListenerSock\x18\x03 \x01(\tR\x10drpcListenerSock\x12 \n" +
	"\vinstanceIdx\x18\x04 \x01(\rR\vinstanceIdx\x12\x14\n" +
	"\x05ntgts\x18\x05 \x01(\rR\x05ntgts\x12 \n" +
	"\vincarnation\x18\x06 \x01(\x04R\vincarnation\x12$\n" +
	"\rsecondaryUris\x18\a \x03(\tR\rsecondaryUris\x12&\n" +
	"\x0esecondaryNctxs\x18\b \x03(\rR\x0esecondaryNctxs\x12\x1d\n" +
	"\n" +
	"check_mode\x18\t \x01(\bR\tcheckMode\"#\n" +
	"\rGetPoolSvcReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"B\n" +
	"\x0eGetPoolSvcResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\asvcreps\x18\x02 \x03(\rR\asvcreps\"*\n" +
	"\x12PoolFindByLabelReq\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"[\n" +
	"\x13PoolFindByLabelResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x18\n" +
	"\asvcreps\x18\x03 \x03(\rR\asvcreps\"/\n" +
	"\fListPoolsReq\x12\x1f\n" +
	"\vinclude_all\x18\x01 \x01(\bR\n" +
	"includeAll\"\x8a\x01\n" +
	"\rListPoolsResp\x12-\n" +
	"\x05pools\x18\x01 \x03(\v2\x17.srv.ListPoolsResp.PoolR\x05pools\x1aJ\n" +
	"\x04Pool\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\asvcreps\x18\x03 \x03(\rR\asvcrepsB9Z7github.com/daos-stack/daos/src/control/common/proto/srvb\x06proto3"

var (
	file_srv_srv_proto_rawDescOnce sync.Once
	file_srv_srv_proto_rawDescData []byte
)

func file_srv_srv_proto_rawDescGZIP() []byte {
	file_srv_srv_proto_rawDescOnce.Do(func() {
		file_srv_srv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_srv_srv_proto_rawDesc), len(file_srv_srv_proto_rawDesc)))
	})
	return file_srv_srv_proto_rawDescData
}

var file_srv_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_srv_srv_proto_goTypes = []any{
	(*NotifyReadyReq)(nil),      // 0: srv.NotifyReadyReq
	(*GetPoolSvcReq)(nil),       // 1: srv.GetPoolSvcReq
	(*GetPoolSvcResp)(nil),      // 2: srv.GetPoolSvcResp
	(*PoolFindByLabelReq)(nil),  // 3: srv.PoolFindByLabelReq
	(*PoolFindByLabelResp)(nil), // 4: srv.PoolFindByLabelResp
	(*ListPoolsReq)(nil),        // 5: srv.ListPoolsReq
	(*ListPoolsResp)(nil),       // 6: srv.ListPoolsResp
	(*ListPoolsResp_Pool)(nil),  // 7: srv.ListPoolsResp.Pool
}
var file_srv_srv_proto_depIdxs = []int32{
	7, // 0: srv.ListPoolsResp.pools:type_name -> srv.ListPoolsResp.Pool
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_srv_srv_proto_init() }
func file_srv_srv_proto_init() {
	if File_srv_srv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_srv_srv_proto_rawDesc), len(file_srv_srv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_srv_srv_proto_goTypes,
		DependencyIndexes: file_srv_srv_proto_depIdxs,
		MessageInfos:      file_srv_srv_proto_msgTypes,
	}.Build()
	File_srv_srv_proto = out.File
	file_srv_srv_proto_goTypes = nil
	file_srv_srv_proto_depIdxs = nil
}
