"""Build rebuild library"""

def scons():
    """Execute build"""
    Import('env')

    env.AppendUnique(LIBPATH=[Dir('.')])
    denv = env.Clone()

    # rebuild
    rebuild = denv.SharedLibrary('rebuild',
                                 ['scan.c', 'srv.c', 'rpc.c', 'initiator.c',
                                  'rebuild_iv.c', "srv_daos_api.c"])
    denv.Install('$PREFIX/lib/daos_srv', rebuild)

if __name__ == "SCons.Script":
    scons()
