"""Build rebuild library"""


def scons():
    """Execute build"""
    Import('env', 'prereqs')

    env.AppendUnique(LIBPATH=[Dir('.')])

    if not prereqs.server_requested():
        return

    denv = env.Clone()

    denv.require('argobots', 'protobufc')

    denv.Append(CCFLAGS=['-Wframe-larger-than=131072'])
    # rebuild
    rebuild = denv.d_library('rebuild',
                             ['scan.c', 'srv.c', 'rpc.c', 'ras.c', 'rebuild_iv.c'],
                             install_off="../..")
    denv.Install('$PREFIX/lib64/daos_srv', rebuild)


if __name__ == "SCons.Script":
    scons()
