"""Build versioned extent allocator tests"""
import daos_build

def scons():
    """Execute build"""
    Import('denv')

    libraries = ['vea', 'gurt', 'cart', 'pmemobj', 'cmocka', 'daos_common']

    denv.Append(CPPPATH=['#/src/vos/vea/tests/'])
    denv.AppendUnique(LIBPATH=['..'])
    daos_build.test(denv, 'vea_ut', 'vea_ut.c', LIBS=libraries)

if __name__ == "SCons.Script":
    scons()
