#!python

Import('env')

env.AppendUnique(LIBPATH=[Dir('.')])

denv = env.Clone()

# dmgs: DMG Server Module
mgmt_srv = denv.SharedLibrary('daos_mgmt_srv',
			      ['dmg_rpc.c', 'dmgs_module.c', 'dmgs_pool.c',
			       'dmgs_target.c'])
denv.Install('$PREFIX/lib/daos_srv', mgmt_srv)

# dmgc: DMG Client Library
mgmt = denv.SharedLibrary('daos_mgmt',
			  ['dmg_rpc.c', 'dmgc_module.c', 'dmgc_pool.c'])
denv.Install('$PREFIX/lib/', mgmt)

# tests
SConscript('tests/SConscript', exports = 'denv')
