#!/bin/bash
set -eu

if [ -n "${NO_PREPARE_COMMIT_MSG:=""}" ]; then
    exit 0
fi

run-parts() {
    local dir="$1"
    shift

    for i in $(LC_ALL=C; echo "${dir%/}"/*[^~,]); do
        # don't run vim .swp files
        [ "${i%.sw?}" != "${i}" ] && continue
        $i "$@"
    done
}

run-parts utils/githooks/"${0##*/}".d "$@" 1>&2
