"""Build Per-server Metadata"""
def scons():
    """Execute build"""
    Import('env')

    env.AppendUnique(LIBPATH=[Dir('.')])

    denv = env.Clone()
    denv.AppendUnique(CPPPATH=['#/src/eio/smd/'])
    denv.Library('smd', Glob('*.c'), LIBS=['daos_common', 'gurt', 'pmemobj'])

    #SConscript('tests/SConscript', exports='denv')

if __name__ == "SCons.Script":
    scons()
