# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy locally a DAOS virtual cluster

version: "3.8"

services:

  daos_base:
    image: "daos-base:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-base/el8"
      args:
        - "DAOS_CLIENT_UNAME=${DAOS_CLIENT_UNAME}"
        - "DAOS_CLIENT_UID=${DAOS_CLIENT_UID}"
        - "DAOS_CLIENT_GNAME=${DAOS_CLIENT_GNAME}"
        - "DAOS_CLIENT_GID=${DAOS_CLIENT_GID}"
        - "RHEL_BASE_IMAGE_NAME=${RHEL_BASE_IMAGE_NAME}"
        - "RHEL_BASE_IMAGE_TAG=${RHEL_BASE_IMAGE_TAG}"
        - "BUST_CACHE=${BUST_CACHE}"
        - "DAOS_REPOS=${DAOS_REPOS}"
        - "DAOS_GPG_KEYS=${DAOS_GPG_KEYS}"
        - "DAOS_REPOS_NOAUTH=${DAOS_REPOS_NOAUTH}"
        - "DAOS_VERSION=${DAOS_VERSION}"
    tty: true
