# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy locally a DAOS virtual cluster

version: "3.8"

services:

  daos_client_agent:
    image: "daos-client_agent:${DAOS_DOCKER_IMAGE_TAG}"
    tty: true
    networks:
      - docker_host
    secrets:
      - source: daos_agent-certs
        target: daos_agent-certs.txz
        uid: '0'
        gid: '0'
        mode: 0600


secrets:
  daos_agent-certs:
    external: true


networks:
  docker_host:
    name: "host"
    external: true
