# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy locally a DAOS virtual cluster

version: "3.8"

services:

  daos_client:
    image: "daos-client:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-client/el8"
      args:
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
    tty: true
    network_mode: host
    pid: host
    cap_add:
      - SYS_ADMIN
    user: "${DAOS_CLIENT_UID}:${DAOS_CLIENT_GID}"
    volumes:
      - type: bind
        source: "${DAOS_AGENT_RUNTIME_DIR}"
        target: /var/run/daos_agent
    devices:
      - "/dev/fuse:/dev/fuse"
