"""Build pool tests"""

def scons():
    """Execute build"""
    Import('denv')

    denv.Append(CPPPATH=['#/src/dsm', '#/src/server'])

    #libraries = ['daos_common', 'daos', 'gurt', 'cart']
    #libraries += ['uuid', 'mpi']
    #libraries += ['cmocka']

    #PREREQS.require(denv, 'ompi')
    #
    #denv.Program('dsm_test', Glob('*.c'), LIBS=libraries)
if __name__ == "SCons.Script":
    scons()
