"""Build pool tests"""

def scons():
    """Execute build"""
    Import('denv')

    denv.Append(CPPPATH=['#/src/dsm', '#/src/server'])

    #Import('prereqs build_program')
    #libraries = ['daos_common', 'daos', 'gurt', 'cart']
    #libraries += ['uuid', 'mpi']
    #libraries += ['cmocka']

    #prereqs.require(denv, 'ompi')
    #
    #build_program(denv, 'dsm_test', Glob('*.c'), LIBS=libraries)
if __name__ == "SCons.Script":
    scons()
