#
# Copyright 2018, Intel Corporation
#
# 'recipe' for Docker to build an image of centOS-based
# environment for building the DAOS project.
#

# Pull base image
FROM opensuse/leap:15
MAINTAINER Johann Lombardi <johann.lombardi@intel.com>

# Build arguments can be set via -build-arg
# set NOBUILD to disable git clone & build
ARG NOBUILD
# use same UID as host and default value of 1000 if not specified
ARG UID=1000

ENV USER daos
ENV PASSWD daos

# Install basic tools
RUN zypper --non-interactive addrepo \
  https://provo-mirror.opensuse.org/repositories/\
home:/jhli/SLE_15/home:jhli.repo; \
  zypper --non-interactive --gpg-auto-import-keys ref; \
  zypper --non-interactive install astyle boost-devel clang clang-checker \
  cmake cunit-devel curl doxygen flex git gcc gcc-c++ graphviz gzip lcov \
  make meson mscgen nasm ninja numactl pandoc patch readline-devel \
  scons sg3_utils tar yasm \
  libaio-devel libcmocka0 libcmocka-devel libevent-devel libibverbs \
  libiscsi-devel libnuma-devel libopenssl-devel librdmacm1 libtool \
  libuuid-devel libyaml-devel \
  python python-configparser python-devel \
  python2-configparser2 python2-paramiko python2-pep8 python2-pip \
  python2-pylint python2-PyYAML \
  python3 python3-configparser2 python3-devel python3-paramiko \
  python3-pip python3-pep8 python3-pylint python3-PyYAML \
  ipmctl-devel; \
  if [ ! -e /usr/bin/ninja-build ];then \
    ln -s /usr/bin/ninja /usr/bin/ninja-build; fi; \
  pip2 install --upgrade pip; pip2 install -U setuptools wheel; \
  pip2 install scons==3.0.1 PyGithub==1.39

ENV GO_TARBALL go1.9.7.linux-amd64.tar.gz
RUN curl -k "https://dl.google.com/go/${GO_TARBALL}" \
         -o "${GO_TARBALL}"; \
    tar -C /usr/local -xzf "${GO_TARBALL}"; \
    rm -f "${GO_TARBALL}"; \
    if [ ! -e /usr/local/bin/go ] ; then \
      ln -s /usr/local/go/bin/go /usr/local/bin/go ; \
    fi; \
    if [ ! -e /usr/local/bin/godoc ] ; then \
      ln -s /usr/local/go/bin/godoc /usr/local/bin/godoc ; \
    fi; \
    if [ ! -e /usr/local/bin/gofmt ] ; then \
      ln -s /usr/local/go/bin/gofmt /usr/local/bin/gofmt ; \
    fi

RUN useradd -u $UID -ms /bin/bash $USER ;echo "$USER:$PASSWD" | chpasswd

# Create directory for DAOS backend storage
RUN mkdir /mnt/daos; chown $UID /mnt/daos

# Create a target directory for prebuilts
RUN mkdir -p /testbin; chown $UID /testbin; ls -ld /testbin

# Switch to new user
USER $USER

WORKDIR /home/$USER

RUN if [ -n "${HTTP_PROXY}" ]; then \
  git config --global http.proxy "${HTTP_PROXY}"; \
  printf "proxy = %s\n" "${HTTP_PROXY##*/}" >> ~/.curlrc; fi

