"""Build DAOS utilities"""
import daos_build

def scons():
    """Execute build"""
    Import('env', 'prereqs')
    libs = ['daos', 'daos_common', 'uuid', 'dfs', 'duns', 'gurt', 'cart']

    denv = env.Clone()
    denv.AppendUnique(LIBPATH=["../client/dfs"])

    daos_extra_files = denv.Object('daos_hdlr.c')

    daos = daos_build.program(denv, 'daos',
                              ['daos.c', daos_extra_files], LIBS=libs)
    denv.Install('$PREFIX/bin/', daos)

if __name__ == "SCons.Script":
    scons()
