"""Build daos fio engine"""
from __future__ import print_function

import daos_build

def scons():
    """Execute build"""

    Import('env', 'prereqs')

    libs = ['daos_common', 'daos', 'dfs', 'gurt', 'uuid', 'dl']

    denv = env.Clone()

    if prereqs.has_source(env, 'fio'):
        print("Building DAOS FIO Engine with source dir", env.subst("$FIO_SRC"))
    else:
        print("Skipping DAOS FIO Engine build")
        return

    denv.AppendUnique(CPPPATH=["$FIO_SRC"])
    denv.AppendUnique(LIBPATH=[Dir("../../client/dfs")])

    # daos fio engine
    daos_fio = daos_build.library(denv, 'daos_fio', ['daos_fio.c'], LIBS=libs)
    denv.Install('$PREFIX/share/daos/fio_engine', daos_fio)

    daos_fio_async = daos_build.library(denv, 'daos_fio_async',
                                        ['daos_fio_async.c'], LIBS=libs)
    denv.Install('$PREFIX/share/daos/fio_engine', daos_fio_async)

if __name__ == "SCons.Script":
    scons()
