"""Build DAOS Serialize Library"""


def scons():
    """Execute build"""

    Import('env', 'have_hdf5')

    denv = env.Clone()

    # If hdf5 installed build DAOS serialization library
    libraries = ['daos', 'hdf5']

    src = ['daos_serialize.c']
    if have_hdf5 is True:
        if not GetOption('silent'):
            print("Building with hdf5 bindings.")
        daos_serialize = denv.d_library('daos_serialize', src, LIBS=libraries)
        denv.Install('$PREFIX/lib64/', daos_serialize)
    else:
        if not GetOption('silent'):
            print("No installed hdf5 detected, DAOS serialization is not enabled")


if __name__ == "SCons.Script":
    scons()
