name: 'Set Variable from Commit Pragma'
description: 'Set Variable from Commit Pragma'
inputs:
  commit_message:
    description: Dequoted commit message
    required: true
  pragma:
    description: Pragma to make a variable from
    required: true
  default:
    description: Default value if pragma is not found
    required: false
outputs:
  value:
    description: The value of the pragma
    value: ${{ steps.value.outputs.value }}

runs:
  using: "composite"
  steps:
    - name: Create Variable
      id: value
      shell: bash
      run: |
           . ci/gha_functions.sh
           set -eu
           eval $(echo '${{ inputs.commit_message }}' | get_commit_pragmas)
           echo "value=${${{ inputs.pragma }}:-${{ inputs.default }}}" >> $GITHUB_OUTPUT
