#!python
# (C) Copyright 2016-2021 Intel Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
"""Build self test"""

import os
import daos_build

SELF_TEST = 'self_test.c'

def scons():
    """scons function"""

    Import('env', 'prereqs')

    tenv = env.Clone(LIBS=[])

    tenv.AppendUnique(LIBS=['cart', 'gurt', 'pthread', 'm'])
    prereqs.require(tenv, 'mercury')
    tenv.AppendUnique(FLAGS='-pthread')

    self_test = daos_build.program(tenv, SELF_TEST)
    tenv.Install(os.path.join("$PREFIX", 'bin'), self_test)

if __name__ == "SCons.Script":
    scons()
