#!python
# (C) Copyright 2016-2021 Intel Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
"""Build self test"""


def scons():
    """scons function"""

    Import('env', 'cart_utils_objs')

    tenv = env.Clone(LIBS=[])

    tenv.AppendUnique(LIBS=['cart', 'gurt', 'pthread', 'm', 'daos', 'daos_common'])
    tenv.d_add_requires('mercury', 'protobufc')
    tenv.AppendUnique(FLAGS='-pthread')
    tenv.AppendUnique(CPPPATH=[Dir('../../cart/utils').srcnode()])

    self_test = tenv.d_program(['self_test.c', cart_utils_objs])
    tenv.Install('$PREFIX/bin', self_test)


if __name__ == "SCons.Script":
    scons()
