#!python
# (C) Copyright 2016-2020 Intel Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# GOVERNMENT LICENSE RIGHTS-OPEN SOURCE SOFTWARE
# The Government's rights to use, modify, reproduce, release, perform, display,
# or disclose this software are subject to the terms of the Apache License as
# provided in Contract No. 8F-30005.
# Any reproduction of computer software, computer software documentation, or
# portions thereof marked with this legend must also reproduce the markings.
#
"""Build self test"""

import os
import daos_build

SELF_TEST = 'self_test.c'
LIB_CONFIG_INI = 'src/configini.c'

# Function to filter out gcc flags from this compilation env
def remove_certain_gcc_flags(str): 
    import re
    r = re.compile("\-Wframe\-larger\-than\=")
    if r.match(str):
        return False
    else: 
        return True

def scons():
    """scons function"""

    Import('env', 'prereqs', 'cart_lib', 'gurt_lib')

    tenv = env.Clone()

    tenv.AppendUnique(CPPPATH=['#/src/cart', '#/src/tests/ftest/cart'])
    tenv.AppendUnique(LIBS=['cart', 'gurt', 'pthread', 'm'])
    prereqs.require(tenv, 'mercury')
    tenv.AppendUnique(LIBPATH=['#/src/cart'])
    tenv.AppendUnique(FLAGS='-pthread')

    # Allow large stack size for config file parsing
    #lib_config_ini = Library(LIB_CONFIG_INI)
    #self_test = daos_build.program(tenv, [SELF_TEST, LIB_CONFIG_INI], LIBS=lib_config_ini)
    #self_test = daos_build.program(tenv, SELF_TEST)

    print tenv.Dump()
    self_test_tenv = tenv.Clone()
    new_CCFLAGS = filter(remove_certain_gcc_flags, self_test_tenv['CCFLAGS'])
    self_test_tenv['CCFLAGS'] = new_CCFLAGS
    print self_test_tenv.Dump()

    self_test = daos_build.program(self_test_tenv, [SELF_TEST, LIB_CONFIG_INI])
    self_test_tenv.Requires(self_test, [cart_lib, gurt_lib])
    self_test_tenv.Install(os.path.join("$PREFIX", 'bin'), self_test)

if __name__ == "SCons.Script":
    scons()
