# Copyright 2026 Hewlett Packard Enterprise Development LP
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
"""Build versioned object store tests"""


def build_dlck_test_helper(henv):
    """Build dlck_test_helper"""
    henv.Append(OBJPREFIX="dlck_ut_helper_")
    henv.Append(CPPPATH=[Dir('../../../').srcnode()])
    henv.require('argobots', 'cmocka')

    libs = [
        'vos_srv', 'gurt', 'daos_common_pmem', 'bio', 'cmocka', 'uuid', 'dtx', 'abt', 'pthread'
    ]

    srcs = [
        'dlck_test_helper.c',
        '../dlck_abt.c',
        '../dlck_args_engine.c',
        '../dlck_args_files.c',
        '../dlck_args_parse.c',
        '../dlck_engine.c',
        '../dlck_pool.c',
        '../dlck_tls.c',
        '../../../dtx/tests/srv_mock.c',
        '../../../dtx/tests/ult_mock.c',
        '../../../dtx/tests/pl_map_mock.c',
        '../../../dtx/tests/sched_mock.c',
        '../../../engine/util.c',
        '../../../mgmt/mgmt_common.c',
    ]
    henv.d_test_program('dlck_test_helper', srcs, LIBS=libs)


def build_dlck_args_ut(henv):
    """Build dlck_args_ut"""
    henv.Append(OBJPREFIX="dlck_args_ut_")
    henv.AppendUnique(LINKFLAGS=['-Wl,--wrap=argp_failure'])
    henv.require('cmocka')

    libs = [
        'gurt', 'daos_common_pmem', 'cmocka', 'uuid'
    ]

    srcs = [
        'dlck_args_ut.c',
        '../dlck_args_common.c',
        '../dlck_args_engine.c',
        '../dlck_args_files.c',
        '../dlck_args_parse.c',
        '../dlck_args.c',
    ]
    henv.d_test_program('dlck_args_ut', srcs, LIBS=libs)


def build_dlck_checker_common_ut(henv):
    """Build dlck_checker_common_ut"""
    henv.require('cmocka')

    henv.d_test_program('dlck_checker_common_ut', ['dlck_checker_common_ut.c'],
                        LIBS=['gurt', 'cmocka'])


def build_dlck_checker_main_ut(henv):
    """Build dlck_checker_main_ut"""
    henv.Append(OBJPREFIX="dlck_checker_main_ut_")
    henv.AppendUnique(LINKFLAGS=['-Wl,--wrap=ABT_mutex_create', '-Wl,--wrap=ABT_mutex_free',
                                 '-Wl,--wrap=ABT_mutex_lock', '-Wl,--wrap=ABT_mutex_unlock',
                                 '-Wl,--wrap=vfprintf', '-Wl,--wrap=__vfprintf_chk',
                                 '-Wl,--wrap=fflush', '-Wl,--wrap=d_calloc',
                                 '-Wl,--wrap=d_free'])
    henv.require('argobots', 'cmocka')

    libs = ['gurt', 'daos_common_pmem', 'cmocka', 'uuid', 'abt']

    srcs = [
        'dlck_checker_main_ut.c',
        'dlck_checker_ut_mock.c',
        '../dlck_checker.c',
    ]
    henv.d_test_program('dlck_checker_main_ut', srcs, LIBS=libs)


def build_dlck_checker_worker_ut(henv):
    """Build dlck_checker_worker_ut"""
    henv.Append(OBJPREFIX="dlck_checker_worker_ut_")
    henv.AppendUnique(LINKFLAGS=['-Wl,--wrap=fopen', '-Wl,--wrap=fclose', '-Wl,--wrap=d_asprintf2',
                                 '-Wl,--wrap=vfprintf', '-Wl,--wrap=__vfprintf_chk',
                                 '-Wl,--wrap=fflush',
                                 '-Wl,--wrap=d_calloc', '-Wl,--wrap=d_free'])
    henv.require('argobots', 'cmocka')

    libs = ['gurt', 'daos_common_pmem', 'cmocka', 'uuid', 'abt']
    srcs = [
        'dlck_checker_worker_ut.c',
        'dlck_checker_ut_mock.c',
        '../dlck_checker.c'
    ]
    henv.d_test_program('dlck_checker_worker_ut', srcs, LIBS=libs)


def scons():
    """Execute build"""
    Import('env')

    build_dlck_test_helper(env.Clone())
    build_dlck_args_ut(env.Clone())
    build_dlck_checker_common_ut(env.Clone())
    build_dlck_checker_main_ut(env.Clone())
    build_dlck_checker_worker_ut(env.Clone())


if __name__ == "SCons.Script":
    scons()
