# Copyright 2022-2024 Intel Corporation
# Copyright 2025 Google LLC
# Copyright 2025-2026 Hewlett Packard Enterprise Development LP
# All rights reserved.
#
# 'recipe' for Docker to build an image of EL 9 based
# environment for building the DAOS project.
#
# Use --target build-ci to create image with basic build environment for gcc

# Pull base image
ARG POINT_RELEASE=
ARG BASE_DISTRO=rockylinux:9$POINT_RELEASE
FROM $BASE_DISTRO AS basic
LABEL maintainer="daos@daos.groups.io"
# Needed for later use of BASE_DISTRO
ARG BASE_DISTRO

# Intermittent cache-bust. Refresh base image at least once a week.
ARG CB0

ARG REPO_FILE_URL
ARG JENKINS_URL
ARG REPOS
ARG DAOS_LAB_CA_FILE_URL

# Accept DAOS_HTTP_PROXY, DAOS_HTTPS_PROXY, and DAOS_NO_PROXY at build time
ARG DAOS_HTTP_PROXY
ARG DAOS_HTTPS_PROXY
ARG DAOS_NO_PROXY
# Propagate into the build environment
ENV http_proxy=${DAOS_HTTP_PROXY} \
    HTTP_PROXY=${DAOS_HTTP_PROXY} \
    https_proxy=${DAOS_HTTPS_PROXY} \
    HTTPS_PROXY=${DAOS_HTTPS_PROXY} \
    no_proxy=${DAOS_NO_PROXY} \
    NO_PROXY=${DAOS_NO_PROXY}
# Persist into /etc/environment for use by shells and services
RUN set -e; \
    if [ -n "$DAOS_HTTP_PROXY" ]; then \
        echo "http_proxy=$DAOS_HTTP_PROXY" >> /etc/environment; \
        echo "HTTP_PROXY=$DAOS_HTTP_PROXY" >> /etc/environment; \
    fi; \
    if [ -n "$DAOS_HTTPS_PROXY" ]; then \
        echo "https_proxy=$DAOS_HTTPS_PROXY" >> /etc/environment; \
        echo "HTTPS_PROXY=$DAOS_HTTPS_PROXY" >> /etc/environment; \
    fi; \
    if [ -n "$DAOS_NO_PROXY" ]; then \
        echo "no_proxy=$DAOS_NO_PROXY" >> /etc/environment; \
        echo "NO_PROXY=$DAOS_NO_PROXY" >> /etc/environment; \
    fi

# Setup local repo if available
RUN --mount=type=bind,src=./utils/scripts/helpers/repo-helper-el9.sh,target=/tmp/daos/repo-helper.sh \
    /tmp/daos/repo-helper.sh

# Install OS updates.
RUN dnf upgrade && \
    dnf clean all

# Setup docker image for gcc build only
FROM basic AS build-ci
RUN --mount=type=bind,source=utils/scripts/install-el9.sh,target=/tmp/daos/install.sh \
    dnf upgrade &&                                  \
    INSTALL_BUILD_CI_ONLY="true" /tmp/daos/install.sh && \
    dnf clean all

# Add DAOS user
ARG UID=1000
RUN --mount=type=bind,source=utils/scripts/helpers/daos-server-user-setup.sh,target=/tmp/daos/daos-server-user-setup.sh \
    /tmp/daos/daos-server-user-setup.sh

# Create directory for DAOS build backend storage
RUN mkdir -p /home/daos /opt/daos && \
    chown -R daos_server.daos_server /home/daos /opt/daos

# Setup a python venv so that python packages can be installed locally.
USER daos_server:daos_server
ARG PYTHON_VERSION=3.11
RUN python${PYTHON_VERSION} -m venv /home/daos/venv
ENV PATH=/home/daos/venv/bin:$PATH
ENV VIRTUAL_ENV=/home/daos/venv/

# Install latest versions of python tools.
WORKDIR /home/daos
RUN --mount=type=cache,id=uv-cache-el9,target=/home/daos/.cache/uv,mode=0777 \
    --mount=type=bind,source=requirements-build.txt,target=/tmp/daos/requirements-build.txt \
    . /home/daos/venv/bin/activate &&                              \
    pip --no-cache-dir install --upgrade pip &&                    \
    pip --no-cache-dir install -r /tmp/daos/requirements-build.txt && \
    n=0; until uv pip install --python /home/daos/venv/bin/python hatchling; do \
        n=$((n+1)); [ "$n" -ge 3 ] && exit 1; sleep $((n*10)); \
    done

# Install DAOS dependencies if available
ARG DAOS_DEPS_INSTALL=yes
RUN --mount=type=bind,source=ci/rpm/install_deps.sh,target=/tmp/daos/ci/rpm/install_deps.sh \
    --mount=type=bind,source=ci/parse_ci_envs.sh,target=/tmp/daos/ci/parse_ci_envs.sh \
    --mount=type=bind,source=utils/rpms/package_version.sh,target=/tmp/daos/utils/rpms/package_version.sh \
    --mount=type=bind,source=utils/rpms/package_info.sh,target=/tmp/daos/utils/rpms/package_info.sh \
    --mount=type=bind,source=utils/rpms/daos.spec,target=/tmp/daos/utils/rpms/daos.spec \
    [ "$DAOS_DEPS_INSTALL" != "yes" ] || \
        /tmp/daos/ci/rpm/install_deps.sh el9

# Setup docker image for build using local copy of sources.
# Include also clang and java compilers installation
# Control what to build.  By default Dockerfiles build everything to allow for
# ease-of-use for users, however in CI everything is turned off and then
# selectively enabled.  Turning off any step disables all future steps.
ARG DAOS_DEPS_BUILD=yes
ARG DAOS_KEEP_BUILD=no
ARG DAOS_TARGET_TYPE=release
ARG DAOS_PACKAGES_BUILD=yes
ARG DNF_UPGRADE_EXCLUDES=libfabric-devel,libfabric,mercury-devel,mercury,\
mercury-ucx,argobots-devel,argobots,fused-devel,isa-l-devel,libisa-l,isa-l,\
isa-l_crypto-devel,libisa-l_crypto,daos-spdk-devel,daos-spdk,libpmemobj-devel,\
libpmem,libpmem-devel,libpmemobj,\
spdk,spdk-devel,dpdk,dpdk-devel

# Now do an update to ensure software is up to date for the deps build.  If the
# src hasn't changed then this won't do anything, but if it has then we want to
# ensure that latest dependencies are used.
USER root:root
RUN [ "$DAOS_DEPS_BUILD" != "yes" ] || { \
        dnf upgrade \
            --exclude="$DNF_UPGRADE_EXCLUDES" && \
        dnf clean all; \
    }

# Build dependencies
USER daos_server:daos_server
WORKDIR /home/daos/pre
ARG DEPS_JOBS=32

RUN --mount=type=cache,id=uv-cache-el9,target=/home/daos/.cache/uv,mode=0777 \
    --mount=type=bind,source=SConstruct,target=/home/daos/pre/SConstruct \
    --mount=type=bind,source=deps,target=/home/daos/pre/deps \
    --mount=type=bind,source=site_scons/prereq_tools,target=/home/daos/pre/site_scons/prereq_tools \
    --mount=type=bind,source=site_scons/components,target=/home/daos/pre/site_scons/components \
    --mount=type=bind,source=utils/build.config,target=/home/daos/pre/utils/build.config \
    --mount=type=bind,source=utils/scripts/copy_files.sh,target=/home/daos/pre/utils/scripts/copy_files.sh \
    --mount=type=bind,source=utils/scripts/create_spdk_pkgconfig.sh,target=/home/daos/pre/utils/scripts/create_spdk_pkgconfig.sh \
    --mount=type=bind,source=ci/rpm/build_deps.sh,target=/home/daos/pre/utils/scripts/build_deps.sh \
    [ "$DAOS_DEPS_BUILD" != "yes" ] || {                                 \
        DAOS_DEPS_JOBS="$DEPS_JOBS" DAOS_TARGET_TYPE="$DAOS_TARGET_TYPE" \
        utils/scripts/build_deps.sh &&                                   \
        ([ "$DAOS_KEEP_BUILD" != "no" ] || /bin/rm -rf build *.gz);      \
    }

# Build dependencies RPMs
RUN --mount=type=bind,source=utils/rpms,target=/home/daos/pre/utils/rpms \
    --mount=type=bind,source=utils/sl/setup_local.sh,target=/home/daos/pre/utils/sl/setup_local.sh \
    --mount=type=bind,source=utils/build.config,target=/home/daos/pre/utils/build.config \
    [ "$DAOS_PACKAGES_BUILD" != "yes" ] || [ "$DAOS_DEPS_BUILD" != "yes" ] || \
    {                                                                         \
        export DISTRO="el9" &&                                                \
	    /home/daos/pre/utils/rpms/build_packages.sh deps &&                   \
        mkdir -p /home/daos/rpms/deps &&                                      \
        find . -maxdepth 1 -type f -name '*.rpm'                              \
             -exec mv -t /home/daos/rpms/deps {} + ;                          \
    }

# Force an upgrade to get any newly built RPMs, but only if CB1 is set.
ARG CB1
USER root:root
RUN [ -z "$CB1" ] || { \
        dnf upgrade    \
            --exclude="$DNF_UPGRADE_EXCLUDES" && \
        dnf clean all; \
    }

# Set a label.  This is useful for searching for DAOS images, but is also used
# in github-actions to prune elements of the dockerfile below this point.
LABEL DAOS=true
FROM build-ci AS build-local

# Control what to build.  By default Dockerfiles build everything to allow for
# ease-of-use for users, however in CI everything is turned off and then
# selectively enabled.  Turning off any step disables all future steps.
ARG COMPILER=gcc
ARG JOBS=$DEPS_JOBS
ARG DAOS_BUILD_TYPE=$DAOS_TARGET_TYPE
ARG DAOS_BUILD=$DAOS_DEPS_BUILD

# Install the rest of components if other than gcc compiler will be used for DAOS
# This is done in a separate stage to allow for a smaller image for CI building only.
USER root:root
RUN --mount=type=bind,source=utils/scripts/install-el9.sh,target=/tmp/daos/install.sh \
    [ "$COMPILER" = "gcc" ] || { \
        /tmp/daos/install.sh && \
        dnf clean all; \
    }

# Create directory for DAOS build storage
USER daos_server:daos_server
RUN mkdir -p /home/daos/daos

# Build DAOS
WORKDIR /home/daos/daos/

# We need to copy the source code into the image as we need read/write copy 
# of raft source code. Otherwise we would not be able to build it:
# make -C src/rdb/raft/ BUILDDIR=/home/daos/daos/build/release/clang/src/rdb/raft/src GCOV_CCFLAGS= tests_main
# make: Entering directory '/home/daos/daos/src/rdb/raft'
# cd ./tests && sh make-tests.sh "test_*.c" > main_test.c && cd ..
# /bin/bash: line 1: main_test.c: Permission denied
# make: *** [Makefile:40: tests/main_test.c] Error 1
# make: Leaving directory '/home/daos/daos/src/rdb/raft'
# scons: *** [build/release/clang/src/rdb/raft/src/tests_main] Error 2

COPY --chown=daos_server:daos_server src /home/daos/daos/src

RUN --mount=type=bind,source=VERSION,target=/home/daos/daos/VERSION \
    --mount=type=bind,source=LICENSE,target=/home/daos/daos/LICENSE \
    --mount=type=bind,source=ftest.sh,target=/home/daos/daos/ftest.sh \
    --mount=type=bind,source=SConstruct,target=/home/daos/daos/SConstruct \
    --mount=type=bind,source=requirements-ftest.txt,target=/home/daos/daos/requirements-ftest.txt \
    --mount=type=bind,source=.clang-format,target=/home/daos/daos/.clang-format \
    --mount=type=bind,source=site_scons,target=/home/daos/daos/site_scons \
    --mount=type=bind,source=utils/build.config,target=/home/daos/daos/utils/build.config \
    --mount=type=bind,source=utils/certs,target=/home/daos/daos/utils/certs \
    --mount=type=bind,source=utils/completion,target=/home/daos/daos/utils/completion \
    --mount=type=bind,source=utils/config,target=/home/daos/daos/utils/config \
    [ "$DAOS_BUILD" != "yes" ] || {                                     \
        scons --jobs $JOBS install PREFIX=/opt/daos COMPILER=$COMPILER  \
              BUILD_TYPE=$DAOS_BUILD_TYPE TARGET_TYPE=$DAOS_TARGET_TYPE \
              FIRMWARE_MGMT=1 USE_INSTALLED=all &&                      \
        ([ "$DAOS_KEEP_BUILD" != "no" ] || /bin/rm -rf build) &&        \
        go clean -cache &&                                              \
        cp -r utils/config/examples /opt/daos;                          \
    }

# Build DAOS RPMs
RUN --mount=type=bind,source=utils/rpms,target=/home/daos/daos/utils/rpms \
    --mount=type=bind,source=utils/sl,target=/home/daos/daos/utils/sl \
    --mount=type=bind,source=utils/systemd,target=/home/daos/daos/utils/systemd \
    --mount=type=bind,source=utils/build.config,target=/home/daos/daos/utils/build.config \
    --mount=type=bind,source=utils/rpms/build_packages.sh,target=/home/daos/daos/utils/rpms/build_packages.sh \
    [ "$DAOS_PACKAGES_BUILD" != "yes" ] || [ "$DAOS_BUILD" != "yes" ] || { \
	    export DISTRO="el9" &&                                             \
	    /home/daos/daos/utils/rpms/build_packages.sh daos &&               \
	    mkdir -p /home/daos/rpms/daos &&                                   \
        find . -maxdepth 1 -type f -name '*.rpm'                           \
             -exec mv -t /home/daos/rpms/daos {} + ;                       \
    }

# Disable Java build for now since it fails
# Build java and hadoop bindings
#WORKDIR /home/daos/daos/src/client/java
#
#ARG DAOS_JAVA_BUILD=$DAOS_BUILD
#RUN [ "$DAOS_JAVA_BUILD" != "yes" ] || {                                                      \
#        mkdir /home/daos/.m2 &&                                                               \
#        cp /home/daos/daos/utils/scripts/helpers/maven-settings.xml.in /home/daos/.m2/settings.xml &&      \
#        mvn clean install -T 1C                                                               \
#            -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn                                                   \
#            -DskipITs -Dgpg.skip -Ddaos.install.path=/opt/daos;                               \
#    }

# Remove local copy
ARG DAOS_KEEP_SRC=no
RUN [ "$DAOS_KEEP_SRC" != "no" ] || rm -rf /home/daos/daos/* /home/daos/pre/* \
        || true

# Setup docker image for Unit Tests
FROM build-local AS full
# Install the rest of components if not already installed.
# This is done in a separate stage to allow for a smaller image for CI
# and local build
USER root:root
RUN --mount=type=bind,source=utils/scripts/install-el9.sh,target=/tmp/daos/install.sh \
    /tmp/daos/install.sh && \
    dnf clean all

# Add DAOS agent users
RUN useradd --no-log-init --user-group --create-home --shell /bin/bash \
            daos_agent &&                                              \
    echo "daos_agent:daos_agent" | chpasswd

# Create directory for DAOS runtime
RUN mkdir -p /mnt/daos /var/run/daos_server /var/run/daos_agent &&     \
    chown -R daos_server.daos_server /mnt/daos /var/run/daos_server && \
    chown -R daos_agent.daos_agent /var/run/daos_agent

# Update python virtual environment for unit tests
WORKDIR /home/daos
USER daos_server:daos_server
RUN --mount=type=bind,source=requirements-utest.txt,target=/tmp/daos/requirements-utest.txt \
    pip --no-cache-dir install -r /tmp/daos/requirements-utest.txt

# Set environment variables
ENV PATH=/opt/daos/bin:$PATH
ENV FI_SOCKETS_MAX_CONN_RETRY=1
