#
# Copyright 2018-2020, Intel Corporation
#
# 'recipe' for Docker for code scanning.
#

# Pull base image
FROM fedora:latest
MAINTAINER daos-stack <daos@daos.groups.io>

# use same UID as host and default value of 1000 if not specified
ARG UID=1000

# Install Python Bandit scanner.
RUN dnf -y install bandit
