# Copyright 2018-2024 Intel Corporation
# Copyright 2025 Google LLC
# Copyright 2025-2026 Hewlett Packard Enterprise Development LP
# All rights reserved.
#
# 'recipe' for Docker to build an image of Leap based
# environment for building the DAOS project.
#
# Use --target build-ci to create image with basic build environment for gcc

# Pull base image
ARG POINT_RELEASE=
ARG BASE_DISTRO=registry.opensuse.org/opensuse/leap-dnf:15$POINT_RELEASE
FROM $BASE_DISTRO AS basic
LABEL maintainer="daos@daos.groups.io"
# Needed for later use of BASE_DISTRO
ARG BASE_DISTRO

# Intermittent cache-bust. Refresh base image at least once a week.
ARG CB0

ARG REPO_FILE_URL
ARG JENKINS_URL
ARG REPOS
ARG DAOS_LAB_CA_FILE_URL

# Accept DAOS_HTTP_PROXY, DAOS_HTTPS_PROXY, and DAOS_NO_PROXY at build time
ARG DAOS_HTTP_PROXY
ARG DAOS_HTTPS_PROXY
ARG DAOS_NO_PROXY
# Propagate into the build environment
ENV http_proxy=${DAOS_HTTP_PROXY} \
    HTTP_PROXY=${DAOS_HTTP_PROXY} \
    https_proxy=${DAOS_HTTPS_PROXY} \
    HTTPS_PROXY=${DAOS_HTTPS_PROXY} \
    no_proxy=${DAOS_NO_PROXY} \
    NO_PROXY=${DAOS_NO_PROXY}
# Persist into /etc/environment for use by shells and services
RUN set -e; \
    if [ -n "$DAOS_HTTP_PROXY" ]; then \
        echo "http_proxy=$DAOS_HTTP_PROXY" >> /etc/environment; \
        echo "HTTP_PROXY=$DAOS_HTTP_PROXY" >> /etc/environment; \
    fi; \
    if [ -n "$DAOS_HTTPS_PROXY" ]; then \
        echo "https_proxy=$DAOS_HTTPS_PROXY" >> /etc/environment; \
        echo "HTTPS_PROXY=$DAOS_HTTPS_PROXY" >> /etc/environment; \
    fi; \
    if [ -n "$DAOS_NO_PROXY" ]; then \
        echo "no_proxy=$DAOS_NO_PROXY" >> /etc/environment; \
        echo "NO_PROXY=$DAOS_NO_PROXY" >> /etc/environment; \
    fi

# Script to setup local repo if available
COPY ./utils/scripts/helpers/repo-helper-leap15.sh /tmp/repo-helper.sh

RUN chmod +x /tmp/repo-helper.sh && \
    /tmp/repo-helper.sh &&          \
    rm -f /tmp/repo-helper.sh

# Install OS updates.
RUN dnf upgrade && \
    dnf clean all

# Setup docker image for gcc build only
FROM basic AS build-ci
# Script to install basic tools and DAOS dependencies
COPY ./utils/scripts/install-leap15.sh /tmp/install.sh

# Install basic tools and DAOS dependencies
RUN dnf upgrade &&                                  \
    chmod +x /tmp/install.sh &&                     \
    INSTALL_BUILD_CI_ONLY="true" /tmp/install.sh && \
    dnf clean all

# According to https://pkgs.org/search/?q=lua-lmod, Leap 15.6 only has lua-lmod-8.7.34.
# This version has a problem with loading modules, as described in https://github.com/TACC/Lmod/issues/687.
# This affects MPI detection in scons, so DAOS cannot be built with MPI support.
# A custom source of the package is required in CI to install a valid version
# of lua-lmod and its dependencies:
# opensuse-network-cluster for lua-lmod (>=8.7.55)
# opensuse-oss for lua53, lua53-luaterm,, sqlite3-tcl, tcl
# opensuse-devel-languages-lua for lua53-luafilesystem, lua53-luaposix
ARG JENKINS_URL
RUN if [ -n "$JENKINS_URL" ]; then                                                                       \
    dnf -y remove lua-lmod;                                                                              \
    dnf -y --nogpgcheck install lua-lmod --repo '*lua*' --repo '*network-cluster*' --repo '*oss-proxy*'; \
    fi
    
# Add DAOS users
ARG UID=1000
COPY ./utils/scripts/helpers/daos-server-user-setup.sh \
     /tmp/daos-server-user-setup.sh
RUN set -e;                                    \
    chmod +x /tmp/daos-server-user-setup.sh && \
    /tmp/daos-server-user-setup.sh &&          \
    rm -f /tmp/daos-server-user-setup.sh

# Create directory for DAOS build backend storage
RUN mkdir -p /home/daos /opt/daos && \
    chown -R daos_server.daos_server /home/daos /opt/daos

# Setup a python venv so that python packages can be installed locally.
USER daos_server:daos_server
ARG PYTHON_VERSION=3.11
RUN python${PYTHON_VERSION} -m venv /home/daos/venv
ENV PATH=/home/daos/venv/bin:$PATH
ENV VIRTUAL_ENV=/home/daos/venv/

# Install latest versions of python tools.
WORKDIR /home/daos
COPY requirements-build.txt ./
RUN . /home/daos/venv/bin/activate &&                       \
    pip --no-cache-dir install --upgrade pip &&             \
    pip --no-cache-dir install -r requirements-build.txt && \
    rm -r requirements-build.txt

# Install DAOS dependencies if available
ARG DAOS_DEPS_INSTALL=yes
RUN --mount=type=bind,source=ci/rpm/install_deps.sh,target=/tmp/daos/ci/rpm/install_deps.sh \
    --mount=type=bind,source=ci/parse_ci_envs.sh,target=/tmp/daos/ci/parse_ci_envs.sh \
    --mount=type=bind,source=utils/rpms/package_version.sh,target=/tmp/daos/utils/rpms/package_version.sh \
    --mount=type=bind,source=utils/rpms/package_info.sh,target=/tmp/daos/utils/rpms/package_info.sh \
    --mount=type=bind,source=utils/rpms/daos.spec,target=/tmp/daos/utils/rpms/daos.spec \
    [ "$DAOS_DEPS_INSTALL" != "yes" ] || \
        /tmp/daos/ci/rpm/install_deps.sh suse.lp156

# Setup docker image for build using local copy of sources.
# Include also clang and java compilers installation
FROM build-ci AS build-local
# Install remaining tools and dependencies needed for internal build.
# This is done in a separate stage to allow for a smaller image for CI building only.
USER root:root
RUN /tmp/install.sh && \
    dnf clean all &&   \
    rm -f /tmp/install.sh
    
# Create directory for DAOS dependencies build storage
USER daos_server:daos_server
RUN mkdir -p /home/daos/pre/site_scons/prereq_tools \
          /home/daos/pre/site_scons/components

WORKDIR /home/daos/pre
COPY --chown=daos_server:daos_server SConstruct .
COPY --chown=daos_server:daos_server deps deps
COPY --chown=daos_server:daos_server site_scons/prereq_tools \
                                     site_scons/prereq_tools
COPY --chown=daos_server:daos_server site_scons/components site_scons/components
COPY --chown=daos_server:daos_server utils/build.config utils/
COPY --chown=daos_server:daos_server utils/scripts/copy_files.sh \
                                     utils/scripts/copy_files.sh
COPY --chown=daos_server:daos_server utils/scripts/create_spdk_pkgconfig.sh \
                                     utils/scripts/create_spdk_pkgconfig.sh

# Control what to build.  By default Dockerfiles build everything to allow for
# ease-of-use for users, however in CI everything is turned off and then
# selectively enabled.  Turning off any step disables all future steps.
ARG DAOS_DEPS_BUILD=yes
ARG DAOS_KEEP_BUILD=no
ARG DAOS_TARGET_TYPE=release
ARG DAOS_PACKAGES_BUILD=yes

# Now do an update to ensure software is up to date for the deps build.  If the
# src hasn't changed then this won't do anything, but if it has then we want to
# ensure that latest dependencies are used.
USER root:root
RUN [ "$DAOS_DEPS_BUILD" != "yes" ] || { \
        dnf upgrade                      \
            --exclude=fuse,fuse-libs,fuse-devel,libraft0,raft-devel,mercury,mercury-devel && \
        dnf clean all;                   \
    }

# Build dependencies
USER daos_server:daos_server
ARG DEPS_JOBS=1

RUN [ "$DAOS_DEPS_BUILD" != "yes" ] || {                            \
        scons --build-deps=only --jobs $DEPS_JOBS PREFIX=/opt/daos  \
              TARGET_TYPE=$DAOS_TARGET_TYPE &&                      \
        ([ "$DAOS_KEEP_BUILD" != "no" ] || /bin/rm -rf build *.gz); \
    }

COPY --chown=daos_server:daos_server utils/rpms utils/rpms
COPY --chown=daos_server:daos_server utils/sl utils/sl

# Build dependencies RPMs
RUN [ "$DAOS_PACKAGES_BUILD" != "yes" ] || [ "$DAOS_DEPS_BUILD" != "yes" ] || \
    {                                                                         \
        export DISTRO="suse.lp15${POINT_RELEASE#\.}" &&                       \
        utils/rpms/build_packages.sh deps &&                                  \
        mkdir -p /home/daos/rpms/deps &&                                      \
        mv *.rpm /home/daos/rpms/deps;                                        \
    }

    # force an upgrade to get any newly built RPMs, but only if CB1 is set.
ARG CB1
USER root:root
RUN [ -z "$CB1" ] || { \
        dnf upgrade    \
            --exclude=fuse,fuse-libs,fuse-devel,libraft0,raft-devel,mercury,mercury-devel && \
        dnf clean all; \
    }

# Set a label.  This is useful for searching for DAOS images, but is also used
# in github-actions to prune elements of the dockerfile below this point.
LABEL DAOS=true

# Create directory for DAOS dependencies build storage
USER daos_server:daos_server
RUN mkdir -p /home/daos/daos
WORKDIR /home/daos/daos/
COPY --chown=daos_server:daos_server VERSION LICENSE ftest.sh SConstruct \
                                     requirements-ftest.txt .clang-format ./
COPY --chown=daos_server:daos_server site_scons site_scons
COPY --chown=daos_server:daos_server src src
COPY --chown=daos_server:daos_server utils/build.config utils/
COPY --chown=daos_server:daos_server utils/config utils/config
COPY --chown=daos_server:daos_server utils/certs utils/certs
COPY --chown=daos_server:daos_server utils/completion utils/completion

# select compiler to use
ARG COMPILER=gcc
ARG JOBS=$DEPS_JOBS
ARG DAOS_BUILD_TYPE=$DAOS_TARGET_TYPE
ARG DAOS_BUILD=$DAOS_DEPS_BUILD

# Build DAOS
RUN [ "$DAOS_BUILD" != "yes" ] || {                                     \
        scons --jobs $JOBS install PREFIX=/opt/daos COMPILER=$COMPILER  \
              BUILD_TYPE=$DAOS_BUILD_TYPE TARGET_TYPE=$DAOS_TARGET_TYPE \
              FIRMWARE_MGMT=1 &&                                        \
        ([ "$DAOS_KEEP_BUILD" != "no" ] || /bin/rm -rf build) &&        \
        go clean -cache &&                                              \
        cp -r utils/config/examples /opt/daos;                          \
    }

COPY --chown=daos_server:daos_server utils utils
COPY --chown=daos_server:daos_server utils/rpms/daos.spec daos.spec

# Build DAOS RPMs
RUN [ "$DAOS_PACKAGES_BUILD" != "yes" ] || [ "$DAOS_BUILD" != "yes" ] || { \
	    export DISTRO="suse.lp15${POINT_RELEASE#\.}" &&                    \
	    utils/rpms/build_packages.sh daos &&                               \
	    mkdir -p /home/daos/rpms/daos &&                                   \
	    mv *.rpm /home/daos/rpms/daos;                                     \
    }

# Build java and hadoop bindings
WORKDIR /home/daos/daos/src/client/java

ARG DAOS_JAVA_BUILD=$DAOS_BUILD
RUN [ "$DAOS_JAVA_BUILD" != "yes" ] || {                               \
        mkdir /home/daos/.m2 &&                                        \
        cp /home/daos/daos/utils/scripts/helpers/maven-settings.xml.in \ 
           /home/daos/.m2/settings.xml &&                              \
        mvn clean install -ntp -T 1C -DskipITs -Dgpg.skip              \
            -Ddaos.install.path=/opt/daos;                             \
    }

# Remove local copy
ARG DAOS_KEEP_SRC=no
RUN [ "$DAOS_KEEP_SRC" != "no" ] || rm -rf /home/daos/daos /home/daos/pre

# Setup docker image for Unit Tests
FROM build-local AS full

# Add DAOS agent users
USER root:root
RUN useradd --no-log-init --user-group --create-home --shell /bin/bash \
            daos_agent &&                                              \
    echo "daos_agent:daos_agent" | chpasswd

# Create directory for DAOS runtime
RUN mkdir -p /mnt/daos /var/run/daos_server /var/run/daos_agent &&     \
    chown -R daos_server.daos_server /mnt/daos /var/run/daos_server && \
    chown -R daos_agent.daos_agent /var/run/daos_agent

# Update python virtual environment for unit tests
WORKDIR /home/daos
USER daos_server:daos_server
COPY requirements-utest.txt ./
RUN pip --no-cache-dir install -r requirements-utest.txt && \
    rm -f requirements-utest.txt

# Set environment variables
ENV PATH=/opt/daos/bin:$PATH
ENV FI_SOCKETS_MAX_CONN_RETRY=1
