#
# Copyright 2019, Intel Corporation
#
# 'recipe' for Docker to build an Debian package
#
# Pull base image
FROM ubuntu:18.10
Maintainer John.E.Malmberg <John.E.Malmberg@intel.com>

# Install basic tools
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
            autoconf bash curl debhelper dh-make dpkg-dev doxygen gcc \
            git git-buildpackage locales make patch rpm wget

# libfabric
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
            libibverbs-dev libpsm-infinipath1-dev librdmacm-dev \
            libpsm2-dev

# Uncomment this CACHEBUST line if testing PRs for dependent components.
# It should be commented out before the merge to master
#ARG CACHEBUST=1

ARG JENKINS_URL=""
ENV JENKINS_PATH="${JENKINS_URL}/job/daos-stack/job"
ENV JENKINS_ART="lastSuccessfulBuild/artifact/artifacts"

ARG OFIBRANCH="master"
ENV OFI_ART=\
"${JENKINS_PATH}/libfabric/job/${OFIBRANCH}/${JENKINS_ART}/ubuntu18.10"

# Mercury
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
            cmake libboost-dev libevent-dev pkg-config

RUN curl -sS -f -L -O ${OFI_ART}/libfabric1_1.8.0-1_amd64.deb; \
    curl -sS -f -L -O ${OFI_ART}/libfabric-dev_1.8.0-1_amd64.deb; \
    apt-get install -y ./libfabric*_amd64.deb

# CaRT

ARG MERBRANCH="master"
ENV MER_ART=\
"${JENKINS_PATH}/mercury/job/${MERBRANCH}/${JENKINS_ART}/ubuntu18.10"

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
            dh-python libcmocka-dev libhwloc-dev libopenmpi-dev libpmix-dev \
            libssl-dev libyaml-dev scons uuid-dev openmpi-bin; \
    find /usr -name 'libpmix.so*'; \
    rm /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so; \
    ln -s /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so.2 \
      /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so


RUN curl -sS -f -L -O ${MER_ART}/libmercury1_1.0.1-8_amd64.deb; \
    curl -sS -f -L -O ${MER_ART}/libmercury-dev_1.0.1-8_amd64.deb; \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      ./libmercury*_amd64.deb

# Temporarily needed until cart dependencies fixed

ARG OPABRANCH="master"
ENV OPA_ART=\
"${JENKINS_PATH}/openpa/job/${OPABRANCH}/${JENKINS_ART}/ubuntu18.04"

RUN curl -sS -f -L -O ${OPA_ART}/libopa1_1.0.4-1_amd64.deb; \
    curl -sS -f -L -O ${OPA_ART}/libopa-dev_1.0.4-1_amd64.deb; \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      ./libopa*_amd64.deb


# force an upgrade to get any newly built packages
ARG CACHEBUST=1
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y; \
    apt-get autoremove -y
