# Copyright 2025 Hewlett Packard Enterprise Development LP
# All rights reserved.
#
# 'recipe' for Docker to build an image of EL 8 based
# environment for building the DAOS project.
#

# Pull base image
ARG POINT_RELEASE=
ARG BASE_DISTRO=rockylinux/rockylinux:8$POINT_RELEASE
FROM $BASE_DISTRO AS basic
LABEL maintainer="daos@daos.groups.io"
# Needed for later use of BASE_DISTRO
ARG BASE_DISTRO

# Intermittent cache-bust.  Used to reduce load on the actual CB1 later.
ARG CB0

ARG REPO_FILE_URL
ARG JENKINS_URL
ARG REPOS
ARG DAOS_LAB_CA_FILE_URL
# script to install OS updates basic tools and daos dependencies
COPY ./utils/scripts/install-el8.sh /tmp/install.sh
# script to setup local repo if available
COPY ./utils/scripts/helpers/repo-helper-el8.sh /tmp/repo-helper.sh

RUN chmod +x /tmp/repo-helper.sh /tmp/install.sh && \
    /tmp/repo-helper.sh &&                          \
    rm -f /tmp/repo-helper.sh

FROM basic
# Install OS updates and package.  Include basic tools and daos dependencies
# The proxy variables are currently needed for the combination of running
# with a local repository, yet needing a proxy to reach outside repositories.
# This needs to be moved to a shell script like above in the future to
# properly only remove the proxy variables only when they need to be removed
RUN if [ -n "$REPO_FILE_URL" ]; then direct="${REPO_FILE_URL##*//}; "\
        direct="${direct%%/*}"; export no_proxy="${direct}"; fi; \
    dnf upgrade &&        \
    /tmp/install.sh &&    \
    dnf clean all &&      \
    rm -f /tmp/install.sh

RUN apt-get -qq update
RUN apt-get -qqy install python3.11
ARG JENKINS_URL

# Setup a python venv so that python packages can be installed locally.
RUN python3.11 -m venv /home/daos/venv
ENV PATH=/home/daos/venv/bin:$PATH
ENV VIRTUAL_ENV=/home/daos/venv/

# Install latest versions of python tools.
WORKDIR /home/daos
COPY requirements-code-coverage.txt ./
RUN python3 -m pip --no-cache-dir install --upgrade pip && \
    python3 -m pip --no-cache-dir install -r requirements-code-coverage.txt

ARG CB1
