#
# Copyright 2018, Intel Corporation
#
# 'recipe' for Docker to build an image of Ubuntu-based
# environment for building the DAOS project.
#

# Pull base image
FROM ubuntu:16.04
MAINTAINER Johann Lombardi <johann.lombardi@intel.com>

# Update distribution
RUN apt-get update

# Install basic tools
RUN apt-get install -y git gcc golang make cmake libtool-bin scons autoconf
RUN apt-get install -y libboost-dev uuid-dev libssl-dev libevent-dev libltdl-dev
RUN apt-get install -y librdmacm-dev libcmocka0 libcmocka-dev
RUN apt-get install -y curl doxygen pandoc flex patch

# Dependencies

# Add DAOS user
ENV USER daos
ENV PASSWD daos
RUN useradd -u 1000 -ms /bin/bash $USER
RUN echo "$USER:$PASSWD" | chpasswd

# Create directory for DAOS backend storage
RUN mkdir /mnt/daos
RUN chown daos.daos /mnt/daos

# Switch to new user
USER $USER
WORKDIR /home/$USER

# Fetch DAOS code
RUN git clone https://github.com/daos-stack/daos.git
WORKDIR /home/$USER/daos

# Build DAOS & dependencies
RUN git submodule init && git submodule update
RUN scons --build-deps=yes USE_INSTALLED=all install

# Set environment variables
ENV PATH=/home/daos/daos/install/bin:$PATH
ENV LD_LIBRARY_PATH=/home/daos/daos/install/lib:/home/daos/daos/install/lib/daos_srv:$LD_LIBRARY_PATH
ENV CPATH=/home/daos/daos/install/include:$CPATH
ENV CCI_CONFIG=/home/daos/daos/install/etc/cci.ini
ENV ABT_ENV_MAX_NUM_XSTREAMS=100
ENV ABT_MAX_NUM_XSTREAMS=100
ENV CRT_PHY_ADDR_STR="ofi+sockets"
ENV OFI_INTERFACE=eth0
