#
# Copyright 2019, Intel Corporation
#
# 'recipe' for Docker to build an Debian package
#
# Pull base image
FROM ubuntu:18.04
Maintainer John.E.Malmberg <John.E.Malmberg@intel.com>

# Install basic tools
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
            autoconf bash curl debhelper dh-make dpkg-dev doxygen gcc \
            git git-buildpackage locales make patch rpm wget

# libfabric
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
            libibverbs-dev libpsm-infinipath1-dev librdmacm-dev

ENV UBUNTU_URL="https://launchpad.net/ubuntu/+archive/primary/+files"
RUN curl -sS -f -L -O ${UBUNTU_URL}/libpsm2-2_10.3.58-1_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/libpsm2-dev_10.3.58-1_amd64.deb; \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ./libpsm2-2_10.3.58-1_amd64.deb ./libpsm2-dev_10.3.58-1_amd64.deb

ARG JENKINS_URL=""
ENV JENKINS_PATH="${JENKINS_URL}/job/daos-stack/job"
ENV JENKINS_ART="lastSuccessfulBuild/artifact/artifacts"

# Uncomment this CACHEBUST line if testing PRs for dependent components.
# It should be commented out before the merge to master
#ARG CACHEBUST=1

ARG OFIBRANCH="master"
ENV OFI_ART=\
"${JENKINS_PATH}/libfabric/job/${OFIBRANCH}/${JENKINS_ART}/ubuntu18.04"

# Mercury
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
            cmake libboost-dev libevent-dev pkg-config

RUN curl -sS -f -L -O ${OFI_ART}/libfabric1_1.8.0-1_amd64.deb; \
    curl -sS -f -L -O ${OFI_ART}/libfabric-dev_1.8.0-1_amd64.deb; \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      ./libfabric1_1.8.0-1_amd64.deb ./libfabric-dev_1.8.0-1_amd64.deb

# CaRT

ARG MERBRANCH="master"
ENV MER_ART=\
"${JENKINS_PATH}/mercury/job/${MERBRANCH}/${JENKINS_ART}/ubuntu18.04"

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
            dh-python libcmocka-dev \
            libssl-dev libyaml-dev scons uuid-dev

RUN curl -sS -f -L -O ${UBUNTU_URL}/libopenmpi-dev_3.1.2-6_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/libopenmpi3_3.1.2-6_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/openmpi-common_3.1.2-6_all.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/openmpi-bin_3.1.2-6_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/libc6_2.28-0ubuntu1_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/libc6-dev_2.28-0ubuntu1_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/libc-dev-bin_2.28-0ubuntu1_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/libc-bin_2.28-0ubuntu1_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/libhwloc5_1.11.10-3_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/libhwloc-dev_1.11.10-3_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/libhwloc-plugins_1.11.10-3_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/libpmix2_3.0.1-2_amd64.deb; \
    curl -sS -f -L -O ${UBUNTU_URL}/libpmix-dev_3.0.1-2_amd64.deb; \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      ./libpmix2_3.0.1-2_amd64.deb ./libpmix-dev_3.0.1-2_amd64.deb \
      ./libhwloc5_1.11.10-3_amd64.deb ./libhwloc-dev_1.11.10-3_amd64.deb \
      ./libhwloc-plugins_1.11.10-3_amd64.deb \
      ./libc6_2.28-0ubuntu1_amd64.deb ./libc6-dev_2.28-0ubuntu1_amd64.deb \
      ./libc-dev-bin_2.28-0ubuntu1_amd64.deb \
      ./libc-bin_2.28-0ubuntu1_amd64.deb \
      ./libopenmpi-dev_3.1.2-6_amd64.deb ./libopenmpi3_3.1.2-6_amd64.deb \
      ./openmpi-common_3.1.2-6_all.deb ./openmpi-bin_3.1.2-6_amd64.deb; \
    find /usr -name 'libpmix.so*'; \
    rm -f /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so; \
    ln -s /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so.2 \
      /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so

RUN curl -sS -f -L -O ${MER_ART}/libmercury1_1.0.1-9_amd64.deb; \
    curl -sS -f -L -O ${MER_ART}/libmercury-dev_1.0.1-9_amd64.deb; \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      ./libmercury*_amd64.deb

# Temporarily needed until cart dependencies fixed

ARG OPABRANCH="master"
ENV OPA_ART=\
"${JENKINS_PATH}/openpa/job/${OPABRANCH}/${JENKINS_ART}/ubuntu18.04"
RUN curl -sS -f -L -O ${OPA_ART}/libopa1_1.0.4-1_amd64.deb; \
    curl -sS -f -L -O ${OPA_ART}/libopa-dev_1.0.4-1_amd64.deb; \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      ./libopa*_amd64.deb

# force an upgrade to get any newly built packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y; \
    apt-get autoremove -y

