# Copyright (C) 2018-2021 Intel Corporation
# All rights reserved.
#
# 'recipe' for Docker to build an image of centOS 8
# environment for building the DAOS project.

# Pull base image
FROM centos:8.3.2011
LABEL maintainer="daos@daos.groups.io"

# Build arguments can be set via --build-arg
# use same UID as host and default value of 1000 if not specified
ARG UID=1000

# Install basic tools to build DAOS
RUN yum clean all && yum -y install epel-release dnf-plugins-core && \
    dnf config-manager --set-enabled powertools && \
    yum -y upgrade && \
    yum -y install \
        boost-python3-devel \
        clang-analyzer \
        cmake \
        CUnit-devel \
        doxygen \
        e2fsprogs \
        file \
        flex \
        fuse3-devel \
        gcc \
        gcc-c++ \
        git \
        golang \
        graphviz \
        hwloc-devel \
        ipmctl \
        java-1.8.0-openjdk \
        json-c-devel \
        libaio-devel \
        libcmocka-devel \
        libevent-devel \
        libipmctl-devel \
        libiscsi-devel \
        libtool \
        libtool-ltdl-devel \
        libunwind-devel \
        libuuid-devel \
        libyaml-devel \
        Lmod \
        lz4-devel \
        make \
        man \
        maven \
        nasm \
        ndctl \
        numactl-devel \
        openmpi-devel \
        openssl-devel \
        pandoc \
        patch \
        patchelf \
        pciutils \
        python3-pip \
        python3-Cython \
        python3-devel \
        python3-distro \
        python3-jira \
        python3-numpy \
        python3-paramiko \
        python3-pylint \
        python3-requests \
        python3-tabulate \
        python3-pyxattr \
        python3-scons \
        readline-devel \
        sg3_utils \
        valgrind-devel \
        yasm && \
    yum clean all

ARG UID=1000

# Add DAOS users
RUN useradd --uid $UID --user-group --create-home --shell /bin/bash --home /home/daos daos_server
RUN echo "daos_server:daos_server" | chpasswd
RUN useradd --user-group --create-home --shell /bin/bash daos_agent
RUN echo "daos_agent:daos_agent" | chpasswd

# Create directory for DAOS backend storage
RUN mkdir -p /opt/daos && chown -R daos_server.daos_server /opt/daos
RUN mkdir /mnt/daos && chown daos_server.daos_server /mnt/daos
RUN mkdir /var/run/daos_server && chown daos_server.daos_server /var/run/daos_server
RUN mkdir /var/run/daos_agent && chown daos_agent.daos_agent /var/run/daos_agent

# Control what to build.  By default Dockerfiles build everything to allow for
# ease-of-use for users, however in CI everything is turned off and then
# selectively enabled.  Turning off any step disables all future steps.
ARG DAOS_DEPS_BUILD=yes
ARG DAOS_BUILD=$DAOS_DEPS_BUILD
ARG DAOS_JAVA_BUILD=$DAOS_BUILD
# Legacy, NOBUILD should be set to any string to disable all three.
ARG NOBUILD=no

# select compiler to use
ARG COMPILER=gcc

# The COPY command has a --chown option but it's not well supported so copy as
# root then run a chown command which is frustrating as the copy can take a few
# seconds.
WORKDIR /home/daos/pre
COPY SConstruct .
COPY utils/sl utils/sl
COPY utils/build.config utils/
RUN chown -R daos_server.daos_server /home/daos
USER daos_server:daos_server
RUN ln -s utils/sl site_scons

RUN [ "$DAOS_DEPS_BUILD" != "yes" ] || \
    (scons-3 --build-deps=yes install PREFIX=/opt/daos --deps-only && \
    /bin/rm -rf build *.gz)

WORKDIR /home/daos/daos/
COPY VERSION LICENSE ftest.sh SConstruct ./
COPY utils utils
COPY src src
USER root:root
RUN chown -R daos_server.daos_server /home/daos
USER daos_server:daos_server
RUN ln -s utils/sl site_scons

# Build DAOS
RUN [ "$DAOS_BUILD" != "yes" ] || \
    (scons-3 -j 4 install PREFIX=/opt/daos COMPILER=$COMPILER && \
    /bin/rm -rf build && \
    cp -r utils/config/examples /opt/daos)

# Set environment variables
ENV LD_LIBRARY_PATH=/opt/daos/lib:/opt/daos/lib64:$LD_LIBRARY_PATH
ENV PATH=/opt/daos/bin:$PATH
ENV FI_SOCKETS_MAX_CONN_RETRY=1

# Build java and hadoop bindings
WORKDIR /home/daos/daos/src/client/java
# Set maven repo mirror
RUN mkdir -p /home/daos/.m2
RUN echo -e "<settings>\n\
        <mirrors>\n\
                <mirror>\n\
                        <id>google-maven-central</id>\n\
                        <name>GCS Maven Central mirror</name>\n\
                        <url>https://maven-central.storage-download.googleapis.com/maven2/</url>\n\
                        <mirrorOf>central</mirrorOf>\n\
                </mirror>\n\
        </mirrors>\n\
</settings>" > /home/daos/.m2/settings.xml

RUN [ "$DAOS_JAVA_BUILD" != "yes" ] || \
    mvn clean install -T 1C -DskipITs -Dgpg.skip -Ddaos.install.path=/opt/daos
WORKDIR /home/daos

# Remove local copy
RUN rm -rf /home/daos/*