#!python

Import('denv')

denv.Append(CPPPATH = ['#/src/common/dtp/tests'])

libraries = ['cart', 'pthread', 'crypto', 'uuid', 'mcl']

# a simple example to use dtp_xxx APIs
denv.Program('dtp_echo_cli', 'dtp_echo_cli.c', LIBS=libraries)
denv.Program('dtp_echo_srv', 'dtp_echo_srv.c', LIBS=libraries)
