#!python

Import('denv')

libraries  = ['vos', 'daos_common', 'daos_tests', 'crt_util', 'crt']
libraries += ['uuid', 'pthread', 'pmemobj', 'cmocka', 'gomp']

denv.Append(CPPPATH = ['#/src/vos/tests/'])
vos_test_src=['vos_tests.c', 'vts_io.c', 'vts_pool.c', 'vts_container.c',
              'vts_common.c', 'vts_purge.c']
vos_tests = denv.Program('vos_tests', vos_test_src, LIBS = libraries)
evt_ctl = denv.Program('evt_ctl', 'evt_ctl.c', LIBS = libraries)

denv.Install('$PREFIX/bin/', vos_tests)
denv.Install('$PREFIX/bin/', evt_ctl)
