#!python

Import('env')

env.Program('hdr_build', 'hdr_build.c')
env.Program('vos_pool_tests','vos_pool_tests.c', LIBS=['$LIBS', 'libvos', 'libuuid',
                                                       'libpthread',
                                                       'libdaos_common',
						       'daos_transport'])
env.Program('vos_container_tests','vos_container_tests.c',
            LIBS=['$LIBS', 'libvos', 'libuuid','libpthread',
                  'libdaos_common','libgomp','daos_transport'])

env.Program('vos_chash_table_test','vos_chashtable_test.c', CCFLAGS='-fopenmp',
            LIBS=['$LIBS', 'libvos', 'libuuid','libdaos_common','libpthread',
                  'libgomp', 'daos_transport'])
