# Copyright (c) 2018 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
"""SConscript to test Preprocess too"""

def scons():
    """Run Preprocess tool"""
    Import('env')

    envs = [env, env.Clone(OBJPREFIX="f"), env.Clone(OBJSUFFIX="_y.o"),
            env.Clone(OBJPREFIX="x", OBJSUFFIX="_z.o"),
            env.Clone(SHOBJPREFIX="z"), env.Clone(SHOBJSUFFIX="_f.os"),
            env.Clone(OBJPREFIX="x", SHOBJPREFIX="z")]

    for denv in envs:
        # pylint: disable=no-member
        buildfoo = denv.Preprocess("foo.c")
        # pylint: enable=no-member
        denv.Program(buildfoo)

if __name__ == 'SCons.Script':
    scons()
