#!/bin/sh

# shellcheck disable=SC2046,SC2035
codespell -w --ignore-words-list nd,uint,ths,ba,creat,te,cas,mapp,pres,crashers,dout,tre,reord,mimick,cloneable,keypair,bject,tread,cancelled --builtin clear,rare,informal,names,en-GB_to_en-US --skip *.png,*.PNG,*.pyc,src/rdb/raft/*,src/control/vendor/*,RSA.golden $(git ls-tree --full-tree --name-only HEAD)

def_ignore="SPLIT_STRING,SSCANF_TO_KSTRTO,PREFER_KERNEL_TYPES"
def_ignore+=",USE_NEGATIVE_ERRNO,CAMELCASE,STATIC_CONST_CHAR_ARRAY"
def_ignore+=",COMPARISON_TO_NULL,COMPLEX_MACRO,BIT_MACRO"

CP=../code_review/checkpatch.pl
if [ ! -x $CP ]
then
	CP=./code_review/checkpatch.pl
fi

if [ -x $CP ]
then
    for FILE in $(git ls-tree --full-tree --name-only HEAD -r src | grep -v -e src/control/vendor -e .go\$ -e pb-c -e debug_setup.h)
    do
        $CP --quiet --no-tree -file --show-types --no-summary --ignore "$def_ignore" --strict "$FILE" --fix-inplace
    done
fi

./ci/check_d_macro_calls.py | patch -p1
./ci/check_d_macro_calls.py | patch -p1
./ci/check_d_macro_calls.py | patch -p1

exit 0
