"""Build container tests"""

def scons():
    """Execute build"""
    Import('denv')

    #Import('prereqs build_program')
    #libraries = ['daos_common', 'gurt', 'cart', 'daos']
    #libraries += ['uuid', 'mpi']
    #libraries += ['cmocka']

    #prereqs.require(denv, 'ompi')
    #
    #build_program(denv, 'dsm_test', Glob('*.c'), LIBS=libraries)

if __name__ == "SCons.Script":
    scons()
