"""Build container tests"""

def scons():
    """Execute build"""
    Import('denv')

    denv.Append(CPPPATH=['#/src/dsm', '#/src/server'])

    #Import('prereqs')
    #libraries = ['daos_common', 'gurt', 'cart', 'daos']
    #libraries += ['uuid', 'mpi']
    #libraries += ['cmocka']

    #prereqs.require(denv, 'ompi')
    #
    #denv.Program('dsm_test', Glob('*.c'), LIBS=libraries)

if __name__ == "SCons.Script":
    scons()
