#!python

Import('denv', 'PREREQS')

denv.Append(CPPPATH = ['#/src/dsm', '#/src/server'])

libraries = ['daos_common', 'gurt', 'cart', 'daos']
libraries += ['uuid', 'mpi']
libraries += ['cmocka']

#PREREQS.require(denv, 'ompi')
#
#denv.Program('dsm_test', Glob('*.c'), LIBS = libraries)
