// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParams) Reset()         { *m = EmptyParams{} }
func (m *EmptyParams) String() string { return proto.CompactTextString(m) }
func (*EmptyParams) ProtoMessage()    {}
func (*EmptyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_srv_df659f08190eb06d, []int{0}
}
func (m *EmptyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParams.Unmarshal(m, b)
}
func (m *EmptyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParams.Marshal(b, m, deterministic)
}
func (dst *EmptyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParams.Merge(dst, src)
}
func (m *EmptyParams) XXX_Size() int {
	return xxx_messageInfo_EmptyParams.Size(m)
}
func (m *EmptyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParams.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParams proto.InternalMessageInfo

type FeatureName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureName) Reset()         { *m = FeatureName{} }
func (m *FeatureName) String() string { return proto.CompactTextString(m) }
func (*FeatureName) ProtoMessage()    {}
func (*FeatureName) Descriptor() ([]byte, []int) {
	return fileDescriptor_srv_df659f08190eb06d, []int{1}
}
func (m *FeatureName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureName.Unmarshal(m, b)
}
func (m *FeatureName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureName.Marshal(b, m, deterministic)
}
func (dst *FeatureName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureName.Merge(dst, src)
}
func (m *FeatureName) XXX_Size() int {
	return xxx_messageInfo_FeatureName.Size(m)
}
func (m *FeatureName) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureName.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureName proto.InternalMessageInfo

func (m *FeatureName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Category struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_srv_df659f08190eb06d, []int{2}
}
func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (dst *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(dst, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

// Feature represents a management task that can be performed by server.
type Feature struct {
	// The category of capabilities this feature belongs to.
	Category *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	// The name of the feature.
	Fname *FeatureName `protobuf:"bytes,2,opt,name=fname,proto3" json:"fname,omitempty"`
	// The description of the feature.
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_srv_df659f08190eb06d, []int{3}
}
func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (dst *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(dst, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Feature) GetFname() *FeatureName {
	if m != nil {
		return m.Fname
	}
	return nil
}

func (m *Feature) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// NvmeNamespace represent NVMe namespaces available on controller.
type NvmeNamespace struct {
	// namespace id
	Id int32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// device capacity in GBytes
	Capacity             int32    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NvmeNamespace) Reset()         { *m = NvmeNamespace{} }
func (m *NvmeNamespace) String() string { return proto.CompactTextString(m) }
func (*NvmeNamespace) ProtoMessage()    {}
func (*NvmeNamespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_srv_df659f08190eb06d, []int{4}
}
func (m *NvmeNamespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NvmeNamespace.Unmarshal(m, b)
}
func (m *NvmeNamespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NvmeNamespace.Marshal(b, m, deterministic)
}
func (dst *NvmeNamespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NvmeNamespace.Merge(dst, src)
}
func (m *NvmeNamespace) XXX_Size() int {
	return xxx_messageInfo_NvmeNamespace.Size(m)
}
func (m *NvmeNamespace) XXX_DiscardUnknown() {
	xxx_messageInfo_NvmeNamespace.DiscardUnknown(m)
}

var xxx_messageInfo_NvmeNamespace proto.InternalMessageInfo

func (m *NvmeNamespace) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NvmeNamespace) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

// NvmeController represents an NVMe Controller.
type NvmeController struct {
	// The id of the controller.
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The model name of the controller.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// The serial number of the controller.
	Serial string `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	// The pci address of the controller.
	Pciaddr string `protobuf:"bytes,4,opt,name=pciaddr,proto3" json:"pciaddr,omitempty"`
	// The firmware revision of the controller.
	Fwrev string `protobuf:"bytes,5,opt,name=fwrev,proto3" json:"fwrev,omitempty"`
	// NvmeNamespaces created on this controller.
	Namespace            []*NvmeNamespace `protobuf:"bytes,6,rep,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NvmeController) Reset()         { *m = NvmeController{} }
func (m *NvmeController) String() string { return proto.CompactTextString(m) }
func (*NvmeController) ProtoMessage()    {}
func (*NvmeController) Descriptor() ([]byte, []int) {
	return fileDescriptor_srv_df659f08190eb06d, []int{5}
}
func (m *NvmeController) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NvmeController.Unmarshal(m, b)
}
func (m *NvmeController) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NvmeController.Marshal(b, m, deterministic)
}
func (dst *NvmeController) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NvmeController.Merge(dst, src)
}
func (m *NvmeController) XXX_Size() int {
	return xxx_messageInfo_NvmeController.Size(m)
}
func (m *NvmeController) XXX_DiscardUnknown() {
	xxx_messageInfo_NvmeController.DiscardUnknown(m)
}

var xxx_messageInfo_NvmeController proto.InternalMessageInfo

func (m *NvmeController) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NvmeController) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *NvmeController) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *NvmeController) GetPciaddr() string {
	if m != nil {
		return m.Pciaddr
	}
	return ""
}

func (m *NvmeController) GetFwrev() string {
	if m != nil {
		return m.Fwrev
	}
	return ""
}

func (m *NvmeController) GetNamespace() []*NvmeNamespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type UpdateNvmeCtrlrParams struct {
	Ctrlr *NvmeController `protobuf:"bytes,1,opt,name=ctrlr,proto3" json:"ctrlr,omitempty"`
	// Filesystem path containing firmware image
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Firmware slot (register) to update
	Slot                 int32    `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNvmeCtrlrParams) Reset()         { *m = UpdateNvmeCtrlrParams{} }
func (m *UpdateNvmeCtrlrParams) String() string { return proto.CompactTextString(m) }
func (*UpdateNvmeCtrlrParams) ProtoMessage()    {}
func (*UpdateNvmeCtrlrParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_srv_df659f08190eb06d, []int{6}
}
func (m *UpdateNvmeCtrlrParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNvmeCtrlrParams.Unmarshal(m, b)
}
func (m *UpdateNvmeCtrlrParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNvmeCtrlrParams.Marshal(b, m, deterministic)
}
func (dst *UpdateNvmeCtrlrParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNvmeCtrlrParams.Merge(dst, src)
}
func (m *UpdateNvmeCtrlrParams) XXX_Size() int {
	return xxx_messageInfo_UpdateNvmeCtrlrParams.Size(m)
}
func (m *UpdateNvmeCtrlrParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNvmeCtrlrParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNvmeCtrlrParams proto.InternalMessageInfo

func (m *UpdateNvmeCtrlrParams) GetCtrlr() *NvmeController {
	if m != nil {
		return m.Ctrlr
	}
	return nil
}

func (m *UpdateNvmeCtrlrParams) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *UpdateNvmeCtrlrParams) GetSlot() int32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

type FioConfigPath struct {
	// Filesystem path containing fio job configuration
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FioConfigPath) Reset()         { *m = FioConfigPath{} }
func (m *FioConfigPath) String() string { return proto.CompactTextString(m) }
func (*FioConfigPath) ProtoMessage()    {}
func (*FioConfigPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_srv_df659f08190eb06d, []int{7}
}
func (m *FioConfigPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FioConfigPath.Unmarshal(m, b)
}
func (m *FioConfigPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FioConfigPath.Marshal(b, m, deterministic)
}
func (dst *FioConfigPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FioConfigPath.Merge(dst, src)
}
func (m *FioConfigPath) XXX_Size() int {
	return xxx_messageInfo_FioConfigPath.Size(m)
}
func (m *FioConfigPath) XXX_DiscardUnknown() {
	xxx_messageInfo_FioConfigPath.DiscardUnknown(m)
}

var xxx_messageInfo_FioConfigPath proto.InternalMessageInfo

func (m *FioConfigPath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type BurnInNvmeParams struct {
	Ctrlrid              int32          `protobuf:"varint,1,opt,name=ctrlrid,proto3" json:"ctrlrid,omitempty"`
	Path                 *FioConfigPath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BurnInNvmeParams) Reset()         { *m = BurnInNvmeParams{} }
func (m *BurnInNvmeParams) String() string { return proto.CompactTextString(m) }
func (*BurnInNvmeParams) ProtoMessage()    {}
func (*BurnInNvmeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_srv_df659f08190eb06d, []int{8}
}
func (m *BurnInNvmeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurnInNvmeParams.Unmarshal(m, b)
}
func (m *BurnInNvmeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurnInNvmeParams.Marshal(b, m, deterministic)
}
func (dst *BurnInNvmeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurnInNvmeParams.Merge(dst, src)
}
func (m *BurnInNvmeParams) XXX_Size() int {
	return xxx_messageInfo_BurnInNvmeParams.Size(m)
}
func (m *BurnInNvmeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_BurnInNvmeParams.DiscardUnknown(m)
}

var xxx_messageInfo_BurnInNvmeParams proto.InternalMessageInfo

func (m *BurnInNvmeParams) GetCtrlrid() int32 {
	if m != nil {
		return m.Ctrlrid
	}
	return 0
}

func (m *BurnInNvmeParams) GetPath() *FioConfigPath {
	if m != nil {
		return m.Path
	}
	return nil
}

type BurnInNvmeReport struct {
	// Report from running burn-in reported by fio
	Report               string   `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BurnInNvmeReport) Reset()         { *m = BurnInNvmeReport{} }
func (m *BurnInNvmeReport) String() string { return proto.CompactTextString(m) }
func (*BurnInNvmeReport) ProtoMessage()    {}
func (*BurnInNvmeReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_srv_df659f08190eb06d, []int{9}
}
func (m *BurnInNvmeReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurnInNvmeReport.Unmarshal(m, b)
}
func (m *BurnInNvmeReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurnInNvmeReport.Marshal(b, m, deterministic)
}
func (dst *BurnInNvmeReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurnInNvmeReport.Merge(dst, src)
}
func (m *BurnInNvmeReport) XXX_Size() int {
	return xxx_messageInfo_BurnInNvmeReport.Size(m)
}
func (m *BurnInNvmeReport) XXX_DiscardUnknown() {
	xxx_messageInfo_BurnInNvmeReport.DiscardUnknown(m)
}

var xxx_messageInfo_BurnInNvmeReport proto.InternalMessageInfo

func (m *BurnInNvmeReport) GetReport() string {
	if m != nil {
		return m.Report
	}
	return ""
}

// ScmModule represent Storage Class Memory modules installed.
type ScmModule struct {
	// The uid of the module.
	// string uid = 1;
	// The physical id of the module.
	Physicalid uint32 `protobuf:"varint,1,opt,name=physicalid,proto3" json:"physicalid,omitempty"`
	// The device handle of the module.
	// string handle = 3;
	// The channel id where module is installed.
	Channel uint32 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// The channel position where module is installed.
	Channelpos uint32 `protobuf:"varint,3,opt,name=channelpos,proto3" json:"channelpos,omitempty"`
	// The memory controller id attached to module.
	Memctrlr uint32 `protobuf:"varint,4,opt,name=memctrlr,proto3" json:"memctrlr,omitempty"`
	// The socket id attached to module.
	Socket uint32 `protobuf:"varint,5,opt,name=socket,proto3" json:"socket,omitempty"`
	// The serial number of the module.
	// string serial = 8;
	// The capacity of the module.
	Capacity             uint64   `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScmModule) Reset()         { *m = ScmModule{} }
func (m *ScmModule) String() string { return proto.CompactTextString(m) }
func (*ScmModule) ProtoMessage()    {}
func (*ScmModule) Descriptor() ([]byte, []int) {
	return fileDescriptor_srv_df659f08190eb06d, []int{10}
}
func (m *ScmModule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScmModule.Unmarshal(m, b)
}
func (m *ScmModule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScmModule.Marshal(b, m, deterministic)
}
func (dst *ScmModule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScmModule.Merge(dst, src)
}
func (m *ScmModule) XXX_Size() int {
	return xxx_messageInfo_ScmModule.Size(m)
}
func (m *ScmModule) XXX_DiscardUnknown() {
	xxx_messageInfo_ScmModule.DiscardUnknown(m)
}

var xxx_messageInfo_ScmModule proto.InternalMessageInfo

func (m *ScmModule) GetPhysicalid() uint32 {
	if m != nil {
		return m.Physicalid
	}
	return 0
}

func (m *ScmModule) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *ScmModule) GetChannelpos() uint32 {
	if m != nil {
		return m.Channelpos
	}
	return 0
}

func (m *ScmModule) GetMemctrlr() uint32 {
	if m != nil {
		return m.Memctrlr
	}
	return 0
}

func (m *ScmModule) GetSocket() uint32 {
	if m != nil {
		return m.Socket
	}
	return 0
}

func (m *ScmModule) GetCapacity() uint64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func init() {
	proto.RegisterType((*EmptyParams)(nil), "proto.EmptyParams")
	proto.RegisterType((*FeatureName)(nil), "proto.FeatureName")
	proto.RegisterType((*Category)(nil), "proto.Category")
	proto.RegisterType((*Feature)(nil), "proto.Feature")
	proto.RegisterType((*NvmeNamespace)(nil), "proto.NvmeNamespace")
	proto.RegisterType((*NvmeController)(nil), "proto.NvmeController")
	proto.RegisterType((*UpdateNvmeCtrlrParams)(nil), "proto.UpdateNvmeCtrlrParams")
	proto.RegisterType((*FioConfigPath)(nil), "proto.FioConfigPath")
	proto.RegisterType((*BurnInNvmeParams)(nil), "proto.BurnInNvmeParams")
	proto.RegisterType((*BurnInNvmeReport)(nil), "proto.BurnInNvmeReport")
	proto.RegisterType((*ScmModule)(nil), "proto.ScmModule")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MgmtControlClient is the client API for MgmtControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MgmtControlClient interface {
	GetFeature(ctx context.Context, in *FeatureName, opts ...grpc.CallOption) (*Feature, error)
	ListAllFeatures(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (MgmtControl_ListAllFeaturesClient, error)
	ListFeatures(ctx context.Context, in *Category, opts ...grpc.CallOption) (MgmtControl_ListFeaturesClient, error)
	ListNvmeCtrlrs(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (MgmtControl_ListNvmeCtrlrsClient, error)
	UpdateNvmeCtrlr(ctx context.Context, in *UpdateNvmeCtrlrParams, opts ...grpc.CallOption) (*NvmeController, error)
	FetchFioConfigPaths(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (MgmtControl_FetchFioConfigPathsClient, error)
	BurnInNvme(ctx context.Context, in *BurnInNvmeParams, opts ...grpc.CallOption) (MgmtControl_BurnInNvmeClient, error)
	ListScmModules(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (MgmtControl_ListScmModulesClient, error)
}

type mgmtControlClient struct {
	cc *grpc.ClientConn
}

func NewMgmtControlClient(cc *grpc.ClientConn) MgmtControlClient {
	return &mgmtControlClient{cc}
}

func (c *mgmtControlClient) GetFeature(ctx context.Context, in *FeatureName, opts ...grpc.CallOption) (*Feature, error) {
	out := new(Feature)
	err := c.cc.Invoke(ctx, "/proto.MgmtControl/GetFeature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtControlClient) ListAllFeatures(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (MgmtControl_ListAllFeaturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MgmtControl_serviceDesc.Streams[0], "/proto.MgmtControl/ListAllFeatures", opts...)
	if err != nil {
		return nil, err
	}
	x := &mgmtControlListAllFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MgmtControl_ListAllFeaturesClient interface {
	Recv() (*Feature, error)
	grpc.ClientStream
}

type mgmtControlListAllFeaturesClient struct {
	grpc.ClientStream
}

func (x *mgmtControlListAllFeaturesClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mgmtControlClient) ListFeatures(ctx context.Context, in *Category, opts ...grpc.CallOption) (MgmtControl_ListFeaturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MgmtControl_serviceDesc.Streams[1], "/proto.MgmtControl/ListFeatures", opts...)
	if err != nil {
		return nil, err
	}
	x := &mgmtControlListFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MgmtControl_ListFeaturesClient interface {
	Recv() (*Feature, error)
	grpc.ClientStream
}

type mgmtControlListFeaturesClient struct {
	grpc.ClientStream
}

func (x *mgmtControlListFeaturesClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mgmtControlClient) ListNvmeCtrlrs(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (MgmtControl_ListNvmeCtrlrsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MgmtControl_serviceDesc.Streams[2], "/proto.MgmtControl/ListNvmeCtrlrs", opts...)
	if err != nil {
		return nil, err
	}
	x := &mgmtControlListNvmeCtrlrsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MgmtControl_ListNvmeCtrlrsClient interface {
	Recv() (*NvmeController, error)
	grpc.ClientStream
}

type mgmtControlListNvmeCtrlrsClient struct {
	grpc.ClientStream
}

func (x *mgmtControlListNvmeCtrlrsClient) Recv() (*NvmeController, error) {
	m := new(NvmeController)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mgmtControlClient) UpdateNvmeCtrlr(ctx context.Context, in *UpdateNvmeCtrlrParams, opts ...grpc.CallOption) (*NvmeController, error) {
	out := new(NvmeController)
	err := c.cc.Invoke(ctx, "/proto.MgmtControl/UpdateNvmeCtrlr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtControlClient) FetchFioConfigPaths(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (MgmtControl_FetchFioConfigPathsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MgmtControl_serviceDesc.Streams[3], "/proto.MgmtControl/FetchFioConfigPaths", opts...)
	if err != nil {
		return nil, err
	}
	x := &mgmtControlFetchFioConfigPathsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MgmtControl_FetchFioConfigPathsClient interface {
	Recv() (*FioConfigPath, error)
	grpc.ClientStream
}

type mgmtControlFetchFioConfigPathsClient struct {
	grpc.ClientStream
}

func (x *mgmtControlFetchFioConfigPathsClient) Recv() (*FioConfigPath, error) {
	m := new(FioConfigPath)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mgmtControlClient) BurnInNvme(ctx context.Context, in *BurnInNvmeParams, opts ...grpc.CallOption) (MgmtControl_BurnInNvmeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MgmtControl_serviceDesc.Streams[4], "/proto.MgmtControl/BurnInNvme", opts...)
	if err != nil {
		return nil, err
	}
	x := &mgmtControlBurnInNvmeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MgmtControl_BurnInNvmeClient interface {
	Recv() (*BurnInNvmeReport, error)
	grpc.ClientStream
}

type mgmtControlBurnInNvmeClient struct {
	grpc.ClientStream
}

func (x *mgmtControlBurnInNvmeClient) Recv() (*BurnInNvmeReport, error) {
	m := new(BurnInNvmeReport)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mgmtControlClient) ListScmModules(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (MgmtControl_ListScmModulesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MgmtControl_serviceDesc.Streams[5], "/proto.MgmtControl/ListScmModules", opts...)
	if err != nil {
		return nil, err
	}
	x := &mgmtControlListScmModulesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MgmtControl_ListScmModulesClient interface {
	Recv() (*ScmModule, error)
	grpc.ClientStream
}

type mgmtControlListScmModulesClient struct {
	grpc.ClientStream
}

func (x *mgmtControlListScmModulesClient) Recv() (*ScmModule, error) {
	m := new(ScmModule)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MgmtControlServer is the server API for MgmtControl service.
type MgmtControlServer interface {
	GetFeature(context.Context, *FeatureName) (*Feature, error)
	ListAllFeatures(*EmptyParams, MgmtControl_ListAllFeaturesServer) error
	ListFeatures(*Category, MgmtControl_ListFeaturesServer) error
	ListNvmeCtrlrs(*EmptyParams, MgmtControl_ListNvmeCtrlrsServer) error
	UpdateNvmeCtrlr(context.Context, *UpdateNvmeCtrlrParams) (*NvmeController, error)
	FetchFioConfigPaths(*EmptyParams, MgmtControl_FetchFioConfigPathsServer) error
	BurnInNvme(*BurnInNvmeParams, MgmtControl_BurnInNvmeServer) error
	ListScmModules(*EmptyParams, MgmtControl_ListScmModulesServer) error
}

func RegisterMgmtControlServer(s *grpc.Server, srv MgmtControlServer) {
	s.RegisterService(&_MgmtControl_serviceDesc, srv)
}

func _MgmtControl_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtControlServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MgmtControl/GetFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtControlServer).GetFeature(ctx, req.(*FeatureName))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtControl_ListAllFeatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MgmtControlServer).ListAllFeatures(m, &mgmtControlListAllFeaturesServer{stream})
}

type MgmtControl_ListAllFeaturesServer interface {
	Send(*Feature) error
	grpc.ServerStream
}

type mgmtControlListAllFeaturesServer struct {
	grpc.ServerStream
}

func (x *mgmtControlListAllFeaturesServer) Send(m *Feature) error {
	return x.ServerStream.SendMsg(m)
}

func _MgmtControl_ListFeatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Category)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MgmtControlServer).ListFeatures(m, &mgmtControlListFeaturesServer{stream})
}

type MgmtControl_ListFeaturesServer interface {
	Send(*Feature) error
	grpc.ServerStream
}

type mgmtControlListFeaturesServer struct {
	grpc.ServerStream
}

func (x *mgmtControlListFeaturesServer) Send(m *Feature) error {
	return x.ServerStream.SendMsg(m)
}

func _MgmtControl_ListNvmeCtrlrs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MgmtControlServer).ListNvmeCtrlrs(m, &mgmtControlListNvmeCtrlrsServer{stream})
}

type MgmtControl_ListNvmeCtrlrsServer interface {
	Send(*NvmeController) error
	grpc.ServerStream
}

type mgmtControlListNvmeCtrlrsServer struct {
	grpc.ServerStream
}

func (x *mgmtControlListNvmeCtrlrsServer) Send(m *NvmeController) error {
	return x.ServerStream.SendMsg(m)
}

func _MgmtControl_UpdateNvmeCtrlr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNvmeCtrlrParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtControlServer).UpdateNvmeCtrlr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MgmtControl/UpdateNvmeCtrlr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtControlServer).UpdateNvmeCtrlr(ctx, req.(*UpdateNvmeCtrlrParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtControl_FetchFioConfigPaths_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MgmtControlServer).FetchFioConfigPaths(m, &mgmtControlFetchFioConfigPathsServer{stream})
}

type MgmtControl_FetchFioConfigPathsServer interface {
	Send(*FioConfigPath) error
	grpc.ServerStream
}

type mgmtControlFetchFioConfigPathsServer struct {
	grpc.ServerStream
}

func (x *mgmtControlFetchFioConfigPathsServer) Send(m *FioConfigPath) error {
	return x.ServerStream.SendMsg(m)
}

func _MgmtControl_BurnInNvme_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BurnInNvmeParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MgmtControlServer).BurnInNvme(m, &mgmtControlBurnInNvmeServer{stream})
}

type MgmtControl_BurnInNvmeServer interface {
	Send(*BurnInNvmeReport) error
	grpc.ServerStream
}

type mgmtControlBurnInNvmeServer struct {
	grpc.ServerStream
}

func (x *mgmtControlBurnInNvmeServer) Send(m *BurnInNvmeReport) error {
	return x.ServerStream.SendMsg(m)
}

func _MgmtControl_ListScmModules_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MgmtControlServer).ListScmModules(m, &mgmtControlListScmModulesServer{stream})
}

type MgmtControl_ListScmModulesServer interface {
	Send(*ScmModule) error
	grpc.ServerStream
}

type mgmtControlListScmModulesServer struct {
	grpc.ServerStream
}

func (x *mgmtControlListScmModulesServer) Send(m *ScmModule) error {
	return x.ServerStream.SendMsg(m)
}

var _MgmtControl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MgmtControl",
	HandlerType: (*MgmtControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeature",
			Handler:    _MgmtControl_GetFeature_Handler,
		},
		{
			MethodName: "UpdateNvmeCtrlr",
			Handler:    _MgmtControl_UpdateNvmeCtrlr_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAllFeatures",
			Handler:       _MgmtControl_ListAllFeatures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListFeatures",
			Handler:       _MgmtControl_ListFeatures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListNvmeCtrlrs",
			Handler:       _MgmtControl_ListNvmeCtrlrs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FetchFioConfigPaths",
			Handler:       _MgmtControl_FetchFioConfigPaths_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BurnInNvme",
			Handler:       _MgmtControl_BurnInNvme_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListScmModules",
			Handler:       _MgmtControl_ListScmModules_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "srv.proto",
}

func init() { proto.RegisterFile("srv.proto", fileDescriptor_srv_df659f08190eb06d) }

var fileDescriptor_srv_df659f08190eb06d = []byte{
	// 618 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0x35, 0xed, 0x66, 0xdb, 0xbd, 0x31, 0xdb, 0x32, 0xb6, 0x1a, 0x8a, 0xc8, 0x1a, 0x41, 0x16,
	0x0b, 0x45, 0xb6, 0x4f, 0xea, 0x83, 0xd8, 0xc5, 0xaa, 0x60, 0x4b, 0x19, 0xd1, 0xf7, 0x31, 0x99,
	0x76, 0x83, 0x49, 0x26, 0x4c, 0xa6, 0x2b, 0xfb, 0xa8, 0x3f, 0x49, 0xf0, 0xff, 0xc9, 0xdc, 0xdc,
	0x7c, 0xec, 0x36, 0x3e, 0x65, 0xce, 0xcd, 0x3d, 0x67, 0xce, 0xdc, 0x39, 0x03, 0xa3, 0x52, 0x2f,
	0x4f, 0x0a, 0xad, 0x8c, 0x62, 0x2e, 0x7e, 0x42, 0x1f, 0xbc, 0xf7, 0x59, 0x61, 0x56, 0x57, 0x42,
	0x8b, 0xac, 0x0c, 0x9f, 0x82, 0x77, 0x2e, 0x85, 0xb9, 0xd5, 0xf2, 0x52, 0x64, 0x92, 0x31, 0x18,
	0xe4, 0x22, 0x93, 0x81, 0x33, 0x71, 0xa6, 0x23, 0x8e, 0xeb, 0xf0, 0x39, 0xec, 0xce, 0x85, 0x91,
	0x37, 0x4a, 0xaf, 0xd8, 0x11, 0xec, 0x46, 0xb4, 0xa6, 0x9e, 0x06, 0x87, 0xbf, 0x1d, 0xd8, 0x21,
	0x2d, 0x76, 0xbc, 0xd1, 0xe7, 0xcd, 0xf6, 0x2a, 0x1b, 0x27, 0xb5, 0x54, 0x4b, 0x64, 0x53, 0x70,
	0xaf, 0x71, 0xd7, 0x2d, 0xec, 0x64, 0xd4, 0xd9, 0xf1, 0xc5, 0xab, 0x06, 0x36, 0x01, 0x2f, 0x96,
	0x65, 0xa4, 0x93, 0xc2, 0x24, 0x2a, 0x0f, 0xb6, 0xd1, 0x41, 0xb7, 0x14, 0xbe, 0x01, 0xff, 0x72,
	0x99, 0x21, 0xa9, 0x2c, 0x44, 0x24, 0xd9, 0x18, 0xb6, 0x92, 0x18, 0x95, 0x5d, 0xbe, 0x95, 0xc4,
	0xd5, 0x09, 0x0a, 0x11, 0x25, 0x66, 0x85, 0x7c, 0x97, 0x37, 0x38, 0xfc, 0xe3, 0xc0, 0xd8, 0xb2,
	0xe7, 0x2a, 0x37, 0x5a, 0xa5, 0xa9, 0xd4, 0x44, 0x77, 0x1a, 0xfa, 0x01, 0xb8, 0x99, 0x8a, 0x65,
	0x8a, 0x8a, 0x23, 0x5e, 0x01, 0xf6, 0x10, 0x86, 0xa5, 0xd4, 0x89, 0x48, 0xc9, 0x12, 0x21, 0x16,
	0xc0, 0x4e, 0x11, 0x25, 0x22, 0x8e, 0x75, 0x30, 0xc0, 0x1f, 0x35, 0xb4, 0x3a, 0xd7, 0x3f, 0xb5,
	0x5c, 0x06, 0x6e, 0xa5, 0x83, 0x80, 0xcd, 0x60, 0x94, 0xd7, 0xce, 0x83, 0xe1, 0x64, 0x7b, 0xea,
	0xcd, 0x0e, 0x68, 0x1a, 0x6b, 0xa7, 0xe2, 0x6d, 0x5b, 0x98, 0xc2, 0xe1, 0xd7, 0x22, 0x16, 0x46,
	0xa2, 0x73, 0xa3, 0x53, 0x5d, 0x5d, 0x2d, 0x3b, 0x06, 0x37, 0xb2, 0x90, 0x2e, 0xe0, 0xb0, 0x23,
	0xd4, 0x1e, 0x90, 0x57, 0x3d, 0xf6, 0xe2, 0x0b, 0x61, 0x16, 0x74, 0x2c, 0x5c, 0xdb, 0x5a, 0x99,
	0x2a, 0x43, 0x63, 0xc2, 0x75, 0xf8, 0x0c, 0xfc, 0xf3, 0x44, 0xcd, 0x55, 0x7e, 0x9d, 0xdc, 0x5c,
	0x51, 0x13, 0x12, 0x9d, 0x96, 0x18, 0x7e, 0x83, 0xfd, 0xb3, 0x5b, 0x9d, 0x7f, 0xca, 0xed, 0x5e,
	0xe4, 0x26, 0x80, 0x1d, 0xdc, 0xa9, 0x99, 0x66, 0x0d, 0xd9, 0xb4, 0xb3, 0x75, 0x7b, 0xde, 0xb5,
	0x5d, 0x48, 0xf7, 0x45, 0x57, 0x97, 0xcb, 0x42, 0x69, 0x63, 0x47, 0xaf, 0x71, 0x45, 0x0e, 0x08,
	0x85, 0x7f, 0x1d, 0x18, 0x7d, 0x89, 0xb2, 0x0b, 0x15, 0xdf, 0xa6, 0x92, 0x3d, 0x01, 0x28, 0x16,
	0xab, 0x32, 0x89, 0x44, 0x4a, 0x06, 0x7c, 0xde, 0xa9, 0xa0, 0xbb, 0x85, 0xc8, 0x73, 0xba, 0x58,
	0x9f, 0xd7, 0xd0, 0x32, 0x69, 0x59, 0xa8, 0x12, 0x47, 0xe1, 0xf3, 0x4e, 0xc5, 0xe6, 0x29, 0x93,
	0x59, 0x35, 0xe8, 0x01, 0xfe, 0x6d, 0x30, 0xc6, 0x42, 0x45, 0x3f, 0xa4, 0xc1, 0x5b, 0xf6, 0x39,
	0xa1, 0xb5, 0x0c, 0x0e, 0x27, 0xce, 0x74, 0xd0, 0x66, 0x70, 0xf6, 0x6b, 0x00, 0xde, 0xc5, 0x4d,
	0x66, 0xe8, 0x8a, 0xd8, 0x0c, 0xe0, 0x83, 0x34, 0xf5, 0xbb, 0xea, 0x79, 0x1b, 0x47, 0xe3, 0xf5,
	0x5a, 0x78, 0x8f, 0xbd, 0x82, 0xbd, 0xcf, 0x49, 0x69, 0xde, 0xa5, 0x29, 0xd5, 0xca, 0x86, 0xd8,
	0x79, 0xfb, 0x77, 0x89, 0x2f, 0x1d, 0x76, 0x0a, 0xf7, 0x2d, 0xb5, 0xe1, 0x6d, 0x3e, 0xdb, 0x5e,
	0xd2, 0x5b, 0x18, 0x5b, 0x52, 0x13, 0xc0, 0xfe, 0xed, 0xfa, 0x03, 0x88, 0x02, 0x1f, 0x61, 0x6f,
	0x23, 0xc3, 0xec, 0x31, 0x75, 0xf7, 0x66, 0xfb, 0xbf, 0x5a, 0x6c, 0x0e, 0x0f, 0xce, 0xa5, 0x89,
	0x16, 0x6b, 0xf1, 0xe9, 0xf7, 0xd3, 0x9b, 0x34, 0xb4, 0x73, 0x06, 0xd0, 0xe6, 0x8c, 0x3d, 0xa2,
	0xbe, 0xcd, 0x48, 0x1f, 0xdd, 0xfd, 0x51, 0x65, 0x12, 0x35, 0x5e, 0x57, 0x33, 0x69, 0x22, 0xd8,
	0xef, 0x61, 0x9f, 0x6a, 0x4d, 0x9b, 0xe5, 0x7e, 0x1f, 0x62, 0xf1, 0xf4, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x4a, 0x2c, 0x63, 0x5f, 0xbe, 0x05, 0x00, 0x00,
}
