"""Build security library"""

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    prereqs.require(env, 'protobufc')

    env.AppendUnique(LIBPATH=[Dir('.')])
    denv = env.Clone()

    # Shared src between server and client
    common_src = denv.SharedObject(['security.pb-c.c'])

    # dc_security: Security Client
    dc_security_tgts = denv.SharedObject(['cli_security.c']) + common_src
    Export('dc_security_tgts')

    SConscript('tests/SConscript', exports='denv')

if __name__ == "SCons.Script":
    scons()
