#!python
# (C) Copyright 2018-2021 Intel Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
"""Build swim src"""

SRC = ['swim.c']

def scons():
    """Scons function"""

    Import('env')

    env.AppendUnique(LIBPATH=[Dir('.')])

    denv = env.Clone()

    denv.AppendUnique(LIBS=['gurt'])

    swim_targets = denv.SharedObject(SRC)

    Default(swim_targets)
    Export('swim_targets')


if __name__ == "SCons.Script":
    scons()
