#!python
# (C) Copyright 2018-2021 Intel Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
"""Build swim src"""


def scons():
    """Scons function"""

    Import('env')

    swim_targets = env.SharedObject('swim.c')

    Default(swim_targets)
    Export('swim_targets')


if __name__ == "SCons.Script":
    scons()
