#!python
# (C) Copyright 2018-2020 Intel Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# GOVERNMENT LICENSE RIGHTS-OPEN SOURCE SOFTWARE
# The Government's rights to use, modify, reproduce, release, perform, display,
# or disclose this software are subject to the terms of the Apache License as
# provided in Contract No. 8F-30005.
# Any reproduction of computer software, computer software documentation, or
# portions thereof marked with this legend must also reproduce the markings.
#
"""Build swim src"""

SRC = ['swim.c']

def scons():
    """Scons function"""

    Import('env', 'gurt_lib')

    env.AppendUnique(LIBPATH=[Dir('.')])

    denv = env.Clone()

    denv.AppendUnique(CPPPATH=['#/src/cart/swim'])
    denv.AppendUnique(LIBS=['gurt'])
    denv.Append(CCFLAGS=['-D_USE_CART_'])

    swim_targets = denv.SharedObject(SRC)
    swim_lib = denv.SharedLibrary('libswim', swim_targets)
    denv.Requires(swim_lib, gurt_lib)

    Default(swim_targets)
    Export('swim_lib', 'swim_targets')

if __name__ == "SCons.Script":
    scons()
