"""Build extent I/O"""
import os
import daos_build

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    env.AppendUnique(LIBPATH=[Dir('.')])

    denv = env.Clone()
    prereqs.require(denv, 'pmdk', 'spdk', 'argobots')

    eio = daos_build.library(denv, "eio", Glob('*.c'), LIBS=['numa', 'spdk'])
    denv.Install('$PREFIX/lib/daos_srv', eio)

if __name__ == "SCons.Script":
    scons()
