"""Build io_conf generator"""


def scons():
    """Execute build"""
    Import(['denv', 'daos_test_tgt', 'daos_epoch_io', 'daos_test_obj'])

    libraries = ['daos_common', 'daos', 'daos_tests', 'gurt', 'cart', 'uuid']
    libraries += ['cmocka', 'json-c', 'dpar']

    daos_gen_io_conf = denv.d_test_program([File('daos_gen_io_conf.c'), daos_test_tgt,
                                            daos_epoch_io, daos_test_obj],
                                           LIBS=libraries)

    daos_run_io_conf = denv.d_test_program([File('daos_run_io_conf.c'), daos_test_tgt,
                                            daos_epoch_io, daos_test_obj],
                                           LIBS=libraries)
    denv.Install('$PREFIX/bin/', daos_gen_io_conf)
    denv.Install('$PREFIX/bin/', daos_run_io_conf)


if __name__ == "SCons.Script":
    scons()
