"""Build drpc test"""

def scons():
    """Execute build"""
    Import('env', 'prereqs')

    libs = ['$LIBS', 'daos_common', 'gurt']
    sources = ['drpc_test.c', 'drpc_test.pb-c.c']

    denv = env.Clone()
    denv.AppendUnique(CFLAGS=['-std=gnu99'])
    denv.AppendUnique(CPPDEFINES=['TEST'])

    prereqs.require(denv, 'protobufc')

    drpc_test = denv.Program('drpc_test', sources, LIBS=libs)
    env.Install('$PREFIX/bin/', drpc_test)

    drpc_iosrv_test = denv.Program('drpc_iosrv_test',
                                   ['drpc_iosrv_test.c'], LIBS=libs)
    env.Install('$PREFIX/bin/', drpc_iosrv_test)

if __name__ == "SCons.Script":
    scons()
