"""Build DAOS components"""

import os

HEADERS = ['daos.h', 'daos_api.h', 'daos_types.h', 'daos_errno.h',
           'daos_event.h', 'daos_mgmt.h', 'daos_types.h', 'daos_addons.h',
           'daos_task.h', 'daos_fs.h', 'daos_uns.h']
HEADERS_SRV = ['vos.h', 'vos_types.h']

def scons():
    """Execute build"""

    Import('env', 'prereqs')

    # For Common library (tse.h)
    env.AppendUnique(CPPPATH=[Dir('include/daos').srcnode()])
    env.Install(os.path.join('$PREFIX', 'include/daos'), 'include/daos/tse.h')

    # Generic DAOS includes
    env.AppendUnique(CPPPATH=[Dir('include').srcnode()])
    for header in HEADERS:
        env.Install(os.path.join('$PREFIX', 'include'), 'include/%s' % header)
    for header in HEADERS_SRV:
        env.Install(os.path.join('$PREFIX', 'include', 'daos_srv'),
                    'include/daos_srv/%s' % header)

    # Add hwloc requires
    prereqs.require(env, 'hwloc')

    # Generate the common libraries used by more than one component
    SConscript('common/SConscript')
    SConscript('bio/SConscript')

    SConscript('vos/SConscript')

    # Build each DAOS component
    SConscript('rdb/SConscript')
    SConscript('rsvc/SConscript')
    SConscript('mgmt/SConscript')
    SConscript('pool/SConscript')
    SConscript('container/SConscript')
    SConscript('placement/SConscript')
    SConscript('object/SConscript')
    SConscript('rebuild/SConscript')
    SConscript('security/SConscript')

    # Build DAOS client libraries
    SConscript('client/SConscript')

    # Then the DAOS I/O server executable
    SConscript('iosrv/SConscript')

    # Build utilities
    SConscript('utils/SConscript')

    # Build the control plane components
    SConscript('control/SConscript')

    # Build test
    SConscript('tests/SConscript')

if __name__ == "SCons.Script":
    scons()
