# Set of variables for Rocky 8
# yamllint disable rule:line-length

daos_openmpi_module_path: /usr/share/modulefiles/mpi/openmpi-x86_64

daos_base_deps:
  rpms:
    - bash
    - capstone
    - gdb
    - glibc
    - jq
    - lbzip2
    - numactl
    - numactl-libs
    - numatop
    - platform-python
    - python36
    - systemd
    - tree

daos_dev_deps:
  rpms:
    - argobots-devel
    - capstone-devel
    - bzip2-devel
    - clustershell
    - cmake
    - createrepo
    - daos-raft-devel
    - dnf-plugins-core
    - fuse3-devel
    - gcc-c++
    - gcc-gfortran
    - golang
    - libaec-devel
    - libattr-devel
    - libcmocka-devel
    - libevent-devel
    - libyaml-devel
    - meson
    - ninja-build
    - openssl-devel
    - python3-avocado
    - python-avocado-bash
    - python-avocado-common
    - python-avocado-examples
    - python3-avocado-plugins-glib
    - python3-avocado-plugins-golang
    - python3-avocado-plugins-loader-yaml
    - python3-avocado-plugins-output-html
    - python3-avocado-plugins-result-upload
    - python3-avocado-plugins-varianter-yaml-to-mux.noarch
    - python3-clustershell
    - python3-defusedxml
    - python3-distro
    - python3-jira
    - python3-junit_xml
    - python3-pip
    - python3-pyelftools
    - python3-scons
    - python3-tabulate
    - python3-wheel
    - python3-pyxattr
    - python3-pyyaml
    - rpmdevtools
    - rpm-build
    - spdk-devel
    - valgrind-devel
    - wget

daos_client_deps:
  rpms:
    - compat-hwloc1
    - fuse3
    - fuse3-libs
    - libaec
    - libuuid
    - lz4-libs
    - numactl-devel
    - systemd
    - util-linux

daos_server_deps:
  rpms:
    - compat-hwloc1
    - dpdk
    - ipmctl
    - libipmctl
    - libpmemobj
    - libuuid
    - lz4-libs
    - ndctl
    - spdk-tools

mlnx_deps:
  rpms:
    - mlnx-ofed-all
