# Set of variables for Rocky 8
# yamllint disable rule:line-length

daos_openmpi_module_path: /usr/share/modulefiles/mpi/openmpi-x86_64

daos_base_deps:
  rpms:
    - bash
    - capstone
    - gdb
    - glibc
    - jq
    - lbzip2
    - numactl
    - numactl-libs
    - numatop
    - platform-python
    - python36
    - systemd
    - tree

daos_dev_deps:
  rpms:
    - argobots-devel
    - capstone-devel
    - bzip2-devel
    - cmake
    - createrepo
    - daos-raft-devel
    - dnf-plugins-core
    - fuse3-devel
    - gcc-c++
    - gcc-gfortran
    - golang
    - libaec-devel
    - libattr-devel
    - libcmocka-devel
    - libevent-devel
    - libyaml-devel
    - openssl-devel
    - python3-clustershell
    - rpmdevtools
    - rpm-build
    - spdk-devel
    - valgrind-devel
    - wget
  pips:
    - "avocado=={{ daos_avocado_version | default(daos_avocado_version_default) }}"
    - "avocado-framework=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
    - "avocado-framework-plugin-glib=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
    - "avocado-framework-plugin-golang=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
    - "avocado-framework-plugin-loader-yaml=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
    - "avocado-framework-plugin-result-html=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
    - "avocado-framework-plugin-result-upload=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
    - "avocado-framework-plugin-varianter-yaml-to-mux=={{ daos_avocado_framework_version | default(daos_avocado_framework_version_default) }}"
    - defusedxml
    - distro
    - jira
    - junit_xml
    - meson
    - ninja
    - pyelftools
    - pyxattr
    - pyyaml
    - scons
    - tabulate
    - wheel

daos_client_deps:
  rpms:
    - compat-hwloc1
    - fuse3
    - fuse3-libs
    - libaec
    - libuuid
    - lz4-libs
    - numactl-devel
    - systemd
    - util-linux

daos_server_deps:
  rpms:
    - compat-hwloc1
    - dpdk
    - ipmctl
    - libipmctl
    - libpmemobj
    - libuuid
    - lz4-libs
    - ndctl
    - spdk-tools

mlnx_deps:
  rpms:
    - mlnx-ofed-all
