#!python

Import('env', 'PREREQS')

common = env.SharedLibrary('libdaos_common', Glob('*.c'))
env.AppendUnique(LIBPATH=[Dir('.')])
SConscript('tests/SConscript', exports='env')
env.Install('$PREFIX/lib/', common)

if PREREQS is None:
        config = Configure(env)
        if config.CheckLibWithHeader('pmemobj', 'libpmemobj.h', language='C'):
                env.Append(LIBS=['pmemobj'])
        config.Finish()
else:
        PREREQS.require('nvml')
