#!python

Import('env', 'PREREQS')

env.AppendUnique(LIBPATH=[Dir('.')])

if PREREQS is None:
        config = Configure(env)
        if config.CheckLibWithHeader('pmemobj', 'libpmemobj.h', language='C'):
                env.Append(LIBS=['pmemobj'])
        config.Finish()
else:
        PREREQS.require(env, 'nvml', 'argobots', 'cart')

denv = env.Clone()

common = denv.SharedLibrary('libdaos_common', Glob('*.c'))
denv.Install('$PREFIX/lib/', common)

denv.Append(CPPPATH = ['#/src/common'])
SConscript('tests/SConscript', exports='denv')
