"""Build DAOS client"""

def scons():
    """Execute build"""

    SConscript('addons/SConscript')
    SConscript('api/SConscript')
    SConscript('dfs/SConscript')

if __name__ == "SCons.Script":
    scons()
