// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mgmt.proto

package mgmt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Generic request indicating which ranks to operate on.
// Used in gRPC fanout to operate on hosts with multiple ranks.
type RanksReq struct {
	Ranks                []uint32 `protobuf:"varint,1,rep,packed,name=ranks,proto3" json:"ranks,omitempty"`
	Force                bool     `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RanksReq) Reset()         { *m = RanksReq{} }
func (m *RanksReq) String() string { return proto.CompactTextString(m) }
func (*RanksReq) ProtoMessage()    {}
func (*RanksReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgmt_82425800c4ec2aed, []int{0}
}
func (m *RanksReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RanksReq.Unmarshal(m, b)
}
func (m *RanksReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RanksReq.Marshal(b, m, deterministic)
}
func (dst *RanksReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RanksReq.Merge(dst, src)
}
func (m *RanksReq) XXX_Size() int {
	return xxx_messageInfo_RanksReq.Size(m)
}
func (m *RanksReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RanksReq.DiscardUnknown(m)
}

var xxx_messageInfo_RanksReq proto.InternalMessageInfo

func (m *RanksReq) GetRanks() []uint32 {
	if m != nil {
		return m.Ranks
	}
	return nil
}

func (m *RanksReq) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

// Generic response containing DER result from multiple ranks.
// Used in gRPC fanout to operate on hosts with multiple ranks.
type RanksResp struct {
	Results              []*RanksResp_RankResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RanksResp) Reset()         { *m = RanksResp{} }
func (m *RanksResp) String() string { return proto.CompactTextString(m) }
func (*RanksResp) ProtoMessage()    {}
func (*RanksResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgmt_82425800c4ec2aed, []int{1}
}
func (m *RanksResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RanksResp.Unmarshal(m, b)
}
func (m *RanksResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RanksResp.Marshal(b, m, deterministic)
}
func (dst *RanksResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RanksResp.Merge(dst, src)
}
func (m *RanksResp) XXX_Size() int {
	return xxx_messageInfo_RanksResp.Size(m)
}
func (m *RanksResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RanksResp.DiscardUnknown(m)
}

var xxx_messageInfo_RanksResp proto.InternalMessageInfo

func (m *RanksResp) GetResults() []*RanksResp_RankResult {
	if m != nil {
		return m.Results
	}
	return nil
}

// Identical to ctl.system.RankResult proto message.
type RanksResp_RankResult struct {
	Rank                 uint32   `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Errored              bool     `protobuf:"varint,3,opt,name=errored,proto3" json:"errored,omitempty"`
	Msg                  string   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	State                uint32   `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RanksResp_RankResult) Reset()         { *m = RanksResp_RankResult{} }
func (m *RanksResp_RankResult) String() string { return proto.CompactTextString(m) }
func (*RanksResp_RankResult) ProtoMessage()    {}
func (*RanksResp_RankResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgmt_82425800c4ec2aed, []int{1, 0}
}
func (m *RanksResp_RankResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RanksResp_RankResult.Unmarshal(m, b)
}
func (m *RanksResp_RankResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RanksResp_RankResult.Marshal(b, m, deterministic)
}
func (dst *RanksResp_RankResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RanksResp_RankResult.Merge(dst, src)
}
func (m *RanksResp_RankResult) XXX_Size() int {
	return xxx_messageInfo_RanksResp_RankResult.Size(m)
}
func (m *RanksResp_RankResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RanksResp_RankResult.DiscardUnknown(m)
}

var xxx_messageInfo_RanksResp_RankResult proto.InternalMessageInfo

func (m *RanksResp_RankResult) GetRank() uint32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *RanksResp_RankResult) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *RanksResp_RankResult) GetErrored() bool {
	if m != nil {
		return m.Errored
	}
	return false
}

func (m *RanksResp_RankResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RanksResp_RankResult) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func init() {
	proto.RegisterType((*RanksReq)(nil), "mgmt.RanksReq")
	proto.RegisterType((*RanksResp)(nil), "mgmt.RanksResp")
	proto.RegisterType((*RanksResp_RankResult)(nil), "mgmt.RanksResp.RankResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MgmtSvcClient is the client API for MgmtSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MgmtSvcClient interface {
	// Join the server described by JoinReq to the system.
	Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinResp, error)
	// LeaderQuery provides a mechanism for clients to discover
	// the system's current Management Service leader
	LeaderQuery(ctx context.Context, in *LeaderQueryReq, opts ...grpc.CallOption) (*LeaderQueryResp, error)
	// Create a DAOS pool allocated across a number of ranks
	PoolCreate(ctx context.Context, in *PoolCreateReq, opts ...grpc.CallOption) (*PoolCreateResp, error)
	// Destroy a DAOS pool allocated across a number of ranks.
	PoolDestroy(ctx context.Context, in *PoolDestroyReq, opts ...grpc.CallOption) (*PoolDestroyResp, error)
	// Exclude a pool target.
	PoolExclude(ctx context.Context, in *PoolExcludeReq, opts ...grpc.CallOption) (*PoolExcludeResp, error)
	// Reintegrate a pool target.
	PoolReintegrate(ctx context.Context, in *PoolReintegrateReq, opts ...grpc.CallOption) (*PoolReintegrateResp, error)
	// PoolQuery queries a DAOS pool.
	PoolQuery(ctx context.Context, in *PoolQueryReq, opts ...grpc.CallOption) (*PoolQueryResp, error)
	// Set a DAOS pool property.
	PoolSetProp(ctx context.Context, in *PoolSetPropReq, opts ...grpc.CallOption) (*PoolSetPropResp, error)
	// Fetch the Access Control List for a DAOS pool.
	PoolGetACL(ctx context.Context, in *GetACLReq, opts ...grpc.CallOption) (*ACLResp, error)
	// Overwrite the Access Control List for a DAOS pool with a new one.
	PoolOverwriteACL(ctx context.Context, in *ModifyACLReq, opts ...grpc.CallOption) (*ACLResp, error)
	// Update existing the Access Control List for a DAOS pool with new entries.
	PoolUpdateACL(ctx context.Context, in *ModifyACLReq, opts ...grpc.CallOption) (*ACLResp, error)
	// Delete an entry from a DAOS pool's Access Control List.
	PoolDeleteACL(ctx context.Context, in *DeleteACLReq, opts ...grpc.CallOption) (*ACLResp, error)
	// Get the information required by libdaos to attach to the system.
	GetAttachInfo(ctx context.Context, in *GetAttachInfoReq, opts ...grpc.CallOption) (*GetAttachInfoResp, error)
	// Get BIO device health information.
	BioHealthQuery(ctx context.Context, in *BioHealthReq, opts ...grpc.CallOption) (*BioHealthResp, error)
	// Get SMD device list.
	SmdListDevs(ctx context.Context, in *SmdDevReq, opts ...grpc.CallOption) (*SmdDevResp, error)
	// Get SMD pool list.
	SmdListPools(ctx context.Context, in *SmdPoolReq, opts ...grpc.CallOption) (*SmdPoolResp, error)
	// List all pools in a DAOS system: basic info: UUIDs, service ranks.
	ListPools(ctx context.Context, in *ListPoolsReq, opts ...grpc.CallOption) (*ListPoolsResp, error)
	// Get the current state of the device
	DevStateQuery(ctx context.Context, in *DevStateReq, opts ...grpc.CallOption) (*DevStateResp, error)
	// Set the device state of an NVMe SSD to FAULTY
	StorageSetFaulty(ctx context.Context, in *DevStateReq, opts ...grpc.CallOption) (*DevStateResp, error)
	// List all containers in a pool
	ListContainers(ctx context.Context, in *ListContReq, opts ...grpc.CallOption) (*ListContResp, error)
	// Prepare DAOS IO servers on a host for controlled shutdown. (gRPC fanout)
	PrepShutdownRanks(ctx context.Context, in *RanksReq, opts ...grpc.CallOption) (*RanksResp, error)
	// Stop DAOS IO servers on a host. (gRPC fanout)
	StopRanks(ctx context.Context, in *RanksReq, opts ...grpc.CallOption) (*RanksResp, error)
	// Ping DAOS IO servers on a host. (gRPC fanout)
	PingRanks(ctx context.Context, in *RanksReq, opts ...grpc.CallOption) (*RanksResp, error)
	// ResetFormat DAOS IO servers on a host. (gRPC fanout)
	ResetFormatRanks(ctx context.Context, in *RanksReq, opts ...grpc.CallOption) (*RanksResp, error)
	// Start DAOS IO servers on a host. (gRPC fanout)
	StartRanks(ctx context.Context, in *RanksReq, opts ...grpc.CallOption) (*RanksResp, error)
	// Change the owner of a DAOS container
	ContSetOwner(ctx context.Context, in *ContSetOwnerReq, opts ...grpc.CallOption) (*ContSetOwnerResp, error)
}

type mgmtSvcClient struct {
	cc *grpc.ClientConn
}

func NewMgmtSvcClient(cc *grpc.ClientConn) MgmtSvcClient {
	return &mgmtSvcClient{cc}
}

func (c *mgmtSvcClient) Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinResp, error) {
	out := new(JoinResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) LeaderQuery(ctx context.Context, in *LeaderQueryReq, opts ...grpc.CallOption) (*LeaderQueryResp, error) {
	out := new(LeaderQueryResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/LeaderQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PoolCreate(ctx context.Context, in *PoolCreateReq, opts ...grpc.CallOption) (*PoolCreateResp, error) {
	out := new(PoolCreateResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PoolCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PoolDestroy(ctx context.Context, in *PoolDestroyReq, opts ...grpc.CallOption) (*PoolDestroyResp, error) {
	out := new(PoolDestroyResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PoolDestroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PoolExclude(ctx context.Context, in *PoolExcludeReq, opts ...grpc.CallOption) (*PoolExcludeResp, error) {
	out := new(PoolExcludeResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PoolExclude", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PoolReintegrate(ctx context.Context, in *PoolReintegrateReq, opts ...grpc.CallOption) (*PoolReintegrateResp, error) {
	out := new(PoolReintegrateResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PoolReintegrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PoolQuery(ctx context.Context, in *PoolQueryReq, opts ...grpc.CallOption) (*PoolQueryResp, error) {
	out := new(PoolQueryResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PoolQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PoolSetProp(ctx context.Context, in *PoolSetPropReq, opts ...grpc.CallOption) (*PoolSetPropResp, error) {
	out := new(PoolSetPropResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PoolSetProp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PoolGetACL(ctx context.Context, in *GetACLReq, opts ...grpc.CallOption) (*ACLResp, error) {
	out := new(ACLResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PoolGetACL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PoolOverwriteACL(ctx context.Context, in *ModifyACLReq, opts ...grpc.CallOption) (*ACLResp, error) {
	out := new(ACLResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PoolOverwriteACL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PoolUpdateACL(ctx context.Context, in *ModifyACLReq, opts ...grpc.CallOption) (*ACLResp, error) {
	out := new(ACLResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PoolUpdateACL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PoolDeleteACL(ctx context.Context, in *DeleteACLReq, opts ...grpc.CallOption) (*ACLResp, error) {
	out := new(ACLResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PoolDeleteACL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) GetAttachInfo(ctx context.Context, in *GetAttachInfoReq, opts ...grpc.CallOption) (*GetAttachInfoResp, error) {
	out := new(GetAttachInfoResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/GetAttachInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) BioHealthQuery(ctx context.Context, in *BioHealthReq, opts ...grpc.CallOption) (*BioHealthResp, error) {
	out := new(BioHealthResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/BioHealthQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) SmdListDevs(ctx context.Context, in *SmdDevReq, opts ...grpc.CallOption) (*SmdDevResp, error) {
	out := new(SmdDevResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/SmdListDevs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) SmdListPools(ctx context.Context, in *SmdPoolReq, opts ...grpc.CallOption) (*SmdPoolResp, error) {
	out := new(SmdPoolResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/SmdListPools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) ListPools(ctx context.Context, in *ListPoolsReq, opts ...grpc.CallOption) (*ListPoolsResp, error) {
	out := new(ListPoolsResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/ListPools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) DevStateQuery(ctx context.Context, in *DevStateReq, opts ...grpc.CallOption) (*DevStateResp, error) {
	out := new(DevStateResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/DevStateQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) StorageSetFaulty(ctx context.Context, in *DevStateReq, opts ...grpc.CallOption) (*DevStateResp, error) {
	out := new(DevStateResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/StorageSetFaulty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) ListContainers(ctx context.Context, in *ListContReq, opts ...grpc.CallOption) (*ListContResp, error) {
	out := new(ListContResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/ListContainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PrepShutdownRanks(ctx context.Context, in *RanksReq, opts ...grpc.CallOption) (*RanksResp, error) {
	out := new(RanksResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PrepShutdownRanks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) StopRanks(ctx context.Context, in *RanksReq, opts ...grpc.CallOption) (*RanksResp, error) {
	out := new(RanksResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/StopRanks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) PingRanks(ctx context.Context, in *RanksReq, opts ...grpc.CallOption) (*RanksResp, error) {
	out := new(RanksResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/PingRanks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) ResetFormatRanks(ctx context.Context, in *RanksReq, opts ...grpc.CallOption) (*RanksResp, error) {
	out := new(RanksResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/ResetFormatRanks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) StartRanks(ctx context.Context, in *RanksReq, opts ...grpc.CallOption) (*RanksResp, error) {
	out := new(RanksResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/StartRanks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtSvcClient) ContSetOwner(ctx context.Context, in *ContSetOwnerReq, opts ...grpc.CallOption) (*ContSetOwnerResp, error) {
	out := new(ContSetOwnerResp)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtSvc/ContSetOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MgmtSvcServer is the server API for MgmtSvc service.
type MgmtSvcServer interface {
	// Join the server described by JoinReq to the system.
	Join(context.Context, *JoinReq) (*JoinResp, error)
	// LeaderQuery provides a mechanism for clients to discover
	// the system's current Management Service leader
	LeaderQuery(context.Context, *LeaderQueryReq) (*LeaderQueryResp, error)
	// Create a DAOS pool allocated across a number of ranks
	PoolCreate(context.Context, *PoolCreateReq) (*PoolCreateResp, error)
	// Destroy a DAOS pool allocated across a number of ranks.
	PoolDestroy(context.Context, *PoolDestroyReq) (*PoolDestroyResp, error)
	// Exclude a pool target.
	PoolExclude(context.Context, *PoolExcludeReq) (*PoolExcludeResp, error)
	// Reintegrate a pool target.
	PoolReintegrate(context.Context, *PoolReintegrateReq) (*PoolReintegrateResp, error)
	// PoolQuery queries a DAOS pool.
	PoolQuery(context.Context, *PoolQueryReq) (*PoolQueryResp, error)
	// Set a DAOS pool property.
	PoolSetProp(context.Context, *PoolSetPropReq) (*PoolSetPropResp, error)
	// Fetch the Access Control List for a DAOS pool.
	PoolGetACL(context.Context, *GetACLReq) (*ACLResp, error)
	// Overwrite the Access Control List for a DAOS pool with a new one.
	PoolOverwriteACL(context.Context, *ModifyACLReq) (*ACLResp, error)
	// Update existing the Access Control List for a DAOS pool with new entries.
	PoolUpdateACL(context.Context, *ModifyACLReq) (*ACLResp, error)
	// Delete an entry from a DAOS pool's Access Control List.
	PoolDeleteACL(context.Context, *DeleteACLReq) (*ACLResp, error)
	// Get the information required by libdaos to attach to the system.
	GetAttachInfo(context.Context, *GetAttachInfoReq) (*GetAttachInfoResp, error)
	// Get BIO device health information.
	BioHealthQuery(context.Context, *BioHealthReq) (*BioHealthResp, error)
	// Get SMD device list.
	SmdListDevs(context.Context, *SmdDevReq) (*SmdDevResp, error)
	// Get SMD pool list.
	SmdListPools(context.Context, *SmdPoolReq) (*SmdPoolResp, error)
	// List all pools in a DAOS system: basic info: UUIDs, service ranks.
	ListPools(context.Context, *ListPoolsReq) (*ListPoolsResp, error)
	// Get the current state of the device
	DevStateQuery(context.Context, *DevStateReq) (*DevStateResp, error)
	// Set the device state of an NVMe SSD to FAULTY
	StorageSetFaulty(context.Context, *DevStateReq) (*DevStateResp, error)
	// List all containers in a pool
	ListContainers(context.Context, *ListContReq) (*ListContResp, error)
	// Prepare DAOS IO servers on a host for controlled shutdown. (gRPC fanout)
	PrepShutdownRanks(context.Context, *RanksReq) (*RanksResp, error)
	// Stop DAOS IO servers on a host. (gRPC fanout)
	StopRanks(context.Context, *RanksReq) (*RanksResp, error)
	// Ping DAOS IO servers on a host. (gRPC fanout)
	PingRanks(context.Context, *RanksReq) (*RanksResp, error)
	// ResetFormat DAOS IO servers on a host. (gRPC fanout)
	ResetFormatRanks(context.Context, *RanksReq) (*RanksResp, error)
	// Start DAOS IO servers on a host. (gRPC fanout)
	StartRanks(context.Context, *RanksReq) (*RanksResp, error)
	// Change the owner of a DAOS container
	ContSetOwner(context.Context, *ContSetOwnerReq) (*ContSetOwnerResp, error)
}

func RegisterMgmtSvcServer(s *grpc.Server, srv MgmtSvcServer) {
	s.RegisterService(&_MgmtSvc_serviceDesc, srv)
}

func _MgmtSvc_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).Join(ctx, req.(*JoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_LeaderQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).LeaderQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/LeaderQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).LeaderQuery(ctx, req.(*LeaderQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PoolCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PoolCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PoolCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PoolCreate(ctx, req.(*PoolCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PoolDestroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolDestroyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PoolDestroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PoolDestroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PoolDestroy(ctx, req.(*PoolDestroyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PoolExclude_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolExcludeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PoolExclude(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PoolExclude",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PoolExclude(ctx, req.(*PoolExcludeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PoolReintegrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolReintegrateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PoolReintegrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PoolReintegrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PoolReintegrate(ctx, req.(*PoolReintegrateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PoolQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PoolQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PoolQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PoolQuery(ctx, req.(*PoolQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PoolSetProp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolSetPropReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PoolSetProp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PoolSetProp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PoolSetProp(ctx, req.(*PoolSetPropReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PoolGetACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetACLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PoolGetACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PoolGetACL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PoolGetACL(ctx, req.(*GetACLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PoolOverwriteACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyACLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PoolOverwriteACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PoolOverwriteACL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PoolOverwriteACL(ctx, req.(*ModifyACLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PoolUpdateACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyACLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PoolUpdateACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PoolUpdateACL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PoolUpdateACL(ctx, req.(*ModifyACLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PoolDeleteACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteACLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PoolDeleteACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PoolDeleteACL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PoolDeleteACL(ctx, req.(*DeleteACLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_GetAttachInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttachInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).GetAttachInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/GetAttachInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).GetAttachInfo(ctx, req.(*GetAttachInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_BioHealthQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BioHealthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).BioHealthQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/BioHealthQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).BioHealthQuery(ctx, req.(*BioHealthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_SmdListDevs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmdDevReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).SmdListDevs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/SmdListDevs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).SmdListDevs(ctx, req.(*SmdDevReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_SmdListPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmdPoolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).SmdListPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/SmdListPools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).SmdListPools(ctx, req.(*SmdPoolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_ListPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoolsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).ListPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/ListPools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).ListPools(ctx, req.(*ListPoolsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_DevStateQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).DevStateQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/DevStateQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).DevStateQuery(ctx, req.(*DevStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_StorageSetFaulty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).StorageSetFaulty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/StorageSetFaulty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).StorageSetFaulty(ctx, req.(*DevStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/ListContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).ListContainers(ctx, req.(*ListContReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PrepShutdownRanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RanksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PrepShutdownRanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PrepShutdownRanks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PrepShutdownRanks(ctx, req.(*RanksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_StopRanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RanksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).StopRanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/StopRanks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).StopRanks(ctx, req.(*RanksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_PingRanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RanksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).PingRanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/PingRanks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).PingRanks(ctx, req.(*RanksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_ResetFormatRanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RanksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).ResetFormatRanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/ResetFormatRanks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).ResetFormatRanks(ctx, req.(*RanksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_StartRanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RanksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).StartRanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/StartRanks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).StartRanks(ctx, req.(*RanksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtSvc_ContSetOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContSetOwnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtSvcServer).ContSetOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtSvc/ContSetOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtSvcServer).ContSetOwner(ctx, req.(*ContSetOwnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MgmtSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mgmt.MgmtSvc",
	HandlerType: (*MgmtSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _MgmtSvc_Join_Handler,
		},
		{
			MethodName: "LeaderQuery",
			Handler:    _MgmtSvc_LeaderQuery_Handler,
		},
		{
			MethodName: "PoolCreate",
			Handler:    _MgmtSvc_PoolCreate_Handler,
		},
		{
			MethodName: "PoolDestroy",
			Handler:    _MgmtSvc_PoolDestroy_Handler,
		},
		{
			MethodName: "PoolExclude",
			Handler:    _MgmtSvc_PoolExclude_Handler,
		},
		{
			MethodName: "PoolReintegrate",
			Handler:    _MgmtSvc_PoolReintegrate_Handler,
		},
		{
			MethodName: "PoolQuery",
			Handler:    _MgmtSvc_PoolQuery_Handler,
		},
		{
			MethodName: "PoolSetProp",
			Handler:    _MgmtSvc_PoolSetProp_Handler,
		},
		{
			MethodName: "PoolGetACL",
			Handler:    _MgmtSvc_PoolGetACL_Handler,
		},
		{
			MethodName: "PoolOverwriteACL",
			Handler:    _MgmtSvc_PoolOverwriteACL_Handler,
		},
		{
			MethodName: "PoolUpdateACL",
			Handler:    _MgmtSvc_PoolUpdateACL_Handler,
		},
		{
			MethodName: "PoolDeleteACL",
			Handler:    _MgmtSvc_PoolDeleteACL_Handler,
		},
		{
			MethodName: "GetAttachInfo",
			Handler:    _MgmtSvc_GetAttachInfo_Handler,
		},
		{
			MethodName: "BioHealthQuery",
			Handler:    _MgmtSvc_BioHealthQuery_Handler,
		},
		{
			MethodName: "SmdListDevs",
			Handler:    _MgmtSvc_SmdListDevs_Handler,
		},
		{
			MethodName: "SmdListPools",
			Handler:    _MgmtSvc_SmdListPools_Handler,
		},
		{
			MethodName: "ListPools",
			Handler:    _MgmtSvc_ListPools_Handler,
		},
		{
			MethodName: "DevStateQuery",
			Handler:    _MgmtSvc_DevStateQuery_Handler,
		},
		{
			MethodName: "StorageSetFaulty",
			Handler:    _MgmtSvc_StorageSetFaulty_Handler,
		},
		{
			MethodName: "ListContainers",
			Handler:    _MgmtSvc_ListContainers_Handler,
		},
		{
			MethodName: "PrepShutdownRanks",
			Handler:    _MgmtSvc_PrepShutdownRanks_Handler,
		},
		{
			MethodName: "StopRanks",
			Handler:    _MgmtSvc_StopRanks_Handler,
		},
		{
			MethodName: "PingRanks",
			Handler:    _MgmtSvc_PingRanks_Handler,
		},
		{
			MethodName: "ResetFormatRanks",
			Handler:    _MgmtSvc_ResetFormatRanks_Handler,
		},
		{
			MethodName: "StartRanks",
			Handler:    _MgmtSvc_StartRanks_Handler,
		},
		{
			MethodName: "ContSetOwner",
			Handler:    _MgmtSvc_ContSetOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mgmt.proto",
}

func init() { proto.RegisterFile("mgmt.proto", fileDescriptor_mgmt_82425800c4ec2aed) }

var fileDescriptor_mgmt_82425800c4ec2aed = []byte{
	// 689 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0x80, 0x4f, 0x0e, 0xe1, 0x27, 0x13, 0x12, 0xc2, 0xc2, 0xe1, 0xb8, 0xbe, 0x8a, 0xb8, 0x69,
	0xae, 0xa8, 0x44, 0x81, 0x16, 0xb5, 0x52, 0x55, 0x48, 0x29, 0xad, 0x40, 0xa4, 0xb6, 0x7a, 0x5d,
	0xb9, 0xf1, 0x10, 0xac, 0x26, 0x5e, 0x67, 0x77, 0x13, 0x4a, 0xdf, 0xad, 0x4f, 0xd1, 0x17, 0xaa,
	0x66, 0x77, 0x6d, 0x6f, 0x42, 0x90, 0xe0, 0x6e, 0xe6, 0xf3, 0x7c, 0xbb, 0xb3, 0x63, 0x67, 0x03,
	0x30, 0x1a, 0x8c, 0xd4, 0x5e, 0x26, 0xb8, 0xe2, 0xac, 0x4a, 0xb1, 0x0f, 0x19, 0xe7, 0x43, 0x43,
	0x7c, 0xe8, 0xf3, 0xd4, 0x3e, 0xf5, 0x6b, 0x52, 0x4c, 0x6d, 0xb8, 0x25, 0x15, 0x17, 0xd1, 0x00,
	0xbf, 0x8d, 0x27, 0x28, 0xee, 0xf2, 0xe7, 0x51, 0xdf, 0x6a, 0xbb, 0x47, 0xb0, 0x16, 0x44, 0xe9,
	0x0f, 0x19, 0xe0, 0x98, 0x6d, 0xc3, 0xb2, 0xa0, 0xd8, 0xab, 0xb4, 0x97, 0x3a, 0x8d, 0xc0, 0x24,
	0x44, 0xaf, 0xb9, 0xe8, 0xa3, 0xb7, 0xd4, 0xae, 0x74, 0xd6, 0x02, 0x93, 0xec, 0xfe, 0xae, 0x40,
	0xcd, 0x8a, 0x32, 0x63, 0x07, 0xb0, 0x2a, 0x50, 0x4e, 0x86, 0xca, 0xb8, 0xf5, 0x7d, 0x7f, 0x4f,
	0x37, 0x5b, 0x54, 0xe8, 0x28, 0xd0, 0x25, 0x41, 0x5e, 0xea, 0xff, 0x02, 0x28, 0x31, 0x63, 0x50,
	0xa5, 0x0d, 0xbd, 0x4a, 0xbb, 0xd2, 0x69, 0x04, 0x3a, 0x66, 0x3b, 0xb0, 0x12, 0xf5, 0x55, 0xc2,
	0x53, 0xef, 0xdf, 0x76, 0xa5, 0x53, 0x0b, 0x6c, 0xc6, 0x3c, 0x58, 0x45, 0x21, 0xb8, 0xc0, 0xd8,
	0x76, 0x95, 0xa7, 0xac, 0x05, 0x4b, 0x23, 0x39, 0xf0, 0xaa, 0xba, 0x9c, 0x42, 0xea, 0x5f, 0xaa,
	0x48, 0xa1, 0xb7, 0xac, 0x17, 0x36, 0xc9, 0xfe, 0x9f, 0x3a, 0xac, 0x5e, 0x0e, 0x46, 0x2a, 0x9c,
	0xf6, 0xd9, 0x73, 0xa8, 0x7e, 0xe6, 0x49, 0xca, 0x1a, 0xa6, 0x69, 0x8a, 0x03, 0x1c, 0xfb, 0x4d,
	0x37, 0x95, 0xd9, 0xee, 0x3f, 0xec, 0x2d, 0xd4, 0x2f, 0x30, 0x8a, 0x51, 0x7c, 0xa1, 0x61, 0xb2,
	0x6d, 0x53, 0xe0, 0x20, 0xd2, 0xfe, 0x5b, 0x40, 0xb5, 0x7d, 0x0c, 0xd0, 0xe3, 0x7c, 0x78, 0x2a,
	0x30, 0x52, 0xc8, 0xb6, 0x4c, 0x59, 0x49, 0xc8, 0xdd, 0xbe, 0x0f, 0xf3, 0x8d, 0x89, 0x75, 0x51,
	0x2a, 0xc1, 0x8b, 0x8d, 0x1d, 0xe4, 0x6c, 0x3c, 0x43, 0x5d, 0xfb, 0xc3, 0xcf, 0xfe, 0x70, 0x12,
	0xa3, 0x6b, 0x5b, 0x34, 0x67, 0x17, 0x54, 0xdb, 0xe7, 0xb0, 0x41, 0x30, 0xc0, 0x24, 0x55, 0x38,
	0x10, 0xd4, 0xbb, 0x57, 0xd6, 0x3a, 0x98, 0x56, 0x79, 0xf6, 0xc0, 0x13, 0xbd, 0xd2, 0x11, 0xd4,
	0xe8, 0x81, 0x19, 0x1e, 0x2b, 0x2b, 0x8b, 0xd1, 0x6d, 0xdd, 0x63, 0x6e, 0xff, 0x21, 0xaa, 0x9e,
	0xe0, 0x99, 0xdb, 0xbf, 0x45, 0x73, 0xfd, 0x17, 0x54, 0xdb, 0x7b, 0x66, 0xec, 0x1f, 0x51, 0xbd,
	0x3f, 0xbd, 0x60, 0x1b, 0xa6, 0xcc, 0x64, 0xe4, 0xd9, 0x97, 0xae, 0x33, 0x5d, 0xff, 0x0a, 0x5a,
	0x54, 0x7f, 0x35, 0x45, 0x71, 0x2b, 0x12, 0x85, 0x64, 0xd9, 0x66, 0x2f, 0x79, 0x9c, 0x5c, 0xdf,
	0x3d, 0x24, 0x1e, 0x40, 0x83, 0xc4, 0xaf, 0x59, 0x1c, 0x3d, 0xdd, 0xea, 0xe2, 0x10, 0x67, 0xac,
	0x02, 0x2c, 0xb4, 0x4e, 0xa0, 0x41, 0x47, 0x50, 0x2a, 0xea, 0xdf, 0x7c, 0x4a, 0xaf, 0x39, 0xdb,
	0x29, 0xcf, 0x55, 0x40, 0x32, 0xff, 0x5f, 0xc8, 0xf5, 0x1a, 0x6f, 0xa0, 0x79, 0x92, 0xf0, 0x73,
	0x8c, 0x86, 0xea, 0x66, 0xe6, 0x9d, 0x14, 0xd4, 0x79, 0x27, 0x0e, 0xd3, 0xf2, 0x3e, 0xd4, 0xc3,
	0x51, 0x7c, 0x91, 0x48, 0xd5, 0xc5, 0xa9, 0xcc, 0xc7, 0x1a, 0x8e, 0xe2, 0x2e, 0x4e, 0x49, 0x6b,
	0xcd, 0x02, 0xed, 0x1c, 0xc2, 0xba, 0x75, 0xe8, 0xc4, 0x92, 0x95, 0x35, 0xe6, 0x7b, 0x19, 0xfb,
	0x9b, 0x73, 0x24, 0xff, 0x6c, 0x4a, 0xc7, 0xb6, 0x58, 0x00, 0xa7, 0x45, 0x87, 0x69, 0xef, 0x35,
	0x34, 0xba, 0x38, 0x0d, 0xe9, 0xe7, 0x6e, 0x8e, 0xb7, 0x99, 0x4f, 0xd6, 0x40, 0x52, 0xd9, 0x3c,
	0xb2, 0x93, 0x69, 0x85, 0xe6, 0xda, 0x0c, 0x51, 0x9d, 0x45, 0x93, 0xa1, 0x7a, 0x82, 0x7c, 0x0c,
	0x4d, 0xea, 0xe4, 0x94, 0xa7, 0x2a, 0x4a, 0x52, 0x14, 0x32, 0x57, 0x73, 0xea, 0xa8, 0x25, 0xb2,
	0x27, 0xdd, 0xec, 0x09, 0xcc, 0xc2, 0x9b, 0x89, 0x8a, 0xf9, 0x6d, 0xaa, 0x6f, 0x4f, 0xd6, 0x9c,
	0xb9, 0x4a, 0xc7, 0xfe, 0xc6, 0xdc, 0xd5, 0xaa, 0x3f, 0xf1, 0x5a, 0xa8, 0x78, 0xf6, 0x94, 0xfa,
	0x5e, 0x92, 0x0e, 0x1e, 0x5d, 0x7f, 0x08, 0xad, 0x00, 0x25, 0xaa, 0x33, 0x2e, 0x46, 0x91, 0x7a,
	0xb4, 0xf6, 0x02, 0x20, 0x54, 0x91, 0x78, 0xbc, 0xf0, 0x0e, 0xd6, 0x69, 0x1a, 0x21, 0xaa, 0xab,
	0xdb, 0x14, 0x05, 0xb3, 0xbf, 0x69, 0x97, 0x91, 0xb9, 0xb3, 0x08, 0xd3, 0x02, 0xdf, 0x57, 0xf4,
	0x9f, 0xda, 0xcb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0xc4, 0xc8, 0xe6, 0x2b, 0x07, 0x00,
	0x00,
}
