// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pool.proto

package mgmt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// PoolCreateReq supplies new pool parameters.
type PoolCreateReq struct {
	Scmbytes             uint64   `protobuf:"varint,1,opt,name=scmbytes,proto3" json:"scmbytes,omitempty"`
	Nvmebytes            uint64   `protobuf:"varint,2,opt,name=nvmebytes,proto3" json:"nvmebytes,omitempty"`
	Ranks                []uint32 `protobuf:"varint,3,rep,packed,name=ranks,proto3" json:"ranks,omitempty"`
	Numsvcreps           uint32   `protobuf:"varint,4,opt,name=numsvcreps,proto3" json:"numsvcreps,omitempty"`
	User                 string   `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Usergroup            string   `protobuf:"bytes,6,opt,name=usergroup,proto3" json:"usergroup,omitempty"`
	Uuid                 string   `protobuf:"bytes,7,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sys                  string   `protobuf:"bytes,8,opt,name=sys,proto3" json:"sys,omitempty"`
	Acl                  []string `protobuf:"bytes,9,rep,name=acl,proto3" json:"acl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolCreateReq) Reset()         { *m = PoolCreateReq{} }
func (m *PoolCreateReq) String() string { return proto.CompactTextString(m) }
func (*PoolCreateReq) ProtoMessage()    {}
func (*PoolCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{0}
}

func (m *PoolCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolCreateReq.Unmarshal(m, b)
}
func (m *PoolCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolCreateReq.Marshal(b, m, deterministic)
}
func (m *PoolCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolCreateReq.Merge(m, src)
}
func (m *PoolCreateReq) XXX_Size() int {
	return xxx_messageInfo_PoolCreateReq.Size(m)
}
func (m *PoolCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_PoolCreateReq proto.InternalMessageInfo

func (m *PoolCreateReq) GetScmbytes() uint64 {
	if m != nil {
		return m.Scmbytes
	}
	return 0
}

func (m *PoolCreateReq) GetNvmebytes() uint64 {
	if m != nil {
		return m.Nvmebytes
	}
	return 0
}

func (m *PoolCreateReq) GetRanks() []uint32 {
	if m != nil {
		return m.Ranks
	}
	return nil
}

func (m *PoolCreateReq) GetNumsvcreps() uint32 {
	if m != nil {
		return m.Numsvcreps
	}
	return 0
}

func (m *PoolCreateReq) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PoolCreateReq) GetUsergroup() string {
	if m != nil {
		return m.Usergroup
	}
	return ""
}

func (m *PoolCreateReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PoolCreateReq) GetSys() string {
	if m != nil {
		return m.Sys
	}
	return ""
}

func (m *PoolCreateReq) GetAcl() []string {
	if m != nil {
		return m.Acl
	}
	return nil
}

// PoolCreateResp returns created pool uuid and ranks.
type PoolCreateResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Svcreps              []uint32 `protobuf:"varint,2,rep,packed,name=svcreps,proto3" json:"svcreps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolCreateResp) Reset()         { *m = PoolCreateResp{} }
func (m *PoolCreateResp) String() string { return proto.CompactTextString(m) }
func (*PoolCreateResp) ProtoMessage()    {}
func (*PoolCreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{1}
}

func (m *PoolCreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolCreateResp.Unmarshal(m, b)
}
func (m *PoolCreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolCreateResp.Marshal(b, m, deterministic)
}
func (m *PoolCreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolCreateResp.Merge(m, src)
}
func (m *PoolCreateResp) XXX_Size() int {
	return xxx_messageInfo_PoolCreateResp.Size(m)
}
func (m *PoolCreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolCreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_PoolCreateResp proto.InternalMessageInfo

func (m *PoolCreateResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PoolCreateResp) GetSvcreps() []uint32 {
	if m != nil {
		return m.Svcreps
	}
	return nil
}

// PoolDestroyReq supplies pool identifier and force flag.
type PoolDestroyReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sys                  string   `protobuf:"bytes,2,opt,name=sys,proto3" json:"sys,omitempty"`
	Force                bool     `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolDestroyReq) Reset()         { *m = PoolDestroyReq{} }
func (m *PoolDestroyReq) String() string { return proto.CompactTextString(m) }
func (*PoolDestroyReq) ProtoMessage()    {}
func (*PoolDestroyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{2}
}

func (m *PoolDestroyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolDestroyReq.Unmarshal(m, b)
}
func (m *PoolDestroyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolDestroyReq.Marshal(b, m, deterministic)
}
func (m *PoolDestroyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolDestroyReq.Merge(m, src)
}
func (m *PoolDestroyReq) XXX_Size() int {
	return xxx_messageInfo_PoolDestroyReq.Size(m)
}
func (m *PoolDestroyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolDestroyReq.DiscardUnknown(m)
}

var xxx_messageInfo_PoolDestroyReq proto.InternalMessageInfo

func (m *PoolDestroyReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PoolDestroyReq) GetSys() string {
	if m != nil {
		return m.Sys
	}
	return ""
}

func (m *PoolDestroyReq) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

// PoolDestroyResp returns resultant state of destroy operation.
type PoolDestroyResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolDestroyResp) Reset()         { *m = PoolDestroyResp{} }
func (m *PoolDestroyResp) String() string { return proto.CompactTextString(m) }
func (*PoolDestroyResp) ProtoMessage()    {}
func (*PoolDestroyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{3}
}

func (m *PoolDestroyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolDestroyResp.Unmarshal(m, b)
}
func (m *PoolDestroyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolDestroyResp.Marshal(b, m, deterministic)
}
func (m *PoolDestroyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolDestroyResp.Merge(m, src)
}
func (m *PoolDestroyResp) XXX_Size() int {
	return xxx_messageInfo_PoolDestroyResp.Size(m)
}
func (m *PoolDestroyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolDestroyResp.DiscardUnknown(m)
}

var xxx_messageInfo_PoolDestroyResp proto.InternalMessageInfo

func (m *PoolDestroyResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// ListPoolsReq represents a request to list pools on a given DAOS system.
type ListPoolsReq struct {
	Sys                  string   `protobuf:"bytes,1,opt,name=sys,proto3" json:"sys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPoolsReq) Reset()         { *m = ListPoolsReq{} }
func (m *ListPoolsReq) String() string { return proto.CompactTextString(m) }
func (*ListPoolsReq) ProtoMessage()    {}
func (*ListPoolsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{4}
}

func (m *ListPoolsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsReq.Unmarshal(m, b)
}
func (m *ListPoolsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsReq.Marshal(b, m, deterministic)
}
func (m *ListPoolsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsReq.Merge(m, src)
}
func (m *ListPoolsReq) XXX_Size() int {
	return xxx_messageInfo_ListPoolsReq.Size(m)
}
func (m *ListPoolsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsReq proto.InternalMessageInfo

func (m *ListPoolsReq) GetSys() string {
	if m != nil {
		return m.Sys
	}
	return ""
}

// ListPoolsResp returns the list of pools in the system.
type ListPoolsResp struct {
	Status               int32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Pools                []*ListPoolsResp_Pool `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListPoolsResp) Reset()         { *m = ListPoolsResp{} }
func (m *ListPoolsResp) String() string { return proto.CompactTextString(m) }
func (*ListPoolsResp) ProtoMessage()    {}
func (*ListPoolsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{5}
}

func (m *ListPoolsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsResp.Unmarshal(m, b)
}
func (m *ListPoolsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsResp.Marshal(b, m, deterministic)
}
func (m *ListPoolsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsResp.Merge(m, src)
}
func (m *ListPoolsResp) XXX_Size() int {
	return xxx_messageInfo_ListPoolsResp.Size(m)
}
func (m *ListPoolsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsResp proto.InternalMessageInfo

func (m *ListPoolsResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListPoolsResp) GetPools() []*ListPoolsResp_Pool {
	if m != nil {
		return m.Pools
	}
	return nil
}

type ListPoolsResp_Pool struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Svcreps              []uint32 `protobuf:"varint,2,rep,packed,name=svcreps,proto3" json:"svcreps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPoolsResp_Pool) Reset()         { *m = ListPoolsResp_Pool{} }
func (m *ListPoolsResp_Pool) String() string { return proto.CompactTextString(m) }
func (*ListPoolsResp_Pool) ProtoMessage()    {}
func (*ListPoolsResp_Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{5, 0}
}

func (m *ListPoolsResp_Pool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsResp_Pool.Unmarshal(m, b)
}
func (m *ListPoolsResp_Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsResp_Pool.Marshal(b, m, deterministic)
}
func (m *ListPoolsResp_Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsResp_Pool.Merge(m, src)
}
func (m *ListPoolsResp_Pool) XXX_Size() int {
	return xxx_messageInfo_ListPoolsResp_Pool.Size(m)
}
func (m *ListPoolsResp_Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsResp_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsResp_Pool proto.InternalMessageInfo

func (m *ListPoolsResp_Pool) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ListPoolsResp_Pool) GetSvcreps() []uint32 {
	if m != nil {
		return m.Svcreps
	}
	return nil
}

// ListContainers
// Initial implementation differs from C API
// (numContainers not provided in request - get whole list)
type ListContReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContReq) Reset()         { *m = ListContReq{} }
func (m *ListContReq) String() string { return proto.CompactTextString(m) }
func (*ListContReq) ProtoMessage()    {}
func (*ListContReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{6}
}

func (m *ListContReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContReq.Unmarshal(m, b)
}
func (m *ListContReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContReq.Marshal(b, m, deterministic)
}
func (m *ListContReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContReq.Merge(m, src)
}
func (m *ListContReq) XXX_Size() int {
	return xxx_messageInfo_ListContReq.Size(m)
}
func (m *ListContReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListContReq proto.InternalMessageInfo

func (m *ListContReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ListContResp struct {
	Status               int32                `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Containers           []*ListContResp_Cont `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListContResp) Reset()         { *m = ListContResp{} }
func (m *ListContResp) String() string { return proto.CompactTextString(m) }
func (*ListContResp) ProtoMessage()    {}
func (*ListContResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{7}
}

func (m *ListContResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContResp.Unmarshal(m, b)
}
func (m *ListContResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContResp.Marshal(b, m, deterministic)
}
func (m *ListContResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContResp.Merge(m, src)
}
func (m *ListContResp) XXX_Size() int {
	return xxx_messageInfo_ListContResp.Size(m)
}
func (m *ListContResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListContResp proto.InternalMessageInfo

func (m *ListContResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListContResp) GetContainers() []*ListContResp_Cont {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ListContResp_Cont struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContResp_Cont) Reset()         { *m = ListContResp_Cont{} }
func (m *ListContResp_Cont) String() string { return proto.CompactTextString(m) }
func (*ListContResp_Cont) ProtoMessage()    {}
func (*ListContResp_Cont) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{7, 0}
}

func (m *ListContResp_Cont) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContResp_Cont.Unmarshal(m, b)
}
func (m *ListContResp_Cont) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContResp_Cont.Marshal(b, m, deterministic)
}
func (m *ListContResp_Cont) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContResp_Cont.Merge(m, src)
}
func (m *ListContResp_Cont) XXX_Size() int {
	return xxx_messageInfo_ListContResp_Cont.Size(m)
}
func (m *ListContResp_Cont) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContResp_Cont.DiscardUnknown(m)
}

var xxx_messageInfo_ListContResp_Cont proto.InternalMessageInfo

func (m *ListContResp_Cont) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// PoolSetPropReq represents a request to set a pool property.
type PoolSetPropReq struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Types that are valid to be assigned to Property:
	//	*PoolSetPropReq_Name
	//	*PoolSetPropReq_Number
	Property isPoolSetPropReq_Property `protobuf_oneof:"property"`
	// Types that are valid to be assigned to Value:
	//	*PoolSetPropReq_Strval
	//	*PoolSetPropReq_Numval
	Value                isPoolSetPropReq_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PoolSetPropReq) Reset()         { *m = PoolSetPropReq{} }
func (m *PoolSetPropReq) String() string { return proto.CompactTextString(m) }
func (*PoolSetPropReq) ProtoMessage()    {}
func (*PoolSetPropReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{8}
}

func (m *PoolSetPropReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolSetPropReq.Unmarshal(m, b)
}
func (m *PoolSetPropReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolSetPropReq.Marshal(b, m, deterministic)
}
func (m *PoolSetPropReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolSetPropReq.Merge(m, src)
}
func (m *PoolSetPropReq) XXX_Size() int {
	return xxx_messageInfo_PoolSetPropReq.Size(m)
}
func (m *PoolSetPropReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolSetPropReq.DiscardUnknown(m)
}

var xxx_messageInfo_PoolSetPropReq proto.InternalMessageInfo

func (m *PoolSetPropReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type isPoolSetPropReq_Property interface {
	isPoolSetPropReq_Property()
}

type PoolSetPropReq_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

type PoolSetPropReq_Number struct {
	Number uint32 `protobuf:"varint,3,opt,name=number,proto3,oneof"`
}

func (*PoolSetPropReq_Name) isPoolSetPropReq_Property() {}

func (*PoolSetPropReq_Number) isPoolSetPropReq_Property() {}

func (m *PoolSetPropReq) GetProperty() isPoolSetPropReq_Property {
	if m != nil {
		return m.Property
	}
	return nil
}

func (m *PoolSetPropReq) GetName() string {
	if x, ok := m.GetProperty().(*PoolSetPropReq_Name); ok {
		return x.Name
	}
	return ""
}

func (m *PoolSetPropReq) GetNumber() uint32 {
	if x, ok := m.GetProperty().(*PoolSetPropReq_Number); ok {
		return x.Number
	}
	return 0
}

type isPoolSetPropReq_Value interface {
	isPoolSetPropReq_Value()
}

type PoolSetPropReq_Strval struct {
	Strval string `protobuf:"bytes,4,opt,name=strval,proto3,oneof"`
}

type PoolSetPropReq_Numval struct {
	Numval uint64 `protobuf:"varint,5,opt,name=numval,proto3,oneof"`
}

func (*PoolSetPropReq_Strval) isPoolSetPropReq_Value() {}

func (*PoolSetPropReq_Numval) isPoolSetPropReq_Value() {}

func (m *PoolSetPropReq) GetValue() isPoolSetPropReq_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PoolSetPropReq) GetStrval() string {
	if x, ok := m.GetValue().(*PoolSetPropReq_Strval); ok {
		return x.Strval
	}
	return ""
}

func (m *PoolSetPropReq) GetNumval() uint64 {
	if x, ok := m.GetValue().(*PoolSetPropReq_Numval); ok {
		return x.Numval
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PoolSetPropReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PoolSetPropReq_Name)(nil),
		(*PoolSetPropReq_Number)(nil),
		(*PoolSetPropReq_Strval)(nil),
		(*PoolSetPropReq_Numval)(nil),
	}
}

// PoolSetPropResp represents the result of setting a property.
type PoolSetPropResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolSetPropResp) Reset()         { *m = PoolSetPropResp{} }
func (m *PoolSetPropResp) String() string { return proto.CompactTextString(m) }
func (*PoolSetPropResp) ProtoMessage()    {}
func (*PoolSetPropResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{9}
}

func (m *PoolSetPropResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolSetPropResp.Unmarshal(m, b)
}
func (m *PoolSetPropResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolSetPropResp.Marshal(b, m, deterministic)
}
func (m *PoolSetPropResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolSetPropResp.Merge(m, src)
}
func (m *PoolSetPropResp) XXX_Size() int {
	return xxx_messageInfo_PoolSetPropResp.Size(m)
}
func (m *PoolSetPropResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolSetPropResp.DiscardUnknown(m)
}

var xxx_messageInfo_PoolSetPropResp proto.InternalMessageInfo

func (m *PoolSetPropResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*PoolCreateReq)(nil), "mgmt.PoolCreateReq")
	proto.RegisterType((*PoolCreateResp)(nil), "mgmt.PoolCreateResp")
	proto.RegisterType((*PoolDestroyReq)(nil), "mgmt.PoolDestroyReq")
	proto.RegisterType((*PoolDestroyResp)(nil), "mgmt.PoolDestroyResp")
	proto.RegisterType((*ListPoolsReq)(nil), "mgmt.ListPoolsReq")
	proto.RegisterType((*ListPoolsResp)(nil), "mgmt.ListPoolsResp")
	proto.RegisterType((*ListPoolsResp_Pool)(nil), "mgmt.ListPoolsResp.Pool")
	proto.RegisterType((*ListContReq)(nil), "mgmt.ListContReq")
	proto.RegisterType((*ListContResp)(nil), "mgmt.ListContResp")
	proto.RegisterType((*ListContResp_Cont)(nil), "mgmt.ListContResp.Cont")
	proto.RegisterType((*PoolSetPropReq)(nil), "mgmt.PoolSetPropReq")
	proto.RegisterType((*PoolSetPropResp)(nil), "mgmt.PoolSetPropResp")
}

func init() { proto.RegisterFile("pool.proto", fileDescriptor_8a14d8612184524f) }

var fileDescriptor_8a14d8612184524f = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x5e, 0x37, 0x49, 0x7f, 0x66, 0x09, 0x20, 0xab, 0x02, 0xab, 0x42, 0x28, 0xe4, 0x14, 0x2e,
	0x39, 0x00, 0x12, 0xf7, 0x2e, 0x87, 0x1e, 0xf6, 0xb0, 0x32, 0x4f, 0xe0, 0x66, 0xcd, 0xaa, 0x22,
	0x89, 0x83, 0x7f, 0x2a, 0x55, 0x3c, 0x03, 0x8f, 0xc0, 0x03, 0xf2, 0x16, 0x68, 0xec, 0xa4, 0xed,
	0x6a, 0x37, 0x3d, 0x65, 0xbe, 0xf9, 0xf1, 0x7c, 0xdf, 0xcc, 0x04, 0xa0, 0x53, 0xaa, 0x2e, 0x3b,
	0xad, 0xac, 0xa2, 0x71, 0xf3, 0xd0, 0xd8, 0xfc, 0x1f, 0x81, 0xf4, 0x4e, 0xa9, 0xfa, 0x46, 0x4b,
	0x61, 0x25, 0x97, 0xbf, 0xe8, 0x0a, 0xe6, 0xa6, 0x6a, 0xb6, 0x07, 0x2b, 0x0d, 0x23, 0x19, 0x29,
	0x62, 0x7e, 0xc4, 0xf4, 0x1d, 0x2c, 0xda, 0x7d, 0x23, 0x43, 0x70, 0xe2, 0x83, 0x27, 0x07, 0x5d,
	0x42, 0xa2, 0x45, 0xfb, 0xd3, 0xb0, 0x28, 0x8b, 0x8a, 0x94, 0x07, 0x40, 0xdf, 0x03, 0xb4, 0xae,
	0x31, 0xfb, 0x4a, 0xcb, 0xce, 0xb0, 0x38, 0x23, 0x45, 0xca, 0xcf, 0x3c, 0x94, 0x42, 0xec, 0x8c,
	0xd4, 0x2c, 0xc9, 0x48, 0xb1, 0xe0, 0xde, 0xc6, 0x3e, 0xf8, 0x7d, 0xd0, 0xca, 0x75, 0x6c, 0xea,
	0x03, 0x27, 0x87, 0xaf, 0x70, 0xbb, 0x7b, 0x36, 0xeb, 0x2b, 0xdc, 0xee, 0x9e, 0xbe, 0x86, 0xc8,
	0x1c, 0x0c, 0x9b, 0x7b, 0x17, 0x9a, 0xe8, 0x11, 0x55, 0xcd, 0x16, 0x59, 0x84, 0x1e, 0x51, 0xd5,
	0xf9, 0x1a, 0x5e, 0x9e, 0x4b, 0x35, 0x1d, 0x7d, 0x03, 0x53, 0x63, 0x85, 0x75, 0x41, 0x69, 0xc2,
	0x7b, 0x44, 0x19, 0xcc, 0x06, 0xc2, 0x13, 0xaf, 0x65, 0x80, 0xf9, 0x6d, 0x78, 0xe3, 0x9b, 0x34,
	0x56, 0xab, 0x03, 0xce, 0x6b, 0x60, 0x43, 0x9e, 0xb2, 0x99, 0x9c, 0xd8, 0x2c, 0x21, 0xf9, 0xa1,
	0x74, 0x25, 0x59, 0x94, 0x91, 0x62, 0xce, 0x03, 0xc8, 0x3f, 0xc2, 0xab, 0x47, 0xaf, 0x8d, 0x53,
	0xca, 0x33, 0x78, 0x71, 0xbb, 0x33, 0x16, 0xd3, 0x0d, 0xb6, 0xed, 0x5b, 0x90, 0x63, 0x8b, 0xfc,
	0x0f, 0x81, 0xf4, 0x2c, 0xe5, 0x82, 0xbc, 0x12, 0x12, 0x3c, 0x84, 0x20, 0xee, 0xfa, 0x13, 0x2b,
	0xf1, 0x14, 0xca, 0x47, 0xb5, 0x25, 0x5a, 0x3c, 0xa4, 0xad, 0xbe, 0x40, 0x8c, 0xf0, 0x59, 0xa9,
	0xe3, 0xa3, 0xfa, 0x00, 0xd7, 0xf8, 0xe4, 0x8d, 0x6a, 0xed, 0xc8, 0x9c, 0xf2, 0xdf, 0x41, 0x54,
	0x48, 0xb9, 0x40, 0xf8, 0x2b, 0x40, 0xa5, 0x5a, 0x2b, 0x76, 0xad, 0xd4, 0x03, 0xeb, 0xb7, 0x27,
	0xd6, 0x43, 0x7d, 0xe9, 0x8d, 0xb3, 0xd4, 0xd5, 0x0a, 0x62, 0xf4, 0x3d, 0xdb, 0xfc, 0x2f, 0x09,
	0xbb, 0xfc, 0x2e, 0xed, 0x9d, 0x56, 0xdd, 0xd8, 0x2e, 0x97, 0x10, 0xb7, 0xa2, 0x91, 0x61, 0x99,
	0x9b, 0x2b, 0xee, 0x11, 0x65, 0x30, 0x6d, 0x5d, 0xb3, 0x95, 0xda, 0x2f, 0x34, 0xdd, 0x5c, 0xf1,
	0x1e, 0x63, 0xc4, 0x58, 0xbd, 0x17, 0xb5, 0xbf, 0xf5, 0xc5, 0x86, 0xf0, 0x1e, 0xf7, 0x35, 0x18,
	0xc1, 0x5b, 0x8f, 0x31, 0x12, 0xf0, 0x1a, 0x60, 0xde, 0x69, 0xd5, 0x49, 0x6d, 0x0f, 0xeb, 0x19,
	0x24, 0x7b, 0x51, 0xbb, 0xe3, 0x71, 0x1c, 0xe9, 0x8d, 0xcf, 0x67, 0x3b, 0xf5, 0xbf, 0xf4, 0xe7,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x55, 0x11, 0xf2, 0x66, 0xe0, 0x03, 0x00, 0x00,
}
