// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package mgmt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ScanStorageReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanStorageReq) Reset()         { *m = ScanStorageReq{} }
func (m *ScanStorageReq) String() string { return proto.CompactTextString(m) }
func (*ScanStorageReq) ProtoMessage()    {}
func (*ScanStorageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_fbaf07d8be8e1d9c, []int{0}
}
func (m *ScanStorageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanStorageReq.Unmarshal(m, b)
}
func (m *ScanStorageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanStorageReq.Marshal(b, m, deterministic)
}
func (dst *ScanStorageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanStorageReq.Merge(dst, src)
}
func (m *ScanStorageReq) XXX_Size() int {
	return xxx_messageInfo_ScanStorageReq.Size(m)
}
func (m *ScanStorageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanStorageReq.DiscardUnknown(m)
}

var xxx_messageInfo_ScanStorageReq proto.InternalMessageInfo

// ScanStorageResp returns discovered storage devices.
type ScanStorageResp struct {
	Ctrlrs               []*NvmeController `protobuf:"bytes,1,rep,name=ctrlrs,proto3" json:"ctrlrs,omitempty"`
	Nvmestate            *ResponseState    `protobuf:"bytes,2,opt,name=nvmestate,proto3" json:"nvmestate,omitempty"`
	Modules              []*ScmModule      `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty"`
	Scmstate             *ResponseState    `protobuf:"bytes,4,opt,name=scmstate,proto3" json:"scmstate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ScanStorageResp) Reset()         { *m = ScanStorageResp{} }
func (m *ScanStorageResp) String() string { return proto.CompactTextString(m) }
func (*ScanStorageResp) ProtoMessage()    {}
func (*ScanStorageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_fbaf07d8be8e1d9c, []int{1}
}
func (m *ScanStorageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanStorageResp.Unmarshal(m, b)
}
func (m *ScanStorageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanStorageResp.Marshal(b, m, deterministic)
}
func (dst *ScanStorageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanStorageResp.Merge(dst, src)
}
func (m *ScanStorageResp) XXX_Size() int {
	return xxx_messageInfo_ScanStorageResp.Size(m)
}
func (m *ScanStorageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanStorageResp.DiscardUnknown(m)
}

var xxx_messageInfo_ScanStorageResp proto.InternalMessageInfo

func (m *ScanStorageResp) GetCtrlrs() []*NvmeController {
	if m != nil {
		return m.Ctrlrs
	}
	return nil
}

func (m *ScanStorageResp) GetNvmestate() *ResponseState {
	if m != nil {
		return m.Nvmestate
	}
	return nil
}

func (m *ScanStorageResp) GetModules() []*ScmModule {
	if m != nil {
		return m.Modules
	}
	return nil
}

func (m *ScanStorageResp) GetScmstate() *ResponseState {
	if m != nil {
		return m.Scmstate
	}
	return nil
}

type FormatStorageReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FormatStorageReq) Reset()         { *m = FormatStorageReq{} }
func (m *FormatStorageReq) String() string { return proto.CompactTextString(m) }
func (*FormatStorageReq) ProtoMessage()    {}
func (*FormatStorageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_fbaf07d8be8e1d9c, []int{2}
}
func (m *FormatStorageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormatStorageReq.Unmarshal(m, b)
}
func (m *FormatStorageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormatStorageReq.Marshal(b, m, deterministic)
}
func (dst *FormatStorageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormatStorageReq.Merge(dst, src)
}
func (m *FormatStorageReq) XXX_Size() int {
	return xxx_messageInfo_FormatStorageReq.Size(m)
}
func (m *FormatStorageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FormatStorageReq.DiscardUnknown(m)
}

var xxx_messageInfo_FormatStorageReq proto.InternalMessageInfo

type FormatStorageResp struct {
	Crets                []*NvmeControllerResult `protobuf:"bytes,1,rep,name=crets,proto3" json:"crets,omitempty"`
	Mrets                []*ScmMountResult       `protobuf:"bytes,2,rep,name=mrets,proto3" json:"mrets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FormatStorageResp) Reset()         { *m = FormatStorageResp{} }
func (m *FormatStorageResp) String() string { return proto.CompactTextString(m) }
func (*FormatStorageResp) ProtoMessage()    {}
func (*FormatStorageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_fbaf07d8be8e1d9c, []int{3}
}
func (m *FormatStorageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormatStorageResp.Unmarshal(m, b)
}
func (m *FormatStorageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormatStorageResp.Marshal(b, m, deterministic)
}
func (dst *FormatStorageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormatStorageResp.Merge(dst, src)
}
func (m *FormatStorageResp) XXX_Size() int {
	return xxx_messageInfo_FormatStorageResp.Size(m)
}
func (m *FormatStorageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FormatStorageResp.DiscardUnknown(m)
}

var xxx_messageInfo_FormatStorageResp proto.InternalMessageInfo

func (m *FormatStorageResp) GetCrets() []*NvmeControllerResult {
	if m != nil {
		return m.Crets
	}
	return nil
}

func (m *FormatStorageResp) GetMrets() []*ScmMountResult {
	if m != nil {
		return m.Mrets
	}
	return nil
}

type UpdateStorageReq struct {
	Nvme                 *UpdateNvmeReq `protobuf:"bytes,1,opt,name=nvme,proto3" json:"nvme,omitempty"`
	Scm                  *UpdateScmReq  `protobuf:"bytes,2,opt,name=scm,proto3" json:"scm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateStorageReq) Reset()         { *m = UpdateStorageReq{} }
func (m *UpdateStorageReq) String() string { return proto.CompactTextString(m) }
func (*UpdateStorageReq) ProtoMessage()    {}
func (*UpdateStorageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_fbaf07d8be8e1d9c, []int{4}
}
func (m *UpdateStorageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStorageReq.Unmarshal(m, b)
}
func (m *UpdateStorageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStorageReq.Marshal(b, m, deterministic)
}
func (dst *UpdateStorageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStorageReq.Merge(dst, src)
}
func (m *UpdateStorageReq) XXX_Size() int {
	return xxx_messageInfo_UpdateStorageReq.Size(m)
}
func (m *UpdateStorageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStorageReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStorageReq proto.InternalMessageInfo

func (m *UpdateStorageReq) GetNvme() *UpdateNvmeReq {
	if m != nil {
		return m.Nvme
	}
	return nil
}

func (m *UpdateStorageReq) GetScm() *UpdateScmReq {
	if m != nil {
		return m.Scm
	}
	return nil
}

type UpdateStorageResp struct {
	Crets                []*NvmeControllerResult `protobuf:"bytes,1,rep,name=crets,proto3" json:"crets,omitempty"`
	Mrets                []*ScmModuleResult      `protobuf:"bytes,2,rep,name=mrets,proto3" json:"mrets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateStorageResp) Reset()         { *m = UpdateStorageResp{} }
func (m *UpdateStorageResp) String() string { return proto.CompactTextString(m) }
func (*UpdateStorageResp) ProtoMessage()    {}
func (*UpdateStorageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_fbaf07d8be8e1d9c, []int{5}
}
func (m *UpdateStorageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStorageResp.Unmarshal(m, b)
}
func (m *UpdateStorageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStorageResp.Marshal(b, m, deterministic)
}
func (dst *UpdateStorageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStorageResp.Merge(dst, src)
}
func (m *UpdateStorageResp) XXX_Size() int {
	return xxx_messageInfo_UpdateStorageResp.Size(m)
}
func (m *UpdateStorageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStorageResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStorageResp proto.InternalMessageInfo

func (m *UpdateStorageResp) GetCrets() []*NvmeControllerResult {
	if m != nil {
		return m.Crets
	}
	return nil
}

func (m *UpdateStorageResp) GetMrets() []*ScmModuleResult {
	if m != nil {
		return m.Mrets
	}
	return nil
}

type BurninStorageReq struct {
	Nvme                 *BurninNvmeReq `protobuf:"bytes,1,opt,name=nvme,proto3" json:"nvme,omitempty"`
	Scm                  *BurninScmReq  `protobuf:"bytes,2,opt,name=scm,proto3" json:"scm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BurninStorageReq) Reset()         { *m = BurninStorageReq{} }
func (m *BurninStorageReq) String() string { return proto.CompactTextString(m) }
func (*BurninStorageReq) ProtoMessage()    {}
func (*BurninStorageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_fbaf07d8be8e1d9c, []int{6}
}
func (m *BurninStorageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurninStorageReq.Unmarshal(m, b)
}
func (m *BurninStorageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurninStorageReq.Marshal(b, m, deterministic)
}
func (dst *BurninStorageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurninStorageReq.Merge(dst, src)
}
func (m *BurninStorageReq) XXX_Size() int {
	return xxx_messageInfo_BurninStorageReq.Size(m)
}
func (m *BurninStorageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BurninStorageReq.DiscardUnknown(m)
}

var xxx_messageInfo_BurninStorageReq proto.InternalMessageInfo

func (m *BurninStorageReq) GetNvme() *BurninNvmeReq {
	if m != nil {
		return m.Nvme
	}
	return nil
}

func (m *BurninStorageReq) GetScm() *BurninScmReq {
	if m != nil {
		return m.Scm
	}
	return nil
}

type BurninStorageResp struct {
	Crets                []*NvmeControllerResult `protobuf:"bytes,1,rep,name=crets,proto3" json:"crets,omitempty"`
	Mrets                []*ScmMountResult       `protobuf:"bytes,2,rep,name=mrets,proto3" json:"mrets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BurninStorageResp) Reset()         { *m = BurninStorageResp{} }
func (m *BurninStorageResp) String() string { return proto.CompactTextString(m) }
func (*BurninStorageResp) ProtoMessage()    {}
func (*BurninStorageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_fbaf07d8be8e1d9c, []int{7}
}
func (m *BurninStorageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurninStorageResp.Unmarshal(m, b)
}
func (m *BurninStorageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurninStorageResp.Marshal(b, m, deterministic)
}
func (dst *BurninStorageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurninStorageResp.Merge(dst, src)
}
func (m *BurninStorageResp) XXX_Size() int {
	return xxx_messageInfo_BurninStorageResp.Size(m)
}
func (m *BurninStorageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BurninStorageResp.DiscardUnknown(m)
}

var xxx_messageInfo_BurninStorageResp proto.InternalMessageInfo

func (m *BurninStorageResp) GetCrets() []*NvmeControllerResult {
	if m != nil {
		return m.Crets
	}
	return nil
}

func (m *BurninStorageResp) GetMrets() []*ScmMountResult {
	if m != nil {
		return m.Mrets
	}
	return nil
}

func init() {
	proto.RegisterType((*ScanStorageReq)(nil), "mgmt.ScanStorageReq")
	proto.RegisterType((*ScanStorageResp)(nil), "mgmt.ScanStorageResp")
	proto.RegisterType((*FormatStorageReq)(nil), "mgmt.FormatStorageReq")
	proto.RegisterType((*FormatStorageResp)(nil), "mgmt.FormatStorageResp")
	proto.RegisterType((*UpdateStorageReq)(nil), "mgmt.UpdateStorageReq")
	proto.RegisterType((*UpdateStorageResp)(nil), "mgmt.UpdateStorageResp")
	proto.RegisterType((*BurninStorageReq)(nil), "mgmt.BurninStorageReq")
	proto.RegisterType((*BurninStorageResp)(nil), "mgmt.BurninStorageResp")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_storage_fbaf07d8be8e1d9c) }

var fileDescriptor_storage_fbaf07d8be8e1d9c = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xdd, 0x4e, 0xe3, 0x30,
	0x10, 0x85, 0x95, 0xfe, 0xed, 0xee, 0x74, 0x77, 0xdb, 0x18, 0x90, 0xa2, 0x5c, 0x55, 0x11, 0x12,
	0xe5, 0x47, 0x05, 0xca, 0x1b, 0x80, 0xc4, 0x1d, 0x5c, 0x38, 0xe2, 0x1a, 0x05, 0xd7, 0xaa, 0x90,
	0x32, 0x76, 0x62, 0x3b, 0x7d, 0x4c, 0x9e, 0x09, 0xd9, 0x4e, 0x68, 0x1a, 0x81, 0x2a, 0x21, 0x71,
	0x7b, 0xe6, 0x9b, 0x39, 0x3e, 0x33, 0x32, 0xfc, 0xd3, 0x46, 0xaa, 0x6c, 0xcd, 0x17, 0x85, 0x92,
	0x46, 0x92, 0x01, 0xae, 0xd1, 0xc4, 0x7f, 0x99, 0x44, 0x94, 0xc2, 0x6b, 0x31, 0xa9, 0x91, 0x67,
	0xb1, 0xc1, 0x9a, 0x8b, 0xc3, 0x46, 0xd3, 0x0c, 0xbd, 0x94, 0x4c, 0xe1, 0x7f, 0xca, 0x32, 0x91,
	0xfa, 0x02, 0xe5, 0x65, 0xf2, 0x16, 0xc0, 0x64, 0x47, 0xd2, 0x05, 0xb9, 0x80, 0x11, 0x33, 0x2a,
	0x57, 0x3a, 0x0a, 0x66, 0xfd, 0xf9, 0x78, 0x79, 0xb8, 0xb0, 0x8e, 0x8b, 0xc7, 0x0d, 0xf2, 0x3b,
	0x29, 0x8c, 0x92, 0x79, 0xce, 0x15, 0xad, 0x19, 0x72, 0x0d, 0x7f, 0xac, 0xa9, 0x36, 0x99, 0xe1,
	0x51, 0x6f, 0x16, 0xcc, 0xc7, 0xcb, 0x03, 0xdf, 0x60, 0x87, 0x49, 0xa1, 0x79, 0x6a, 0x4b, 0x74,
	0x4b, 0x91, 0x53, 0xf8, 0x85, 0x72, 0x55, 0xe5, 0x5c, 0x47, 0x7d, 0xe7, 0x30, 0xf1, 0x0d, 0x29,
	0xc3, 0x07, 0xa7, 0xd3, 0xa6, 0x4e, 0x2e, 0xe1, 0xb7, 0x66, 0xe8, 0x87, 0x0f, 0xbe, 0x1e, 0xfe,
	0x01, 0x25, 0x04, 0xa6, 0xf7, 0x52, 0x61, 0x66, 0x5a, 0x21, 0x4b, 0x08, 0x3b, 0x9a, 0x2e, 0xc8,
	0x15, 0x0c, 0x99, 0xe2, 0xa6, 0x09, 0x19, 0x7f, 0x1a, 0x92, 0xeb, 0x2a, 0x37, 0xd4, 0x83, 0xe4,
	0x0c, 0x86, 0xe8, 0x3a, 0x7a, 0xed, 0xb5, 0xb8, 0x47, 0x57, 0xc2, 0x34, 0xac, 0x43, 0x92, 0x0c,
	0xa6, 0x4f, 0xc5, 0x2a, 0x33, 0x7c, 0xfb, 0x0c, 0x72, 0x02, 0x03, 0xbb, 0x83, 0x28, 0x68, 0xe7,
	0xf0, 0x94, 0xb5, 0xa5, 0xbc, 0xa4, 0x0e, 0x20, 0xc7, 0xd0, 0xd7, 0x0c, 0xeb, 0x65, 0x92, 0x36,
	0x97, 0x32, 0xb4, 0x98, 0x2d, 0x27, 0x0a, 0xc2, 0x8e, 0xc5, 0xb7, 0x52, 0x9d, 0xef, 0xa6, 0x3a,
	0xea, 0x9e, 0xa2, 0x1b, 0xeb, 0xb6, 0x52, 0xe2, 0x55, 0xec, 0x8b, 0xe5, 0xa9, 0xfd, 0xb1, 0xea,
	0x69, 0xad, 0x58, 0x25, 0x84, 0x1d, 0x8b, 0x9f, 0x3e, 0xd6, 0xcb, 0xc8, 0xfd, 0x8e, 0x9b, 0xf7,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0x61, 0x59, 0x37, 0x69, 0x03, 0x00, 0x00,
}
