// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage_nvme.proto

package mgmt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// NvmeController represents an NVMe Controller (SSD).
type NvmeController struct {
	Model                string                      `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Serial               string                      `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Pciaddr              string                      `protobuf:"bytes,3,opt,name=pciaddr,proto3" json:"pciaddr,omitempty"`
	Fwrev                string                      `protobuf:"bytes,4,opt,name=fwrev,proto3" json:"fwrev,omitempty"`
	Socketid             int32                       `protobuf:"varint,5,opt,name=socketid,proto3" json:"socketid,omitempty"`
	Namespaces           []*NvmeController_Namespace `protobuf:"bytes,6,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *NvmeController) Reset()         { *m = NvmeController{} }
func (m *NvmeController) String() string { return proto.CompactTextString(m) }
func (*NvmeController) ProtoMessage()    {}
func (*NvmeController) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_nvme_99f5e32c76b592a6, []int{0}
}
func (m *NvmeController) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NvmeController.Unmarshal(m, b)
}
func (m *NvmeController) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NvmeController.Marshal(b, m, deterministic)
}
func (dst *NvmeController) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NvmeController.Merge(dst, src)
}
func (m *NvmeController) XXX_Size() int {
	return xxx_messageInfo_NvmeController.Size(m)
}
func (m *NvmeController) XXX_DiscardUnknown() {
	xxx_messageInfo_NvmeController.DiscardUnknown(m)
}

var xxx_messageInfo_NvmeController proto.InternalMessageInfo

func (m *NvmeController) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *NvmeController) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *NvmeController) GetPciaddr() string {
	if m != nil {
		return m.Pciaddr
	}
	return ""
}

func (m *NvmeController) GetFwrev() string {
	if m != nil {
		return m.Fwrev
	}
	return ""
}

func (m *NvmeController) GetSocketid() int32 {
	if m != nil {
		return m.Socketid
	}
	return 0
}

func (m *NvmeController) GetNamespaces() []*NvmeController_Namespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

// Namespace represents a namespace created on an NvmeController.
type NvmeController_Namespace struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NvmeController_Namespace) Reset()         { *m = NvmeController_Namespace{} }
func (m *NvmeController_Namespace) String() string { return proto.CompactTextString(m) }
func (*NvmeController_Namespace) ProtoMessage()    {}
func (*NvmeController_Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_nvme_99f5e32c76b592a6, []int{0, 0}
}
func (m *NvmeController_Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NvmeController_Namespace.Unmarshal(m, b)
}
func (m *NvmeController_Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NvmeController_Namespace.Marshal(b, m, deterministic)
}
func (dst *NvmeController_Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NvmeController_Namespace.Merge(dst, src)
}
func (m *NvmeController_Namespace) XXX_Size() int {
	return xxx_messageInfo_NvmeController_Namespace.Size(m)
}
func (m *NvmeController_Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_NvmeController_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_NvmeController_Namespace proto.InternalMessageInfo

func (m *NvmeController_Namespace) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NvmeController_Namespace) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

// NvmeControllerResult represents state of operation performed on controller.
type NvmeControllerResult struct {
	Pciaddr              string         `protobuf:"bytes,1,opt,name=pciaddr,proto3" json:"pciaddr,omitempty"`
	State                *ResponseState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NvmeControllerResult) Reset()         { *m = NvmeControllerResult{} }
func (m *NvmeControllerResult) String() string { return proto.CompactTextString(m) }
func (*NvmeControllerResult) ProtoMessage()    {}
func (*NvmeControllerResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_nvme_99f5e32c76b592a6, []int{1}
}
func (m *NvmeControllerResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NvmeControllerResult.Unmarshal(m, b)
}
func (m *NvmeControllerResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NvmeControllerResult.Marshal(b, m, deterministic)
}
func (dst *NvmeControllerResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NvmeControllerResult.Merge(dst, src)
}
func (m *NvmeControllerResult) XXX_Size() int {
	return xxx_messageInfo_NvmeControllerResult.Size(m)
}
func (m *NvmeControllerResult) XXX_DiscardUnknown() {
	xxx_messageInfo_NvmeControllerResult.DiscardUnknown(m)
}

var xxx_messageInfo_NvmeControllerResult proto.InternalMessageInfo

func (m *NvmeControllerResult) GetPciaddr() string {
	if m != nil {
		return m.Pciaddr
	}
	return ""
}

func (m *NvmeControllerResult) GetState() *ResponseState {
	if m != nil {
		return m.State
	}
	return nil
}

type PrepareNvmeReq struct {
	Pciwhitelist         string   `protobuf:"bytes,1,opt,name=pciwhitelist,proto3" json:"pciwhitelist,omitempty"`
	Nrhugepages          int32    `protobuf:"varint,2,opt,name=nrhugepages,proto3" json:"nrhugepages,omitempty"`
	Targetuser           string   `protobuf:"bytes,3,opt,name=targetuser,proto3" json:"targetuser,omitempty"`
	Reset_               bool     `protobuf:"varint,4,opt,name=reset,proto3" json:"reset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareNvmeReq) Reset()         { *m = PrepareNvmeReq{} }
func (m *PrepareNvmeReq) String() string { return proto.CompactTextString(m) }
func (*PrepareNvmeReq) ProtoMessage()    {}
func (*PrepareNvmeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_nvme_99f5e32c76b592a6, []int{2}
}
func (m *PrepareNvmeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareNvmeReq.Unmarshal(m, b)
}
func (m *PrepareNvmeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareNvmeReq.Marshal(b, m, deterministic)
}
func (dst *PrepareNvmeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareNvmeReq.Merge(dst, src)
}
func (m *PrepareNvmeReq) XXX_Size() int {
	return xxx_messageInfo_PrepareNvmeReq.Size(m)
}
func (m *PrepareNvmeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareNvmeReq.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareNvmeReq proto.InternalMessageInfo

func (m *PrepareNvmeReq) GetPciwhitelist() string {
	if m != nil {
		return m.Pciwhitelist
	}
	return ""
}

func (m *PrepareNvmeReq) GetNrhugepages() int32 {
	if m != nil {
		return m.Nrhugepages
	}
	return 0
}

func (m *PrepareNvmeReq) GetTargetuser() string {
	if m != nil {
		return m.Targetuser
	}
	return ""
}

func (m *PrepareNvmeReq) GetReset_() bool {
	if m != nil {
		return m.Reset_
	}
	return false
}

type PrepareNvmeResp struct {
	State                *ResponseState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PrepareNvmeResp) Reset()         { *m = PrepareNvmeResp{} }
func (m *PrepareNvmeResp) String() string { return proto.CompactTextString(m) }
func (*PrepareNvmeResp) ProtoMessage()    {}
func (*PrepareNvmeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_nvme_99f5e32c76b592a6, []int{3}
}
func (m *PrepareNvmeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareNvmeResp.Unmarshal(m, b)
}
func (m *PrepareNvmeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareNvmeResp.Marshal(b, m, deterministic)
}
func (dst *PrepareNvmeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareNvmeResp.Merge(dst, src)
}
func (m *PrepareNvmeResp) XXX_Size() int {
	return xxx_messageInfo_PrepareNvmeResp.Size(m)
}
func (m *PrepareNvmeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareNvmeResp.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareNvmeResp proto.InternalMessageInfo

func (m *PrepareNvmeResp) GetState() *ResponseState {
	if m != nil {
		return m.State
	}
	return nil
}

type ScanNvmeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanNvmeReq) Reset()         { *m = ScanNvmeReq{} }
func (m *ScanNvmeReq) String() string { return proto.CompactTextString(m) }
func (*ScanNvmeReq) ProtoMessage()    {}
func (*ScanNvmeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_nvme_99f5e32c76b592a6, []int{4}
}
func (m *ScanNvmeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanNvmeReq.Unmarshal(m, b)
}
func (m *ScanNvmeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanNvmeReq.Marshal(b, m, deterministic)
}
func (dst *ScanNvmeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanNvmeReq.Merge(dst, src)
}
func (m *ScanNvmeReq) XXX_Size() int {
	return xxx_messageInfo_ScanNvmeReq.Size(m)
}
func (m *ScanNvmeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanNvmeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ScanNvmeReq proto.InternalMessageInfo

type ScanNvmeResp struct {
	Ctrlrs               []*NvmeController `protobuf:"bytes,1,rep,name=ctrlrs,proto3" json:"ctrlrs,omitempty"`
	State                *ResponseState    `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ScanNvmeResp) Reset()         { *m = ScanNvmeResp{} }
func (m *ScanNvmeResp) String() string { return proto.CompactTextString(m) }
func (*ScanNvmeResp) ProtoMessage()    {}
func (*ScanNvmeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_nvme_99f5e32c76b592a6, []int{5}
}
func (m *ScanNvmeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanNvmeResp.Unmarshal(m, b)
}
func (m *ScanNvmeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanNvmeResp.Marshal(b, m, deterministic)
}
func (dst *ScanNvmeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanNvmeResp.Merge(dst, src)
}
func (m *ScanNvmeResp) XXX_Size() int {
	return xxx_messageInfo_ScanNvmeResp.Size(m)
}
func (m *ScanNvmeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanNvmeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ScanNvmeResp proto.InternalMessageInfo

func (m *ScanNvmeResp) GetCtrlrs() []*NvmeController {
	if m != nil {
		return m.Ctrlrs
	}
	return nil
}

func (m *ScanNvmeResp) GetState() *ResponseState {
	if m != nil {
		return m.State
	}
	return nil
}

type FormatNvmeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FormatNvmeReq) Reset()         { *m = FormatNvmeReq{} }
func (m *FormatNvmeReq) String() string { return proto.CompactTextString(m) }
func (*FormatNvmeReq) ProtoMessage()    {}
func (*FormatNvmeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_nvme_99f5e32c76b592a6, []int{6}
}
func (m *FormatNvmeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormatNvmeReq.Unmarshal(m, b)
}
func (m *FormatNvmeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormatNvmeReq.Marshal(b, m, deterministic)
}
func (dst *FormatNvmeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormatNvmeReq.Merge(dst, src)
}
func (m *FormatNvmeReq) XXX_Size() int {
	return xxx_messageInfo_FormatNvmeReq.Size(m)
}
func (m *FormatNvmeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FormatNvmeReq.DiscardUnknown(m)
}

var xxx_messageInfo_FormatNvmeReq proto.InternalMessageInfo

type UpdateNvmeReq struct {
	Model                string   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Startrev             string   `protobuf:"bytes,2,opt,name=startrev,proto3" json:"startrev,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Slot                 int32    `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNvmeReq) Reset()         { *m = UpdateNvmeReq{} }
func (m *UpdateNvmeReq) String() string { return proto.CompactTextString(m) }
func (*UpdateNvmeReq) ProtoMessage()    {}
func (*UpdateNvmeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_nvme_99f5e32c76b592a6, []int{7}
}
func (m *UpdateNvmeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNvmeReq.Unmarshal(m, b)
}
func (m *UpdateNvmeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNvmeReq.Marshal(b, m, deterministic)
}
func (dst *UpdateNvmeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNvmeReq.Merge(dst, src)
}
func (m *UpdateNvmeReq) XXX_Size() int {
	return xxx_messageInfo_UpdateNvmeReq.Size(m)
}
func (m *UpdateNvmeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNvmeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNvmeReq proto.InternalMessageInfo

func (m *UpdateNvmeReq) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *UpdateNvmeReq) GetStartrev() string {
	if m != nil {
		return m.Startrev
	}
	return ""
}

func (m *UpdateNvmeReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *UpdateNvmeReq) GetSlot() int32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

// TODO: provide facility to supply FIO config in params
type BurninNvmeReq struct {
	Fioconfig            *FilePath `protobuf:"bytes,1,opt,name=fioconfig,proto3" json:"fioconfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BurninNvmeReq) Reset()         { *m = BurninNvmeReq{} }
func (m *BurninNvmeReq) String() string { return proto.CompactTextString(m) }
func (*BurninNvmeReq) ProtoMessage()    {}
func (*BurninNvmeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_nvme_99f5e32c76b592a6, []int{8}
}
func (m *BurninNvmeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurninNvmeReq.Unmarshal(m, b)
}
func (m *BurninNvmeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurninNvmeReq.Marshal(b, m, deterministic)
}
func (dst *BurninNvmeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurninNvmeReq.Merge(dst, src)
}
func (m *BurninNvmeReq) XXX_Size() int {
	return xxx_messageInfo_BurninNvmeReq.Size(m)
}
func (m *BurninNvmeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BurninNvmeReq.DiscardUnknown(m)
}

var xxx_messageInfo_BurninNvmeReq proto.InternalMessageInfo

func (m *BurninNvmeReq) GetFioconfig() *FilePath {
	if m != nil {
		return m.Fioconfig
	}
	return nil
}

func init() {
	proto.RegisterType((*NvmeController)(nil), "mgmt.NvmeController")
	proto.RegisterType((*NvmeController_Namespace)(nil), "mgmt.NvmeController.Namespace")
	proto.RegisterType((*NvmeControllerResult)(nil), "mgmt.NvmeControllerResult")
	proto.RegisterType((*PrepareNvmeReq)(nil), "mgmt.PrepareNvmeReq")
	proto.RegisterType((*PrepareNvmeResp)(nil), "mgmt.PrepareNvmeResp")
	proto.RegisterType((*ScanNvmeReq)(nil), "mgmt.ScanNvmeReq")
	proto.RegisterType((*ScanNvmeResp)(nil), "mgmt.ScanNvmeResp")
	proto.RegisterType((*FormatNvmeReq)(nil), "mgmt.FormatNvmeReq")
	proto.RegisterType((*UpdateNvmeReq)(nil), "mgmt.UpdateNvmeReq")
	proto.RegisterType((*BurninNvmeReq)(nil), "mgmt.BurninNvmeReq")
}

func init() { proto.RegisterFile("storage_nvme.proto", fileDescriptor_storage_nvme_99f5e32c76b592a6) }

var fileDescriptor_storage_nvme_99f5e32c76b592a6 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x45, 0x8e, 0xe5, 0xc6, 0xe3, 0x8f, 0xc0, 0xd6, 0x14, 0xe1, 0x43, 0x30, 0x3a, 0xb9, 0x10,
	0x7c, 0x48, 0x0f, 0xbd, 0xb4, 0x3d, 0xb4, 0x90, 0x63, 0x08, 0x1b, 0x7a, 0xea, 0xa1, 0x6c, 0x57,
	0x63, 0x79, 0xa9, 0xa4, 0xdd, 0xee, 0x8e, 0x1d, 0x7a, 0xee, 0xb5, 0x3f, 0xba, 0xec, 0xae, 0x2c,
	0x5b, 0x10, 0x28, 0xb9, 0xed, 0x9b, 0x19, 0xcd, 0xbc, 0xf7, 0x66, 0x04, 0xcc, 0x91, 0xb6, 0xa2,
	0xc4, 0xef, 0xcd, 0xa1, 0xc6, 0x8d, 0xb1, 0x9a, 0x34, 0x1b, 0xd6, 0x65, 0x4d, 0xcb, 0xa9, 0xd4,
	0x75, 0xad, 0x9b, 0x18, 0xcb, 0xff, 0x0c, 0x60, 0x7e, 0x7f, 0xa8, 0xf1, 0x8b, 0x6e, 0xc8, 0xea,
	0xaa, 0x42, 0xcb, 0x16, 0x90, 0xd6, 0xba, 0xc0, 0x2a, 0x4b, 0x56, 0xc9, 0x7a, 0xcc, 0x23, 0x60,
	0x6f, 0x60, 0xe4, 0xd0, 0x2a, 0x51, 0x65, 0x83, 0x10, 0x6e, 0x11, 0xcb, 0xe0, 0x95, 0x91, 0x4a,
	0x14, 0x85, 0xcd, 0x2e, 0x42, 0xe2, 0x08, 0x7d, 0x9f, 0xed, 0x93, 0xc5, 0x43, 0x36, 0x8c, 0x7d,
	0x02, 0x60, 0x4b, 0xb8, 0x74, 0x5a, 0xfe, 0x44, 0x52, 0x45, 0x96, 0xae, 0x92, 0x75, 0xca, 0x3b,
	0xcc, 0x3e, 0x01, 0x34, 0xa2, 0x46, 0x67, 0x84, 0x44, 0x97, 0x8d, 0x56, 0x17, 0xeb, 0xc9, 0xed,
	0xf5, 0xc6, 0xb3, 0xde, 0xf4, 0x39, 0x6e, 0xee, 0x8f, 0x65, 0xfc, 0xec, 0x8b, 0xe5, 0x7b, 0x18,
	0x77, 0x09, 0x36, 0x87, 0x81, 0x2a, 0x82, 0x86, 0x94, 0x0f, 0x54, 0xe1, 0x07, 0x4b, 0x61, 0x84,
	0x54, 0xf4, 0x3b, 0x48, 0x48, 0x79, 0x87, 0xf3, 0x6f, 0xb0, 0xe8, 0x0f, 0xe0, 0xe8, 0xf6, 0x15,
	0x9d, 0x8b, 0x4b, 0xfa, 0xe2, 0xde, 0x42, 0xea, 0x48, 0x10, 0x86, 0x56, 0x93, 0xdb, 0xd7, 0x91,
	0x25, 0x47, 0x67, 0x74, 0xe3, 0xf0, 0xd1, 0xa7, 0x78, 0xac, 0xc8, 0xff, 0x26, 0x30, 0x7f, 0xb0,
	0x68, 0x84, 0x45, 0x3f, 0x84, 0xe3, 0x2f, 0x96, 0xc3, 0xd4, 0x48, 0xf5, 0xb4, 0x53, 0x84, 0x95,
	0x72, 0xd4, 0x36, 0xef, 0xc5, 0xd8, 0x0a, 0x26, 0x8d, 0xdd, 0xed, 0x4b, 0x34, 0xa2, 0x44, 0xd7,
	0x52, 0x3e, 0x0f, 0xb1, 0x6b, 0x00, 0x12, 0xb6, 0x44, 0xda, 0x3b, 0x3c, 0xba, 0x7f, 0x16, 0xf1,
	0x0b, 0xb0, 0xe8, 0x90, 0xc2, 0x02, 0x2e, 0x79, 0x04, 0xf9, 0x07, 0xb8, 0xea, 0xb1, 0x71, 0xe6,
	0x24, 0x26, 0xf9, 0xaf, 0x98, 0x19, 0x4c, 0x1e, 0xa5, 0x68, 0x5a, 0x21, 0x79, 0x09, 0xd3, 0x13,
	0x74, 0x86, 0xdd, 0xc0, 0x48, 0x92, 0xad, 0xac, 0xcb, 0x92, 0xb0, 0xbd, 0xc5, 0x73, 0xdb, 0xe3,
	0x6d, 0xcd, 0x4b, 0x4c, 0xbc, 0x82, 0xd9, 0x9d, 0xb6, 0xb5, 0xa0, 0xe3, 0x64, 0x05, 0xb3, 0xaf,
	0xa6, 0x10, 0xd4, 0x79, 0xfa, 0xfc, 0xd9, 0xfa, 0x73, 0x23, 0x61, 0xc9, 0xdf, 0x61, 0x3c, 0xdc,
	0x0e, 0x33, 0x06, 0x43, 0x23, 0x68, 0xd7, 0x3a, 0x17, 0xde, 0x3e, 0xe6, 0x2a, 0x1d, 0x2d, 0x4b,
	0x79, 0x78, 0xe7, 0x1f, 0x61, 0xf6, 0x79, 0x6f, 0x1b, 0x75, 0x54, 0xcd, 0x6e, 0x60, 0xbc, 0x55,
	0x5a, 0xea, 0x66, 0xab, 0xca, 0xd6, 0xb3, 0x79, 0xe4, 0x7e, 0xa7, 0x2a, 0x7c, 0x10, 0xb4, 0xe3,
	0xa7, 0x82, 0x1f, 0xa3, 0xf0, 0xa7, 0xbd, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xb6, 0xd3,
	0x0e, 0x93, 0x03, 0x00, 0x00,
}
