"""Build drpc test"""


def scons():
    """Execute build"""
    Import('env')

    libs = ['daos', 'daos_common', 'cmocka', 'gurt']
    sources = ['rpc_tests.c']

    denv = env.Clone()
    denv.AppendUnique(CPPPATH=[Dir('../../include/internal').srcnode()])
    denv.AppendUnique(CPPDEFINES=['TEST'])

    # Testing internal interfaces ...
    denv.AppendUnique(CPPPATH=[Dir('../../').srcnode()])

    rpc_test = denv.d_program('rpc_tests', sources, LIBS=libs)
    env.Install('$PREFIX/bin/', rpc_test)


if __name__ == "SCons.Script":
    scons()
