"""Build drpc test"""


def scons():
    """Execute build"""
    Import('env')

    libs = ['daos', 'daos_common', 'cmocka', 'gurt']
    sources = ['rpc_tests.c']

    denv = env.Clone()
    denv.d_internal_headers()
    denv.d_internal_headers(src_dir="object")
    denv.AppendUnique(CPPDEFINES=['TEST'])

    denv.d_test_program('rpc_tests', sources, LIBS=libs)


if __name__ == "SCons.Script":
    scons()
