//
// (C) Copyright 2026 Hewlett Packard Enterprise Development LP
//
// SPDX-License-Identifier: BSD-2-Clause-Patent
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.14.0
// source: pop.proto

package security

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PoPPayload is the signed proof-of-possession payload attached to pool
// connect credentials.
type PoPPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolUuid      []byte                 `protobuf:"bytes,1,opt,name=pool_uuid,json=poolUuid,proto3" json:"pool_uuid,omitempty"`       // UUID (16 bytes) of the pool being connected
	HandleUuid    []byte                 `protobuf:"bytes,2,opt,name=handle_uuid,json=handleUuid,proto3" json:"handle_uuid,omitempty"` // UUID (16 bytes) of the new pool handle
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // Unix seconds when the proof was created
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoPPayload) Reset() {
	*x = PoPPayload{}
	mi := &file_pop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoPPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoPPayload) ProtoMessage() {}

func (x *PoPPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoPPayload.ProtoReflect.Descriptor instead.
func (*PoPPayload) Descriptor() ([]byte, []int) {
	return file_pop_proto_rawDescGZIP(), []int{0}
}

func (x *PoPPayload) GetPoolUuid() []byte {
	if x != nil {
		return x.PoolUuid
	}
	return nil
}

func (x *PoPPayload) GetHandleUuid() []byte {
	if x != nil {
		return x.HandleUuid
	}
	return nil
}

func (x *PoPPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pop_proto protoreflect.FileDescriptor

const file_pop_proto_rawDesc = "" +
	"\n" +
	"\tpop.proto\x12\bsecurity\"h\n" +
	"\n" +
	"PoPPayload\x12\x1b\n" +
	"\tpool_uuid\x18\x01 \x01(\fR\bpoolUuid\x12\x1f\n" +
	"\vhandle_uuid\x18\x02 \x01(\fR\n" +
	"handleUuid\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestampB:Z8github.com/daos-stack/daos/src/control/security;securityb\x06proto3"

var (
	file_pop_proto_rawDescOnce sync.Once
	file_pop_proto_rawDescData []byte
)

func file_pop_proto_rawDescGZIP() []byte {
	file_pop_proto_rawDescOnce.Do(func() {
		file_pop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pop_proto_rawDesc), len(file_pop_proto_rawDesc)))
	})
	return file_pop_proto_rawDescData
}

var file_pop_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pop_proto_goTypes = []any{
	(*PoPPayload)(nil), // 0: security.PoPPayload
}
var file_pop_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pop_proto_init() }
func file_pop_proto_init() {
	if File_pop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pop_proto_rawDesc), len(file_pop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pop_proto_goTypes,
		DependencyIndexes: file_pop_proto_depIdxs,
		MessageInfos:      file_pop_proto_msgTypes,
	}.Build()
	File_pop_proto = out.File
	file_pop_proto_goTypes = nil
	file_pop_proto_depIdxs = nil
}
