"""Build management server module"""
import daos_build

def scons():
    """Execute build"""
    Import('env')

    env.AppendUnique(LIBPATH=[Dir('.')])

    denv = env.Clone()

    common = denv.SharedObject(['rpc.c'])
    # Management server module
    mgmt_srv = daos_build.library(denv, 'mgmt', [common, Glob('srv*.c')])
    denv.Install('$PREFIX/lib/daos_srv', mgmt_srv)

    # Management client library
    dc_mgmt_tgts = common + denv.SharedObject([Glob('cli*.c')])
    Export('dc_mgmt_tgts')

if __name__ == "SCons.Script":
    scons()
