name: Code Coverage Test

on:
  pull_request:             # Remove after testing
  schedule:
    - cron: "0 0 * * 6"     # Every Saturday

concurrency:
  group: code-coverage-${{ github.head_ref  || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -ueo pipefail {0}

permissions: {}

jobs:
  build-rpms:
    name: Bullseye Build RPMs
    runs-on: [self-hosted, docker]
    permissions:
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Build RPMs
        uses: ./.github/actions/build-rpm
        with:
          distro: el8
          covfn_disabled: false

  functional-test:
    name: Bullseye Functional Test
    runs-on: [self-hosted, wolf]
    permissions:
      statuses: write
      # https://github.com/EnricoMi/publish-unit-test-result-action#permissions
      checks: write
      pull-requests: write
    timeout-minutes: 7200
    needs: [build-rpms]
    if: |
      (!cancelled()) &&
      (needs.build-rpms.result == 'success' ||
       needs.build-rpms.result == 'skipped')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Build RPMs
        uses: ./.github/actions/functional-test
        with:
          distro: el8
          tags: test_one_pool_vm
