name: Code Coverage Test

on:
  pull_request:             # Remove after testing
  schedule:
    - cron: "0 0 * * 6"     # Every Saturday

concurrency:
  group: code-coverage-${{ github.head_ref  || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -ueo pipefail {0}

permissions: {}

jobs:
  call-build-rpm:
    uses: ./.github/actions/build-rpm
    with:
      distro: el8
      covfn_disabled: false

  call-functional-test:
    uses: ./.github/actions/functional-test
    needs: [call-build-rpm]
    if: |
      (!cancelled()) &&
      (needs.call-build-rpm.result == 'success' ||
       needs.call-build-rpm.result == 'skipped')
    with:
      distro: el8
      tags: test_one_pool_vm
