name: 'RPM Build and Test Report'

on:
  workflow_run:
    workflows: ['RPM Build and Test']
    types:
      - completed
  # for testing before landing
  workflow_dispatch:

permissions: {}

jobs:
  report-vm-1:
    runs-on: [self-hosted, docker]
    # https://github.com/dorny/test-reporter/issues/149
    permissions:
      checks: write
    strategy:
      matrix:
        # TODO: figure out how to determine this matrix
        distro: ['el8', 'el9', 'leap15']
    env:
      STAGE_NAME:
    steps:
      - name: Set variables
        run: |
            case ${{ matrix.distro }} in
                'el8')
                    DISTRO_NAME="EL"
                    DISTRO_VERSION="8"
                    ;;
                'el9')
                    DISTRO_NAME="EL"
                    DISTRO_VERSION="9"
                    ;;
                'leap15')
                    DISTRO_NAME="Leap"
                    DISTRO_VERSION="15.4"
                    ;;
            esac
            echo "STAGE_NAME=Build RPM on $DISTRO_NAME $DISTRO_VERSION" >> $GITHUB_ENV
      - name: Test Report
        uses: phoenix-actions/test-reporting@f957cd93fc2d848d556fa0d03c57bc79127b6b5e  # v15
        with:
          artifact: ${{ env.STAGE_NAME }} test-results
          name: ${{ env.STAGE_NAME }} Test Results (phoenix-actions)
          path: ${{ env.STAGE_NAME }}/**/results.xml
          reporter: java-junit        # Format of test results

  report-hw-1:
    runs-on: [self-hosted, docker]
    strategy:
      matrix:
        # TODO: figure out how to determine this matrix
        stage: ['Large', 'Medium', 'Medium UCX Provider']
    env:
      STAGE_NAME:
    steps:
      - name: Set variables
        run: echo "STAGE_NAME=Functional Hardware ${{ matrix.stage }}" >> $GITHUB_ENV
      - name: Test Report
        uses: phoenix-actions/test-reporting@f957cd93fc2d848d556fa0d03c57bc79127b6b5e  # v15
        with:
          artifact: ${{ env.STAGE_NAME }} test-results
          name: ${{ env.STAGE_NAME }} Test Results (phoenix-actions)
          path: ${{ env.STAGE_NAME }}/**/results.xml
          reporter: java-junit        # Format of test results

  report2:
    runs-on: [self-hosted, docker]
    strategy:
      matrix:
        distro: ['el8', 'el9', 'leap15']
    env:
      STAGE_NAME:
    steps:
      - name: Set variables
        run: |
            case ${{ matrix.distro }} in
                'el8')
                    DISTRO_NAME="EL"
                    DISTRO_VERSION="8"
                    ;;
                'el9')
                    DISTRO_NAME="EL"
                    DISTRO_VERSION="9"
                    ;;
                'leap15')
                    DISTRO_NAME="Leap"
                    DISTRO_VERSION="15.4"
                    ;;
            esac
            echo "STAGE_NAME=Build RPM on $DISTRO_NAME $DISTRO_VERSION" >> $GITHUB_ENV
      - name: Test Report
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3  # v2.1.1
        with:
          artifact: ${{ env.STAGE_NAME }} test-results
          name: ${{ env.STAGE_NAME }} Test Results (dorny)
          path: ${{ env.STAGE_NAME }}/**/results.xml
          reporter: jest-junit        # Format of test results

  report-hw-2:
    runs-on: [self-hosted, docker]
    strategy:
      matrix:
        # TODO: figure out how to determine this matrix
        stage: ['Large', 'Medium', 'Medium UCX Provider']
    env:
      STAGE_NAME:
    steps:
      - name: Set variables
        run: echo "STAGE_NAME=Functional Hardware ${{ matrix.stage }}" >> $GITHUB_ENV
      - name: Test Report
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3  # v2.1.1
        with:
          artifact: ${{ env.STAGE_NAME }} test-results
          name: ${{ env.STAGE_NAME }} Test Results (dorny)
          path: ${{ env.STAGE_NAME }}/**/results.xml
          reporter: java-junit        # Format of test results
