name: 'RPM Build and Test Report'
on:
  workflow_run:
    workflows:
      - 'RPM Build and Test'
    types:
      - completed

jobs:
  report:
    name: 'Report'
    runs-on: [self-hosted, light]
    steps:
      - name: Test Report
        uses: phoenix-actions/test-reporting@v10
        id: test-report
        with:
          artifact: test-results
          name: ${{ env.STAGE_NAME }} Test Results (new)
          path: ${{ env.STAGE_NAME }}/**/results.xml
          reporter: java-junit        # Format of test results
          fail-on-error: false
