"""Build placement code"""
import daos_build

def scons():
    """Execute build"""
    Import('env')

    env.AppendUnique(LIBPATH=[Dir('.')])

    denv = env.Clone()

    # Common placement code
    common_tgts = denv.SharedObject(['pl_map.c', 'ring_map.c'])

    # generate server module
    srv = daos_build.library(denv, 'placement', common_tgts)
    denv.Install('$PREFIX/lib/daos_srv', srv)

    # placement client library
    dc_placement_tgts = common_tgts
    Export("dc_placement_tgts")

    # Build tests
    SConscript('tests/SConscript', exports=['denv', 'common_tgts'])

if __name__ == "SCons.Script":
    scons()
