"""Build go-spdk bindings C tests"""
from __future__ import print_function
import daos_build

def scons():
    """Execute build"""
    Import('senv', 'prereqs')

    unit_env = senv.Clone()
    prereqs.require(unit_env, 'pmdk', 'spdk', 'isal', 'hwloc', 'cmocka')

    # spdk/lib/nvme to expose normally opaque types during tests
    unit_env.AppendUnique(CPPPATH=["$SPDK_SRC/lib/nvme",
                                   "$SPDK_SRC/include"])

    # SPDK related libs
    libs = ['spdk_env_dpdk', 'spdk_thread', 'spdk_bdev', 'spdk_copy']
    libs += ['rte_mempool', 'rte_mempool_ring', 'rte_bus_pci']
    libs += ['rte_pci', 'rte_ring', 'rte_mbuf', 'rte_eal', 'rte_kvargs']
    libs += ['spdk_bdev_aio', 'spdk_bdev_nvme', 'spdk_bdev_malloc']
    libs += ['spdk_conf', 'spdk_blob', 'spdk_nvme', 'spdk_util']
    libs += ['spdk_json', 'spdk_jsonrpc', 'spdk_rpc', 'spdk_trace']
    libs += ['spdk_sock', 'spdk_log', 'spdk_notify', 'spdk_blob_bdev']
    libs += ['spdk_vmd']

    # Other libs
    libs += ['numa', 'dl', 'isal', 'cmocka', 'pthread']

    if GetOption('help'):
        return
    config = Configure(unit_env)

    if GetOption('clean') or config.CheckHeader("nvme_internal.h"):
        testbin = daos_build.test(unit_env, 'nvme_control_ctests',
                                  ['nvme_control_ut.c', unit_env.ncc,
                                   unit_env.nc], LIBS=libs)
        unit_env.Install("$PREFIX/bin", testbin)
    else:
        print("SPDK nvme_internal.h missing, skipping nvme_control_ut build")

    config.Finish()

if __name__ == "SCons.Script":
    scons()
