#!/bin/bash

# find the base branch of the current branch

set -eux -o pipefail

max_commits=${1:-200}
base_branch_re=${2:-'^  origin/(master|release/)'}

n=0
while [ "$n" -lt "$max_commits" ]; do
    if git branch -r --contains HEAD~$n | grep -E "$base_branch_re" | sed -e 's/^ *[^\/]*\///'; then
        exit 0
    fi
    ((n++)) || true
done

echo "Could not find a base branch within $max_commits commits" >&2
exit 1
